### ISSUE TITLE
Idea: Upgrade that allow players to be able to hold large items like small items (never hands full)

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#1]
I personally think this will be very useful for lategame! The reason is the fact that sometimes the rng god can be cruel and spawn a lot of large items to you and your friend that small team just don't have enough time to grab them all.
I think the upgrade can be called "Hand Augmentation" or something related to arms and hands. Thank you!

Note: I tried to join discord and post my idea there, but the last time I checked, the invitation wasn't valid.

**Comment by Malcolm-Q** [comment]
The link has been updated, thanks for letting me know. That suggestion will likely be implemented. Just a little more polishing in the mean time.
