### ISSUE TITLE
Question about AssetBundle

### ISSUE THREAD

**Issue by erikhoj** [Malcolm-Q/LC-LateGameUpgrades#10]
Hi there!

I was looking through your source code to learn a bit about how to do certain things in Lethal Company, and saw that you load a custom asset bundle called `shipupdrades`.

How did you go about creating that AssetBundle? I can see that you have access to the `Item` Scriptable Object type and other things that are present in the Lethal Company binaries.

**Comment by Malcolm-Q** [comment]
Hello,

shipupgrades is a [unity asset bundle](https://docs.unity3d.com/ScriptReference/AssetBundle.html). Asset bundles are from what I can tell the simplest way to load additional content at runtime in Unity Games.

They're handy for including custom sounds, models, and prefabs to be registered with the network manager.

If you want to create complex objects that use the games scripts you can set up a Unity 2022.3.9f1 project by [following these intructions](https://github.com/EvaisaDev/LethalCompanyUnityTemplate). Evaisa has many very helpful tools so I'd bookmark that.

Then you should have everything at your fingertips, create a prefab and in the bottom of the inspector you should see "Asset Labels" and you can assign a label in the "AssetBundle" field. Then there's a third party addon thing some people use but I just have a script in the Editor folder that converts marked prefabs to asset bundles.

```csharp
...
public class CreateAssetBundles
{
	[MenuItem("Assets/Build AssetBundles")]
	static void BuildAllAssetBundles()
	{
        string assetBundleDirectory = "Assets/StreamingAssets";
        if (!Directory.Exists(Application.streamingAssetsPath))
        {
            Directory.CreateDirectory(assetBundleDirectory);
        }
        BuildPipeline.BuildAssetBundles(Application.streamingAssetsPath, BuildAssetBundleOptions.None, EditorUserBuildSettings.activeBuildTarget);
	}

}
````

Then you're good to load them. It should generate an assetbundle file with the same name as the label you gave it and a manifest file. Open the manifest file in notepad++ or something and you can see the path of each asset in the bundle.

Then you're good to go.
