### ISSUE TITLE
In the terminal after updating Lategame_Upgrades-2.8.4

### ISSUE THREAD

**Issue by Paradox75831004** [Malcolm-Q/LC-LateGameUpgrades#108]
What's wrong with the terminal? Why do some things cost 0? What is this anyway?

https://postimg.cc/9wQt75yS

**Comment by Paradox75831004** [comment]
![c0PPupfF](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72872478/d86e30a0-55a1-4700-9a17-e2632d5c07a6)

**Comment by WhiteSpike** [comment]
An oopsie from @Malcolm-Q , those are drops from monsters when "Hunter" upgrade is on, for example:
Tier 1 Hunter allows Hoarding Bug and Snare Flea to drop samples.
Tier 2 Hunter allows Bunker Spider and Baboon Hawk to drop samples
Tier 3 Hunter allows Bracken, Thumper and Eyeless Dog to drop samples.

All of these samples are meant to be scrap items which can be sold in the Company

**Comment by Paradox75831004** [comment]
> Упс от@Malcolm-Q, это капли с монстров, когда включено улучшение «Охотник», например: Охотник 1-го уровня позволяет накопительному жуку и блохе-ловушке сбрасывать образцы. Охотник 2-го уровня позволяет Бункерному Пауку и Бабуину-ястребу сбрасывать образцы. Охотник 3-го уровня позволяет Бракену, Тамперу и Безглазой собаке сбрасывать образцы.
> 
> Все эти образцы представляют собой металлолом, который можно продать в Компании.
> 
> Другими словами, они не должны были быть в магазине. :D

Oh, I didn’t know that - our “Lethal Loners” assembly is simple. Next time I will notify you about this - thanks for telling me!
