### ISSUE TITLE
Issue in tracking of enabled/disabled upgrades

### ISSUE THREAD

**Issue by gdp740** [Malcolm-Q/LC-LateGameUpgrades#11]
# Issue:
We have Better Scanner and Night Vision unlocked.
We decided to do some configs for Night Vis and disable Portable TP.
After loading back in, our upgrades became an entire different set.

Before: Better Scanner + Night Vision
After: Back Muscle + Discombobulator

# Expected: 
Loading a game should be able to keep track which config is enabled or not.
I didn't read the codebase but I'm thinking the possible cause for this is some sort of array-related behavior

# Replication Steps:
1. Get Better Scanner and Night Vision
2. Save at orbit and exit
3. Set Portable TP to false
4. load the save
5. type `unlocks` in terminal, displays Back Muscle and Discombobulator
6. attempt use Night Vision, not accessible.
7. exit
8. reconfig Portable TP to enabled
9. load the save
10. type `unlocks` in terminal, we have Better Scanner and Night Vision again

Note: We've made sure that its indeed the same save we're playing.

**Comment by gdp740** [comment]
I've read the last part of readme.md so I'll add some more info.

I am the host and I was the one who initiated both of the upgrades purchase.

**Comment by Malcolm-Q** [comment]
Hi, 
This is a great bug report, thank you. I think you're correct that disabling them and removing them from the list of registered network prefabs is causing the ships item saving system to now be holding onto irrelevant indices.

I am about to put up a nightly build for v1.5.0 on here and it should go live on thunderstore tomorrow. I'll make sure to test this case to ensure it is fixed and close this issue.

Thanks again.
