### ISSUE TITLE
Malware Broadcaster Duration Doesn't Work

### ISSUE THREAD

**Issue by DanteAyagawe** [Malcolm-Q/LC-LateGameUpgrades#113]
I tried testing this version of the malware broadcaster, and it appears to not work, apply over 100s and the turret or mines are not disabled for that set amount, and only applies to the default duration

**Comment by DanteAyagawe** [comment]
Is there a mod incompatibility, because the mod I tried to bug test are as follow in this picture
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72873254/303f282f-3c8d-4166-b0f5-585f3eb5c0c7)

**Comment by WhiteSpike** [comment]
Fixed the [issue](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/117). I could only see it happening with turrets, landmines were just not doing what they were told to and wasn't sure if it was a vanilla issue.
In the next patch, please check if it fixed this issue.

**Comment by DanteAyagawe** [comment]
I'll try testing it again

**Comment by DanteAyagawe** [comment]
Yep tried it again, same issue, typing it on the console or even the remote terminal, the turret always sleeps exactly on the default duration

**Comment by WhiteSpike** [comment]
That's because the next patch wasn't released. :)

**Comment by DanteAyagawe** [comment]
ahhh, now I get it
my bad

**Comment by Malcolm-Q** [comment]
2.8.6 was uploaded
