### ISSUE TITLE
The sale never changes

### ISSUE THREAD

**Issue by ImpulsiveLad** [Malcolm-Q/LC-LateGameUpgrades#115]
The sale is always 13% off on the 4th item down and 29% off on the 6th item down. Never ever seen it change across 30 quotas and 7 runs

(Unrelated Beekeeper Question) Does the beehive value multiplier on beekeeper stack across players?(add/multiply?) and does it only apply when beekeeper is at whatever the max level is based on your config or is the bonus automatically divided across the levels?

also what is the distances in? Discombobulating has a radius of 40 but like 40 what?

**Comment by ImpulsiveLad** [comment]
I would imagine it could have to do with having less than the standard amount in the ship by configging an few out?

**Comment by Malcolm-Q** [comment]
I haven't experienced this but will test more.

Beekeeper is server wide and on the last level

1 unity unit is 1 meter. Iirc this game is scaled a little larger though so my gut tells me 1 unit is about 0.75 meters. If you want to get a feel for distances buy the walkie gps, make note of where you're standing. Then walk 40 units in one direction. That's 40 units.

**Comment by ImpulsiveLad** [comment]
so if beekeeper adds a 1.1 multiplier, 5 people having it makes it a 1.5 multiplier or is it just 1.1 still?

**Comment by ImpulsiveLad** [comment]
Important note, this was occurring while I had a value of .75 and .50 for the sale chance
