### ISSUE TITLE
LGU sales don't persist when reloading a save

### ISSUE THREAD

**Issue by paul-merkamp** [Malcolm-Q/LC-LateGameUpgrades#116]
I've had this problem a handful of times now, where we plan to buy something on sale next time we reload the save, but then we load the save and nothing is on sale anymore.

It looks like generally, if you start a new save, nothing is on sale. Unsure if that's related.

Mod list:
```
BepInExPack
LCBetterSaves
HookGenPatcher
LethalLib
Lategame_Upgrades
ShipLoot
HDLethalCompany
Skinwalkers
Coroner
More_Suits
MoreItems
ItemQuickSwitch
ShipLobby
QuickRestart
HideModList
WaluigiSuit
MugSuit
LCFartLizards
SuitSaver
FixCentipedeLag
CoilHeadStare
IntroTweaks
CompatibilityChecker
YippeeMod
TooManyEmotes
LC_API
```

**Comment by Malcolm-Q** [comment]
Yeah sale data isn't saved ATM. It's on my list and easy to implement just haven't gotten to it. Only focusing on the mod jam rn truth be told.

Should be in soon though thanks for reminding me.

**Comment by paul-merkamp** [comment]
good luck on the jam!!
