### ISSUE TITLE
[Suggest] Light Footed Merged??

### ISSUE THREAD

**Issue by Niconoko** [Malcolm-Q/LC-LateGameUpgrades#119]
Me don't wanna be too speedy when being stealth, no wonder where the upgrade has gone to.
Could there be setting to separate them like before? Thx in Adv.

**Comment by Malcolm-Q** [comment]
I didn't know anyone really even used light footed so the suggestion to merge it was a welcome one. Through the config you could bring light footed back and remove running shoes / convert running shoes to be one level, not make you faster, and grant light footed.

Not sure light footed will be seeing a return unless we get ideas on how we could further develop it / make it interesting.

**Comment by Niconoko** [comment]
Me think stealth is great, got me out from many situations.
Here's me idea, (5/5) < Detect range compare from ship to selling spot in company.
Lv.1 Light Footed - Enable crouch and stay still to lower enemies line of sight. (4/5)
Lv.2 Light Footed - Enable standing still to lower enemies line of sight, but still fewer than crouching. (4/5). Crouch now (3/5)
Lv.3 Light Footed - Lower line of sight of enemies while walking. (3/5)
Lv.4 Light Footed - Lower line of sight all over, crouching, standing and walking by half (2.5/5)
Only work on enemies with sight detecting based, since the sound based only crouch would work aleady.

**Comment by WhiteSpike** [comment]
So basically, it would be like "faint presence" where the higher the level, the more likely enemies won't notice you, from what I am understanding, in several modes like crouch, standing still and walking (moving but not sprinting).

If I understood this currently, this should be doable by patching EnemyAI's PlayerIsTargetable method and change the range parameter according to the level and "player mode".
