### ISSUE TITLE
No Lightning Strikes

### ISSUE THREAD

**Issue by Boaphlipsy** [Malcolm-Q/LC-LateGameUpgrades#120]
I am playing with LGU and have the lightning rod upgrade disabled. Lightning will no longer strike when traveling to a stormy planet.

**Comment by WhiteSpike** [comment]
I just tested, the lightning strikes are working just fine (both random and scrap targetted).

What are the mods you are using?
Can you provide a LogOutput of when this happened?

**Comment by Boaphlipsy** [comment]
Oh ok. I have am playing with quite a large modpack, I'll do some testing myself and when I find out which mods conflict I'll post it here.
I'll also provide the LogOutput then

**Comment by Boaphlipsy** [comment]
I have now tested it with only LGU but it does actually not generate lightning strikes anymore. I'll provide my config file(renamed to .txt for uploading on Github) and my LogOuptut here:

[com.malco.lethalcompany.moreshipupgrades.cfg](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13798951/com.malco.lethalcompany.moreshipupgrades.cfg.txt)
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13798944/LogOutput.log)

**Comment by WhiteSpike** [comment]
Hmm, it's throwing an error whenever it tries to do patch related with lightning and it's on the first ever instruction related to this method. :\

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MoreShipUpgrades.Patches.StormyWeatherPatcher.CheckIfLightningRodPresent (StormyWeather __instance, UnityEngine.Vector3& strikePosition, System.Boolean useTargetedObject) (at <2f70d474a3734694a2aeba20d554b55f>:IL_0001)
(wrapper dynamic-method) StormyWeather.DMD<StormyWeather::LightningStrike>(StormyWeather,UnityEngine.Vector3,bool)
StormyWeather.LightningStrikeRandom () (at <44743d9474784365a095189c76175301>:IL_00DC)
(wrapper dynamic-method) StormyWeather.DMD<StormyWeather::Update>(StormyWeather)
```

What version are you playing the game on? 45 or 47?

**Comment by Boaphlipsy** [comment]
I am just playing on Version 45. When Testing I just had Lategame Upgrades and its dependencies installed

**Comment by WhiteSpike** [comment]
I just used your config and it brought up the error mentioned. 

So it's probably some bad parsing happened and the method was not expecting that thus errored itself.

**Comment by WhiteSpike** [comment]
[Resolved](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/123) the issue and will be live in the next release of this mod in the Thunderstore.
