### ISSUE TITLE
Add new setting config

### ISSUE THREAD

**Issue by TheLynk** [Malcolm-Q/LC-LateGameUpgrades#122]
I would like to have the possibility that after we have missed the quota we can keep the improvements of the ship and the people

as proposed by the mod: [PersistentPurchases](https://thunderstore.io/c/lethal-company/p/TheBeeTeam/PersistentPurchases/) for ship decoration and ship upgrades

**Comment by WhiteSpike** [comment]
Made a [pull request] for it, the final decision is on Malcom if they want to include it or not.

**Comment by Malcolm-Q** [comment]
Merged - closing
