### ISSUE TITLE
Baboon hawk doesn't drop samples with Hunter upgrade

### ISSUE THREAD

**Issue by Crysoskis** [Malcolm-Q/LC-LateGameUpgrades#126]
As title says, baboon hawk samples don't drop when they should. On top of that, the inventory icon for the bracken sample uses the baboon hawk's image

**Comment by WhiteSpike** [comment]
[Resolved the issue of Baboon sample not spawning](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/128) and will be live in the next release of this mod in Thunderstore.

I will look at the icon issue, I guess.

**Comment by Malcolm-Q** [comment]
2.8.6 has been uploaded.
