### ISSUE TITLE
[FEATURE] Add the ability to buy a Day of work

### ISSUE THREAD

**Issue by LostZ0mbie** [Malcolm-Q/LC-LateGameUpgrades#127]
Either you'll have to purchase a day to add to your current deadline or you can only add 1 to your deadline if the deadline is below 3 days. Don't know how possible it is to do, but I feel it fits the theme of endgame content and make it somewhat expensive, so the player feels like they have a last chance my suggestion is 1500-1000 credits.

**Comment by Malcolm-Q** [comment]
I like this idea, thanks

**Comment by Malcolm-Q** [comment]
This will be included in next update.
