### ISSUE TITLE
Upgrades Reset when leaving planet

### ISSUE THREAD

**Issue by Kayden21** [Malcolm-Q/LC-LateGameUpgrades#137]
Hey my group noticed an issue where we will buy an upgrade for example the running shoes and it will work as it should and its noticeably faster because its fully upgraded but then when we leave the planet it resets to what might just be base game speed. We have no idea why it does this so it kinda just takes our credits and then the mod does not even work. Would love to know a fix or the cause if you have seen this before.

**Comment by WhiteSpike** [comment]
- What are the mods you were using when this issue appeared?
- Can you provide the ``LogOutput.log`` file present in the ``BepInEx`` folder?

As far as I am aware, Strange Objects resets the player's movement speed to default whenever the ship leaves the moon.

**Comment by Kayden21** [comment]
Yeah we just tested it and strange objects was the issue. Thanks for the help
