### ISSUE TITLE
MoreCompany & Peeper

### ISSUE THREAD

**Issue by zanncdwbl** [Malcolm-Q/LC-LateGameUpgrades#139]
I did a bit of testing, and taking a quick glance at both source codes - both mods affect the Spring/Coil Heads, which in turn breaks the peeper item.
Would there be any chance of a hotfix?

**Comment by Malcolm-Q** [comment]
It's a problem with their code not ours. All of their patches are bool patches that always return false.

What that means is their code and their code only will run. 

It could be solved by instead using a transpiler. It's on my to-do list to make a pr on their repo.

**Comment by zanncdwbl** [comment]
Thanks for letting me know!
