### ISSUE TITLE
[SUGGEST] Loose Upgrade on Death

### ISSUE THREAD

**Issue by Miradae** [Malcolm-Q/LC-LateGameUpgrades#143]
It would be amazing to have a config option that makes it possible that employees loose their upgrades (e.g. ALL, NONE, just one level) on death.

**Comment by WhiteSpike** [comment]
This would only make sense with individual upgrades, no?

If, for example, running shoes is shared and is maxed for everyone. One dies, they would have a lower level of running shoes but everyone remains the same, forcing them to buy the last upgrade (which also affects other's levels as of now)

Unless you want that, in the case of a shared upgrade, the upgrade is only lost if everyone dies?

**Comment by Miradae** [comment]
yeah  i would say for individual upgrades when the person dies, for shared when everyone dies

**Comment by Malcolm-Q** [comment]
moved to discussions https://github.com/Malcolm-Q/LC-LateGameUpgrades/discussions/222

The code is pretty much already there to add this btw I think it's just a matter of time before it's added.
