### ISSUE TITLE
Repetition is the mother of teaching

### ISSUE THREAD

**Issue by Paradox75831004** [Malcolm-Q/LC-LateGameUpgrades#144]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72872478/c86b3ce4-fae9-4e24-85f3-dc1ce1daf73e)
Repeated information in the terminal

**Comment by WhiteSpike** [comment]
[Fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/145) in the next release.
