### ISSUE TITLE
[SUGGESTION] Permanent Lategame Upgrades that don't reset upon failing quota?

### ISSUE THREAD

**Issue by Mimikyew** [Malcolm-Q/LC-LateGameUpgrades#157]
Is there any chance you are willing to make the Lategame upgrades permanent? This would make it feel more like a rougelike where you are constantly getting stronger with every purchase and allow games to last longer. Especially with the amount of modded maps and such, it would be nice to keep the upgrades and feel there was some sort of accomplishment.

**Comment by Malcolm-Q** [comment]
This already exists. Check the config before suggesting something be added to it.

Also that's not how roguelikes work lol.

**Comment by ArsenicBismuth** [comment]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/19264532/46b3da92-fdd1-4059-9ed0-df451507b4b0)
Oh yeah LGU has that too, under `Misc` section.

**Comment by Mimikyew** [comment]
Thank you for the information. I’m sorry for not checking the config first. I’m not very knowledgeable on all that but I appreciate you pointing it out so I know where to look.Also I always get rougelikes and rougelites mixed up. But yeah rougelites like gunfire reborn, roboquest etc have that overarching skill tree that you purchase upgrades into that you keep every run. Sent from my iPhoneOn Jan 12, 2024, at 12:29 PM, Malcolm ***@***.***> wrote:﻿
This already exists. Check the config before suggesting something be added to it.
Also that's not how roguelikes work lol.

**Comment by Mimikyew** [comment]
﻿Thank you for the information. I appreciate you pointing out where it is so I can go and add it. And giving info on the other kid that offers permanent upgrades.Sent from my iPhoneOn Jan 12, 2024, at 1:49 PM, Arsenic Bismuth ***@***.***> wrote:﻿
image.png (view on web)
Oh yeah LGU has that too, under Misc section.
