### ISSUE TITLE
Too many first aid kits for a contract

### ISSUE THREAD

**Issue by Paradox75831004** [Malcolm-Q/LC-LateGameUpgrades#162]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72872478/cf7cc57c-416d-47bf-8b63-add136ebf97b)
There are too many first aid kits, can you somehow reduce them for the use contract? So that there is one with 3 charges for three survivors, for example. But nito in the store is expensive, you can farm it hard

**Comment by Paradox75831004** [comment]
500 credits for each survivor? I think it's a bit much :D
In the complex I found 2-3 I think

**Comment by Paradox75831004** [comment]
The update is just great!

**Comment by Malcolm-Q** [comment]
moved to discussion https://github.com/Malcolm-Q/LC-LateGameUpgrades/discussions/221
