### ISSUE TITLE
Disabling Helmet or Night Vision in config breaks LGU Store

### ISSUE THREAD

**Issue by Louka3000** [Malcolm-Q/LC-LateGameUpgrades#167]
Enable the helmet for purchase = false

or

Enable Night Vision Upgrade = false

will break the lgu store
possibly others are well

**Comment by WhiteSpike** [comment]
Yes, currently any item that can be bought from the store will break the store. We are looking into this.

**Comment by WhiteSpike** [comment]
Fixed in 3.0.3 release
