### ISSUE TITLE
[Suggestion] Add a shortform command for the store for us lazy typers

### ISSUE THREAD

**Issue by Tahvohck** [Malcolm-Q/LC-LateGameUpgrades#17]
Having a separate store is great for the mod, but typing out "lategame" is a pain. Can you add an additional keyword such as "LGU" for those of us with lazy fingers?

**Comment by Malcolm-Q** [comment]
V2.1.0 has shortform commands and was just put on thunderstore

lgu for lategame store
Atk for initattack
Cd for cooldown
