### ISSUE TITLE
Extend Deadline doesn't work

### ISSUE THREAD

**Issue by 1670081661** [Malcolm-Q/LC-LateGameUpgrades#174]
At first, I found that Extend Deadline was removed from "lgu". I can't find it.
Then I tried to type "Extend deadline 2". I found that although my money was cost, but there was no any information, and the deadline still didn't change.
To replicate it: Just play the game and try to use "Extend deadline 2". 
Mod Version - 3.0.2
This used to be usable in Ver2.8.8

**Comment by WhiteSpike** [comment]
Made a [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/187) which should resolve this issue. It will be live in the next release.
