### ISSUE TITLE
using portable teleporter breaks players inventory

### ISSUE THREAD

**Issue by James-Molzer** [Malcolm-Q/LC-LateGameUpgrades#175]
when using the portable teleporters both regular and advance once you are back at the ship all items in your inventory are there but not usable as in the game seems to think the inventory slots are empty, the items icon are overwritten when you pick up something new, when reloading the game all items then reappear when you logged out of both the old items from when you were teleported and the new items you picked up that overwritten your inventory

**Comment by WhiteSpike** [comment]
If you can provide logs of when this happened and the configuration of this mod, I would appreciate it.

**Comment by James-Molzer** [comment]
i did some more testing and this seems to be a incompatibility bug. with just Late-Game installed everything works fine i then install another core mod to from our pack which is Advance Company after do that the bug i mention then occurs, im guessing with the updates to both mods broke something with them working together like they used to. I'll add the log from that test.

[log error teleporter bug.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13941683/log.error.teleporter.bug.txt)

**Comment by Malcolm-Q** [comment]
I believe the creator implemented a fix for this I am unsure if it is live or not though.
