### ISSUE TITLE
Bomb Defusal Contract - Bomb Nerver Stops Ticking

### ISSUE THREAD

**Issue by AimlessRex** [Malcolm-Q/LC-LateGameUpgrades#176]
The Bomb you receive from the Bomb Defusal Contract Loudly ticks forever even after defusal

**Comment by WhiteSpike** [comment]
Made a [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/184) which seemed to fix this issue. Will be live in next release.

**Comment by Malcolm-Q** [comment]
3.0.4
