### ISSUE TITLE
Night Vision Should Use Normal Battery

### ISSUE THREAD

**Issue by Haravikk** [Malcolm-Q/LC-LateGameUpgrades#177]
I like the addition of night vision but it seems odd to me that it has its own self-regenerating battery.

I think it would make more sense to have night vision be more like an alternative to flashlights, with two separate items; regular night-vision goggles, and a pro version that gives better vision and has a longer lasting battery. Both should be charged back at the ship, same as flashlights.

Basically the advantage of night vision over a regular flashlight should be better overall visibility, and perhaps the ability to turn it on/off while another item is selected. The pro version should have even better visibility and have a much longer lasting battery.

It might also be cool to see an even more expensive night vision helmet, combining the benefits of a helmet, regular night vision and a basic walkie talkie all rolled into one item slot.

**Comment by nephatrine** [comment]
How would you remove the goggles to charge them if you had to charge them like normal items?

**Comment by Haravikk** [comment]
> How would you remove the goggles to charge them if you had to charge them like normal items?

I figure they should be a held item like flashlights are, but with better visibility and no alerting enemies (though I'm not sure if enemies actually see flashlights or not, are Forest Keepers more likely to spot you if you have one switched on?).

After all, the jetpack is a held item despite being worn on your back more like an oxygen tank upgrade. There are other mods for increasing item slots if you need them, or allowing items to be attached to the suit; not sure how easy it would be to make  night vision goggles compatible though.

**Comment by ImpulsiveLad** [comment]
imo I would like the night vision more like that, an item in the store that is charged, like a pro pro flashlight
It could be put on like a helmet and a keybind and bring it back to the hand

**Comment by Malcolm-Q** [comment]
moved to discussions https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/177
