### ISSUE TITLE
Exorcism Contract - Demonic Tome Worth Nothing

### ISSUE THREAD

**Issue by AimlessRex** [Malcolm-Q/LC-LateGameUpgrades#178]
The book you receive after completing an exorcism is worth no scrap and is not scannable. Selling it at the company building gives nothing.
![Screenshot (588)](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82302586/9711d200-cf88-429f-b616-3a47c5369afb)

**Comment by WhiteSpike** [comment]
A possible fix has been [committed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/commit/490d7187bba4a3597ea70d7393673a4e495f7ff5) and will be live in next release.

**Comment by Malcolm-Q** [comment]
3.0.4
