### ISSUE TITLE
Bomb Defusal Contract - Weird Bomb Spawn

### ISSUE THREAD

**Issue by AimlessRex** [Malcolm-Q/LC-LateGameUpgrades#182]
Bomb spawned inside of a wall making it impossible to see its number.

![Screenshot (595)](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82302586/ad76950d-b768-4849-8041-7c4282189195)

**Comment by WhiteSpike** [comment]
Yeah, scrap generation algorithm picks the most weird spots to spawn. We will have to find a workaround of either pushing it inside or have something pop up when looking at it. We will look at it when the time's possible.

**Comment by ImpulsiveLad** [comment]
![Screenshot 2024-01-17 005804](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/92990441/6615ef57-ad39-4ef0-bcf5-4269c2499240)

*cries in going to blow up*

**Comment by Malcolm-Q** [comment]
3.1.0 now has a new system for placing contract objects.
