### ISSUE TITLE
Wheelbarrow applying weight changes multiple times because of lack of check if the player is the local player controller

### ISSUE THREAD

**Issue by WhiteSpike** [Malcolm-Q/LC-LateGameUpgrades#190]
If there isn't a check, it will do this up to x people in the lobby times the calculations.

**Comment by WhiteSpike** [comment]
Made a [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/191) which seem to fix this. Will be live in next release

**Comment by batman202012** [comment]
Also had this bug with the shopping cart as well

**Comment by Malcolm-Q** [comment]
3.0.4
