### ISSUE TITLE
Contract fuckery

### ISSUE THREAD

**Issue by ImpulsiveLad** [Malcolm-Q/LC-LateGameUpgrades#205]
I haven't tested extensively but have noticed that:
1. Contracts don't get removed on failure

2. Contracts don't get removed on success

3. During the loop of 1 and 2 you can sometimes buy another contract but it will be the same moon, same contract. (you still lose money buying it.)

4. Not sure on this one due to the previous errors but all my contracts were on vow. Only tested in 2 saves so take it with a grain of salt
[Uploading LogOutput.log…]()

**Comment by WhiteSpike** [comment]
The hyperlink points to the issue itself

**Comment by ImpulsiveLad** [comment]
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13965354/LogOutput.log)

**Comment by nephatrine** [comment]
I noticed that both times my contract got seemingly stuck (didn't ever go away on completion) it happened to be on Experimentation. Might just be a coincidence though. It'd be nice to have a command that abandons the current contract so that we can take new ones if one gets stuck like that.
