### ISSUE TITLE
Everything about this mod can be changed via the config ?

### ISSUE THREAD

**Issue by broilerosu** [Malcolm-Q/LC-LateGameUpgrades#21]
but when i look for a config its just lategame_upgrades\installing.txt and the License ? installed with r2 modman

the mod works i just cant config anything

**Comment by Malcolm-Q** [comment]
Config files are generated in Bepinex/config/

This one starts with com.malco

**Comment by Malcolm-Q** [comment]
If you're using r2modman you can edit the config with the manager

**Comment by broilerosu** [comment]
oh okay i found it thanks
