### ISSUE TITLE
[Suggestion] Contract reward multiples over quotas 

### ISSUE THREAD

**Issue by ImpulsiveLad** [Malcolm-Q/LC-LateGameUpgrades#214]
The contract reward should increased on quotas.

The cost of doing it and wagt you get out for completing it can be chosen but regardless of how high it is, the later the quota you get to, the worse of an idea it would be to go for it, if you have a 1500 quota and your contract is on one of the first 3 planets it’s financially better to just go to titan or another paid planet .

**Comment by Malcolm-Q** [comment]
More configurability for contract rewards and behaviour will probably be added soon. I think there's a few systems for how it could adapt over time that would be easy to implement and switch between.

**Comment by Malcolm-Q** [comment]
Moved to https://github.com/Malcolm-Q/LC-LateGameUpgrades/discussions/218
