### ISSUE TITLE
Discombobulater "initattack" unusable with Contracts

### ISSUE THREAD

**Issue by AllenHill3** [Malcolm-Q/LC-LateGameUpgrades#216]
Anytime myself or my crew tries to type in "initattack" into the terminal to use the discombobulator it just tries to buy a contract instead. We did not have this issue previously before the contracts were added and this is the same save file we were using before contracts were added.

**Comment by nephatrine** [comment]
You can still use it with `atk`, but yeah. It'd be nice to have it fixed.
