### ISSUE TITLE
Running shoes

### ISSUE THREAD

**Issue by rozakk12** [Malcolm-Q/LC-LateGameUpgrades#229]
The running shoes upgrade does not apply and it goes back to the default speed without the upgrade after landing the ship. But the upgrade before landing the ship  is completely fine.

**Comment by Malcolm-Q** [comment]
Do you have strange objects installed?
Uploaded your logoutput.log please.

**Comment by rozakk12** [comment]
> Do you have strange objects installed? Uploaded your logoutput.log please.

uh sorry how do i do that? im not that familiar in reporting bugs

**Comment by Malcolm-Q** [comment]
mb should be in the root of your bepinex folder.

**Comment by rozakk12** [comment]
[Uploading LogOutput.log…]()

**Comment by rozakk12** [comment]
Like that?

**Comment by Malcolm-Q** [comment]
No that just linked to this issue for me unfortunately.

**Comment by rozakk12** [comment]
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13983365/LogOutput.log)

**Comment by rozakk12** [comment]
that should do it

**Comment by rozakk12** [comment]
the other upgrades seem to work fine, just the running shoes fyi

**Comment by rozakk12** [comment]
I may have found the fix, the mod InsanityRemastered was causing all the problems, I think. I uninstalled it, and the running shoes worked again.

**Comment by HAIYANGTONGXUE** [comment]
> Do you have strange objects installed? Uploaded your logoutput.log please.

Does the strangeobject mod conflict with upgrade？
