### ISSUE TITLE
`scan` command causing an exception and displaying `[scanForItems]` instead of value

### ISSUE THREAD

**Issue by Mipsters** [Malcolm-Q/LC-LateGameUpgrades#233]
related issue in [LethalLib](https://github.com/EvaisaDev/LethalLib/issues/51)

happens for a few client in the same server with this modpack

```
018d2384-b7dd-b8c5-1d3b-d80c7dab3b3f
```

log: [LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13996029/LogOutput.log)

seems like they got an item with `itemProperties.minValue` higher then `itemProperties.maxValue` in `Terminal.cs:TextPostProcess`

I think this may have happened because we had a shopping cart on board of the ship, but I'm not certain

**Comment by Mipsters** [comment]
seems like most of the `Samples` have the min and max values reversed
e.g.
[Thumper](https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/6c6ba62c4a5d5f3ac246d4ed18d5d310bf338b5c/UnityFiles/ShipUpgrades/Samples/ThumperSample.asset#L31)
[Bracken](https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/6c6ba62c4a5d5f3ac246d4ed18d5d310bf338b5c/UnityFiles/ShipUpgrades/Samples/BrackenSample.asset#L31)

**Comment by WhiteSpike** [comment]
Minimum and maximum values are set through code which picks up the configurated values from user input, both for samples and shopping cart.

Only issue I know that causes [scanForItems] is nutcracker spawning due to its shotgun

**Comment by WhiteSpike** [comment]
Closing for lack of response.
