### ISSUE TITLE
Shop not showing up when lgu command is used

### ISSUE THREAD

**Issue by iondomenti** [Malcolm-Q/LC-LateGameUpgrades#237]
When I type lgu the terminal is empy and doesn't show any items. Intern, Lategame some other commands work properly. The only problem is the shop not showing up and when typing the name of items from the mod like "beekeeper" it gives the "No action supplied with the word" error
![Screenshot (84)](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/96654923/7669d57b-96dc-4272-b4cb-5c7931a2b877)
Here is my modpack: (https://drive.google.com/drive/folders/1IyIrItsUABUk3EAj9Kdm3Y54H-OOp4eK?usp=sharing)

**Comment by iondomenti** [comment]
This is the console log: https://pastebin.com/3uTi6Jy5

**Comment by Malcolm-Q** [comment]
Looks like you didn't install lethallib correctly and are missing hookgenpatcher.

When lethallib loads it says:

'Could not load file or assembly 'MMHOOK_Assembly-CSharp, '

And fails

Consequently when LGU loads the store and everything the lethallib operation it does raises an exception and returns early.
