### ISSUE TITLE
Some upgrades not working since V45

### ISSUE THREAD

**Issue by squeakerdev** [Malcolm-Q/LC-LateGameUpgrades#24]
Some upgrades are recognised as being upgraded, but have no effect. Haven't tried all of the upgrades, but will list the ones that I know don't work for me below.

**Not working as of V45** (worked perfectly with V40, with no other mods added/removed)**:**
1. Bigger Lungs
2. Running Shoes
3. Back Muscles

**Working:**
1. Better Scanner

**Active mods:**
- BepInExPack
- Custom_Boombox_Music
- ShipLoot
- HDLethalCompany
- LethalCompanyDRP
- LethalFashion
- SpectateEnemies
- 24HourClock
- LateCompany
- LC_API
- MoreItems
- SkipToMultiplayerMenu
- More_Emotes
- More_Suits
- RandomSuits
- HookGenPatcher
- LethalLib
- Lategame_Upgrades
- HelmetCameras
- ObjectVolumeController
- Custom_Boombox_Fix
- TooManySuits
- FrostySuits
- FrostySuits2
- FrostySuits3

Thanks!

**Comment by DillyTheDillster** [comment]
I did some testing, and it seems its More_Emotes. We'll look into it shortly, my assumption is it might have to do with their recent update allowing movement with the griddy emote.
