### ISSUE TITLE
Wheelbarrow PlayerControllerB causes crash loop upon starting a lobby

### ISSUE THREAD

**Issue by Cephelo** [Malcolm-Q/LC-LateGameUpgrades#242]
Sometimes when I host a lobby, I get this crash repeating in the log over and over again, printing infinitely:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MoreShipUpgrades.UpgradeComponents.Items.Wheelbarrow.WheelbarrowScript.CheckIfPlayerCarryingWheelbarrowLookSensitivity (System.Single defaultValue) (at <88de82b71d154461a933043128e6bac8>:IL_000C)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::PlayerLookInput>(GameNetcodeStuff.PlayerControllerB)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)
```
This still frame is all I see onscreen, yet I can still hear the ship audio: 
<img width="1252" alt="image" src="https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/79186646/8c045d07-3b55-4b28-9cad-5046b0091246">
I cannot move around at all.
Disabling the Wheelbarrow in the config avoids this crash the first time a lobby is loaded, but not the second time.  This is fixed by restarting your game, but the second time you make a lobby following that start, it will occur again.
Full log file: 
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14071922/LogOutput.log)
r2modman code: 018d4a6f-f08d-0b8f-a0af-983610016332

**Comment by WhiteSpike** [comment]
While I did fix the errors appearing when the wheelbarrows are not enabled in the config (thus it's not necessary to do comparisions to waste logic time), the getting stuck in the void still persisted so I don't believe this is the core issue that is causing this behaviour.

**Comment by Cephelo** [comment]
After further testing, I can confirm that it's not LateGameUpgrades responsible for this; the Wheelbarrow stack trace just showed up alongside the main issue.  Thanks for your time!
