### ISSUE TITLE
"TotalWeight" config option for Wheelbarrow/ShoppingCart does nothing

### ISSUE THREAD

**Issue by MusicalRess** [Malcolm-Q/LC-LateGameUpgrades#245]
I found this out while messing with a bigger modpack and wanted to test it without any other mods (Other than the Minimap mod), and sure enough it doesn't do anything. I had the default config other than setting the shopping cart to use "TotalWeight" instead of ItemCount and to make the cart spawn 100% of the time, and I managed to fit way over 100 lb inside of it. (In the larger modpack it was set to only hold 30 lb, but it was holding way over 200 lb. I thought it might've been the back muscles effecting the weight but we didn't have that upgrade at the time). 

I had only tested the shopping cart specifically in this profile but it was issue enough to mention it.

To Reproduce, set the shopping cart to use TotalWeight instead of ItemCount. (A dropdown list for this would be great, but that's not as important as it functioning)

(I also imagine it's been noticed already, but the shopping cart always has a value of 0. Just in case it hasn't.)

[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14078387/LogOutput.log)

_My personal intended use was to make the shopping cart hold very little weight, so it could hold A Lot of lighter/weightless items. So I like to think you can place weightless items into a 'full' container if it's set to use weight, makes it less annoying._

**Comment by WhiteSpike** [comment]
Comparisons were using the old system where we would change the item properties of the item whenever the weight had to change. However, this would lead to this item not being saved and being lost on reload. I will change the comparisions to reflect the new weight system.
