### ISSUE TITLE
Idea: Some kind of item that we can use to disable coil-head permanently.

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#25]
This idea suddenly hit me like a truck.

Coil-heads in the game are completely indestructible despite its log stating otherwise, forcing players to assign a member to constantly stare at them in later moons. (which there’re nearly always multiple spawning)

So what if we can buy some kind of device that can be used to disable coil-head? Instead of disable it for only a few seconds like the stun grenades, the device can disable a coil-head permanently.

Now, I understand some people would consider it to be too op to “remove” a monster from the map with some money, so here’s my approach:

The device is very expensive and reusable. It can be placed on/around a coil-head to disable the thing for as long as the device remains there. When players wish to leave the moon, they would have an incentive to go back and grab the device because of its high price, allowing the coil-head to roam again. (Still allowing them to hunt players down depending on your own management)

Thank you!

Bonus point: Coil-heads are presumed to be biological weapons of war, meaning they’re artificially created. A device capable of disabling them is completely possible to exist.

**Comment by Malcolm-Q** [comment]
That's a great idea, I'll look into this. If you have more lmk. I'm going to be doing some more additions next. The one I know I'm going to add for sure is the defibrillator, a one time use item that revives the hit player.

I'm going to explore that idea you suggested probably tomorrow and see what it's like to implement. I really like the idea of leaving the coil head staring task in early game.

**Comment by Malcolm-Q** [comment]
Implemented and live

**Comment by FireGeneral** [comment]
Thank you for your hard work!
