### ISSUE TITLE
Items not showing such as shopping cart and plushies, not sure why.

### ISSUE THREAD

**Issue by Wapplee** [Malcolm-Q/LC-LateGameUpgrades#252]
There is probably many other, if not the entire mod because my teammates cannot see a lot of things, and this just shows what.
This is my POV:
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/83174774/60270352-38e8-435b-8475-0f133d179f48)
And then my friend's view of me. (i was holding it here)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/83174774/af6930c3-6036-46fb-b4e7-01ae9ae4676f)

**Comment by Wapplee** [comment]
the first picture is after i dropped it, my bad.

**Comment by WhiteSpike** [comment]
If you can provide both yours and your friend's logs, I can try find out why it's not loading for both.
Maybe I will require both configurations too to see if anything's not being synced right.

**Comment by Wapplee** [comment]
> If you can provide both yours and your friend's logs, I can try find out why it's not loading for both. Maybe I will require both configurations too to see if anything's not being synced right.

I don't really have the log anymore because I played the day after so, I'm sorry about that.
