### ISSUE TITLE
Upgrades do not work most of the time.

### ISSUE THREAD

**Issue by Mitrut** [Malcolm-Q/LC-LateGameUpgrades#26]
When I play with my friend, my upgrades do not work. Well, not all of them, but better scanner does not work, Iron Lungs and probably, not sure, the one that makes your footsteps silent. 
Is there a fix, maybe I need to change something?

**Comment by fakecontent** [comment]
Thank god i found a guy that has the exact same problem as me

**Comment by Malcolm-Q** [comment]
All upgrades work. If some upgrades don't work you have found an incompatibility.
