### ISSUE TITLE
LG upgrades are not consistent with the save files and can allow (un)intentional cheating.

### ISSUE THREAD

**Issue by Kajot-dev** [Malcolm-Q/LC-LateGameUpgrades#261]
Observed on v3.1.0

Sometimes LGU is inconsistent with in-game save files and reloading the save, will not load lgu setting properly

**How to reproduce:**
- The game must already be started (meaning you went to and back from at least one moon)
- Have enough money to buy Bigger Lungs
- Buy bigger lungs while on ship, in space
- Land on the moon
- Exit the game
- Reenter the game on the same save file
- You are at the orbit, you have the money from before the purchase
- **Expected result:** Since we rolled back to the point before purchase Bigger Lungs should be inactive
- **Observed results:** Bigger lungs are already bought

[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14129230/LogOutput.log)
[ModList.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14129254/ModList.txt)

**Comment by WhiteSpike** [comment]
[Fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/263) and will be live in next release.
