### ISSUE TITLE
issues with lethalexpansioncore using mods

### ISSUE THREAD

**Issue by sangca2002** [Malcolm-Q/LC-LateGameUpgrades#269]
when i try to use scrap mods that use lethalexpansioncore as a dependency with this mod, player's death gets inconsistent. people except the host don't sync when they are dead, and it results in dead people talking with alive people or dead people thinking each other is still alive. the voice chat system gets all weird. not only the voice chat is the problem, because it seems to alive people as the dead person is standing still and doing nothing. de-sync between clients except the host. i was using the mod ImmersiveScraps when i found this issue, and i fixed the issue simply by disabling it and lethalexpansioncore. I had similar issues when i had helmet_camers

**Comment by WhiteSpike** [comment]
If you can provide logs of when this happens, I would appreciate it.

**Comment by sangca2002** [comment]
I might test it out if I have time, I'll try
