### ISSUE TITLE
Global setting of individual Upgrades

### ISSUE THREAD

**Issue by CmmmmmmLau** [Malcolm-Q/LC-LateGameUpgrades#27]
I think it will be helpful if could have a global setting for individual upgrades. If set to true then it will overwrite all the `Individual Purchase` to `false` instead of setting each items one by one.
Also when I playing with friends, we couldn't able to share the upgrade even the host set all the `Individual Purchase` to `false`, I think it might be a bug? A global setting might help to avoid it.
Mod list:
- More Company
- Helmet Cameras
- Lategame Upgrades
- Always Hear Active Walkies
- Skin Walkers
- More Emotes
- Late Company
- Custom Boombox Music
- Mote Items
- Lethal Things
- Lethal Fashion
- some dependenices

**Comment by Malcolm-Q** [comment]
All clients must have the same config.

Global setting will be implemented next update.

**Comment by CmmmmmmLau** [comment]
> All clients must have the same config.
> 
> Global setting will be implemented next update.

thx, that make sense now. But also it is possible to sync the config from host automatic?

**Comment by Malcolm-Q** [comment]
Not at the moment but it is also in the works.

**Comment by Malcolm-Q** [comment]
If you use r2modman or probably another mod manager you can share a code and it will copy your config. You can also just send your friends the config for the time being. Config syncing should be in soon.
