### ISSUE TITLE
Have an In-Game Config

### ISSUE THREAD

**Issue by MacStevins** [Malcolm-Q/LC-LateGameUpgrades#287]
Its annoying that you have to restart the game when changing your configuration than having it in game

**Comment by WhiteSpike** [comment]
Made a [PR](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/289) for this. We won't make a UI for this as there's already many mods that do this ([LethalConfig](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/) as an example) and we won't fix any issues that arise from changing configurations while in-game.

**Comment by MacStevins** [comment]
I was hoping that some of the configurations like keybinds would be in-game
