### ISSUE TITLE
Individual purchase is an option for EACH upgrade?

### ISSUE THREAD

**Issue by TwoPointInfinity** [Malcolm-Q/LC-LateGameUpgrades#29]
Can you make individual upgrades a global setting? 
Nobody who wants this setting set to false will want it done to only some settings. 
For example, me and my crew are disabling it but we have to go to every upgrade (annoying).

**Comment by TwoPointInfinity** [comment]
the problem with this option is having a seperate money pool.
if my teamate buys an upgrade, they will have different money than me, but if i buy walkies the money is taken from both of us. They could go down to 0 and i could still buy things, its confusing and the upgrades have different values.

**Comment by Malcolm-Q** [comment]
Yes that is ready to go and will be in the next update.

Your second comment is a product of a bug / compatibility issue. When these desync issues occur 99% of the time it's more company / bigger lobby breaking the netcode or another incompatibility. Note that you can play this mod with bigger lobby or more company but in general with those two mods they're very accident prone and you have to be careful that your lobby got constructed correctly.

The idea with individual upgrades is you are investing in your team and you can each specialize and gain roles.
