### ISSUE TITLE
Floppy disk can't be picked up as PC takes priority

### ISSUE THREAD

**Issue by McGodMan** [Malcolm-Q/LC-LateGameUpgrades#293]
When doing a Data Extraction contract me and my friends finished it and couldn't pick up the floppy disk, it could still be scanned. More specifically whatever angle we tried to pick it up from the game would try and interact with the PC instead.

The PC was on Experimentation next to a vent but fully exposed (not in a wall).

I'd like to upload the log but it is 73 MB in size and GitHub only supports up to 25 MB, instead here's a [google drive link](https://drive.google.com/file/d/1RIgD8woW4wZ6TDNunjwj_Dod5ygbzFEz/view?usp=sharing).

**Comment by WhiteSpike** [comment]
It should be [resolved](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/292) in next release.
