### ISSUE TITLE
Player upgrades not syncing with host when rejoining save file.

### ISSUE THREAD

**Issue by Vampireking721** [Malcolm-Q/LC-LateGameUpgrades#296]
I have noticed that when loading a previous save file, clients that join do not have any upgrades. The host still has all bought upgrades, but using load lgu does not sync clients. Shared upgrades is turned on in the config file. Buying additional tiers of upgrades acts as the first tier for clients, but the next tier for the host. If a player gets disconnected then rejoins, their upgrades will no longer be active.
[Modlist.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14234101/Modlist.txt)

**Comment by WhiteSpike** [comment]
I need the logs from both host and client performing load LGU command. Mod list on its own that doesn't provide much use.

**Comment by Vampireking721** [comment]
My bad, I figured it out. It was user error. I didn't realize that the client needed to use the load LGU command. I thought that if the host used the command, it would force sync the clients. Thank you for your time!
