### ISSUE TITLE
upgrades still apply after ejection

### ISSUE THREAD

**Issue by sangca2002** [Malcolm-Q/LC-LateGameUpgrades#299]
when ejected using the terminal eject command, only the upgrades' levels get reset. the upgrades' effect persists as if they are upgraded after the ejection, and is only fixed after i save and load the game. i have noticed this in stimpack, whereas the upgrade is not unlocked but my health is still at 140.

**Comment by WhiteSpike** [comment]
I did not manage to reproduce this issue. I would be very appreciated if you could provide the LogOutput.log file of when this happened as:
- When I purchase Stimpack to max, I see my health at 180. (default configs and through Elad's HUD)
- After typing "eject" and confirming, I immediately see my health reset back to 100.
