### ISSUE TITLE
rename the config

### ISSUE THREAD

**Issue by TwoPointInfinity** [Malcolm-Q/LC-LateGameUpgrades#30]
the config for player upgrades says more ship upgrades instead of late game upgrades. Hard to find, i thought it was a different mod.

**Comment by Malcolm-Q** [comment]
Hey, that was the original name of the mod and the GUID string. Changing the GUID has complications so I'd rather not. I already mention the exact name and location of the config file everywhere including the splash screen you see when you start/join a game with LGU installed for the first time but if you have ideas as to how I could better communicate it I'm all ears 👍
