### ISSUE TITLE
Reduced performance between mods

### ISSUE THREAD

**Issue by Paradox75831004** [Malcolm-Q/LC-LateGameUpgrades#302]
I've done multiple tests and noticed a feature that this mod sometimes loads the game too much.

018da728-a335-76a2-ff47-5e92e1269e3c

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72872478/d93b0741-6625-46ea-aa18-689790b8438d)

By disabling your mod or Late_Game, everything got better. I checked everything on one side, inside the CullFactor configuration

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72872478/78b1353a-b971-4fa6-a3c1-07ccc6f004db)

I'm just wondering what's causing such a dramatic drop in productivity? These mods add a couple of things, monsters and some teleport mechanics. Maybe the problem is in the code itself, but it's not for me to judge. But help me figure this out :(

BepInEx-BepInExPack-5.4.2100
ShaosilGaming-GeneralImprovements-1.1.9
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.1.1
Zaggy1024-OpenBodyCams-1.1.5
Owen3H-IntroTweaks-1.4.5
Evaisa-H ookGenPatcher-0.0.5
Еваиса -LethalLib-0.14.2
Rolevote-The_Fiend-1.0.4
x753-Mimics-2.4.0
AmesBoys-ImmortalSnail-0.6.1
NomnomAB-RollingGiant-2.5.1
jaspercreations-Scopophobia-1.1.1
Ccode_lang-SirenHead-0.2.1
SolidStone- ShockwaveDroneEnemy-0.2.1
x753-Peepers-0.9.6
Mikusch-SkullEnemy-1.0.4
rileyzzz-Skibidi_Toilet-1.0.2
Rdos-LethalGym-1.0.1
VersusWorks-Dynamo_Flashlight-0.1.2
Jordo-NeedyCats-1.1.1
Taker-CannabisCompan й -1.0.3
AinaVT-YippeeScrap-1.0.7
Pinta-PintoBoy-1.0.4
ModusInteractive-Lethal_Trading_Cards-1.0.3
SillySquad-AmogusScrap-1.1.0
Theronguard-Emergency_Dice-1.1.13
Scintesto-Scavenger_Plushie-1.0.6
Scintesto-Monster_Plushies- 1.0.4
Zaggy1024-PathfindingLagFix-1.2.1
DOkge-InventoryFixPlugin-0.0.1
SillySquad-BetterTotalScrap-1.1.0
Sv_Matt-HideModList-1.0.1
Hamunii-JetpackFallFix-2.0.1
NutNutty-SellTracker-1.2.1
AlexCodesGames-Additional КонтентФреймворк-1.0 .3
AlexCodesGames-AdditionalSuits-2.0.0
BatTeam-LethalFashion-1.0.6
tinyhoot-ShipLoot-1.0.0
EliteMasterEric-Coroner-1.6.0
NotAtomicBomb-TerminalApi-1.5.1
Fivetoofive-DetailedScan-1.2.2
kRYstall9-FastSwitchPlayerViewInRadar-1.3. 2
Ozone-Runtime_Netcode_Patcher-0.2.5
Sligili-More_Emotes-1.3.3
TwinDimensionalProductions-CoilHeadStare-1.0.6
Hamunii-JetpackWarning-2.2.0
akechii-DiscountAlert-2.3.0
mrov-LethalRichPresence-0.5.8
willis81808-LethalSettings-1. 4.0
willis81808-HackPad-1.1.3
Evaisa-LethalThings-0.9.4
Malco-Lategame_Upgrades-3.1.1
ButteryStancakes-AccurateStaminaDisplay-2.0.0
Dev1A3-RecentlyPlayedWith-1.0.3
fumiko-CullFactory-0.8.2

**Comment by WhiteSpike** [comment]
Without any kind of logs, I can just guess the kind of issues it can happen to reduce performance:
- Error crashing which is not handled til it's shown in the log, leading to stutters.
- Functions are implemented with time complexity superior to O(n), leading to possibly exponential time dependant on input.

LGU does have some patches in enemies and players which could affect performance but the best we got is boombox and peeper iteration which only iterates if there's any instance of these objects.

You're absolutely sure that it is LGU that has performance issues and not LethalLib?

**Comment by Paradox75831004** [comment]
I'm just guessing, I was checking on the same side, and there was a slight decrease in performance. I need more information, but I don't have many testers, I check everything alone and make reports, you'll forgive me...
