### ISSUE TITLE
 Reloading a save makes the upgrades disappear

### ISSUE THREAD

**Issue by AbenthyIrae** [Malcolm-Q/LC-LateGameUpgrades#308]
Reloading a save makes the upgrades disappear and I have to buy everything new, i don't know what to do to fix this :c

**Comment by WhiteSpike** [comment]
Without any sort of logs, I can only guess and is that an error is happening when trying to save LGU relevant data, leading to an empty/trash save file.

I have reworked a bit of the saving mechanism we use to save stuff so maybe next release this issue won't occur or at least as often.

I would like to look at the logs whenever this happens to understand if the issue will still persist.

**Comment by AbenthyIrae** [comment]
Ooh okay ty ! if it happens again, I will send you the logs
