### ISSUE TITLE
The script for returning the ship to orbit does not work

### ISSUE THREAD

**Issue by Paradox75831004** [Malcolm-Q/LC-LateGameUpgrades#316]
When I disabled this mod, everything worked as expected.
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/72872478/65f22748-f830-42bd-bef0-9172cb88206c)

018dd089-1093-390a-350d-a5792fb89f02

I checked it alone and with the guys. On our build, an error is written in the console, something did not pass the test and the objection does not work.

For the error to work, in this build, turn on Late_Game and try to fly solo to any planet - die and monitor the behavior of the autopilot

**Comment by WhiteSpike** [comment]
Resolved in 3.2.2
