### ISSUE TITLE
Night Vision Does not keep Battery upgrades after re loading a file

### ISSUE THREAD

**Issue by santocraft** [Malcolm-Q/LC-LateGameUpgrades#32]
We had the Night Vision upgrade at max, after restarting the game and loading the file once again, it showed up in the terminal that we already had the max upgrade, however it was behaving like the LVL 1.

**Comment by Malcolm-Q** [comment]
I'll try look into it, thanks

**Comment by Malcolm-Q** [comment]
I made a silly mistake on the overriding loading method for this one, should be resolved now. It will be applied in 2.6.0
