### ISSUE TITLE
Bargain Connections throwing an error on finishing a day - as it shows end game stats

### ISSUE THREAD

**Issue by remiX-** [Malcolm-Q/LC-LateGameUpgrades#324]
So this is on the first day of 2nd quota. It caused the run to end there as the ship was stuck on "Wait for ship to land".

My UI also disappeared as in the second screenshot - and shows LethalThings in the middle - not sure why.

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/2831747/56b2c758-79ea-4c21-8604-75e24a85eb86)

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/2831747/c67aca89-6b33-4600-8e3a-b4fd8fbdb511)

**Comment by WhiteSpike** [comment]
It should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/328) and live in next release.
