### ISSUE TITLE
Typing switch into the terminal opens the moons selector

### ISSUE THREAD

**Issue by ofoxsmith** [Malcolm-Q/LC-LateGameUpgrades#325]
Typing `switch` into the terminal opens the moons selector, but typing `switch <player>` changes the currently targeted player.

This started happening after upgrading lategame, so I assume it's a bug here.

**Comment by WhiteSpike** [comment]
So:
- Started a game
- Went to the Terminal
- typed ``switch``
- It prompted ``Switching radar cam view``
- typed ``switch <player>``
- It prompted ``Switched radar to player``

Am I missing a step here? Because I can't seem to reproduce the behaviour you're describing.

**Comment by ofoxsmith** [comment]
I can't consistently reproduce it either. Either way, I don't think its a bug with LategameUprgades, just started happening when it was updated.

**Comment by remiX-** [comment]
Hey @ofoxsmith, are you using Wesleys_Moons?
