### ISSUE TITLE
Unable to interact unless sprinting

### ISSUE THREAD

**Issue by FoxivanFable** [Malcolm-Q/LC-LateGameUpgrades#329]
in the most recent major update i suddenly cannot change my interact status, if im looking at the terminal and i sprint, i can interact ONLY with the terminal until i sprint while facing another interactable item. but the cherry on top is that i no longer regen stamina

this only started happening with that update

**Comment by FoxivanFable** [comment]
getting the log file now

**Comment by FoxivanFable** [comment]
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14382102/LogOutput.log)

**Comment by ytitnE** [comment]
I just found that disabling sickbeats causes this issue

**Comment by WhiteSpike** [comment]
Should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/332) in next release.
