### ISSUE TITLE
Bug Report: Underwater Teleport

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#33]
Don't know if anyone has already found this or I'm the first one.

I found that if you fall into water and then teleport out of it using the advanced portable tele (didn't check normal portable tele), your character will forever walk slow and sound as if he's still underwater.

**Comment by Malcolm-Q** [comment]
I think you're the first. Should be an easy fix though, thanks

**Comment by Malcolm-Q** [comment]
I think this is actually a bug in the base game when teleporting someone out, regardless it should be fixed now and will be included in next update (2.6.0)
