### ISSUE TITLE
Contract items disapear

### ISSUE THREAD

**Issue by TheRealMrKam** [Malcolm-Q/LC-LateGameUpgrades#330]
Reloading a save makes Contract items (lost scavanger, bomb...) disapear from the ship.

Here is the log of me taking a Scav to the ship quitting and reloading the save, if it can help you in any way:

[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14386109/LogOutput.log)

(I have this bug for multiple updates, reported it on Discord. Reporting here again to be sure you have it.)

**Comment by WhiteSpike** [comment]
The issue with these two specifically is that their initial state is not in grabbable state (scavenger will start in injured and bomb will start clocking), besides the check if they are in a contract to be "visible" to the player.

When I have the time to look at these, I will have to rearrange some stuff to make sure the "grabbable" states are saved when they are stored in the ship and reboot happens.

**Comment by WhiteSpike** [comment]
Should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/342) and live in next release.
