### ISSUE TITLE
[Bug] Version 3.2.2 breaking interraction with everything on the ship.

### ISSUE THREAD

**Issue by Uniteria** [Malcolm-Q/LC-LateGameUpgrades#333]
Hey :) As tittle said, new version is breaking all interractions on the ship. In log it says something about Bigger Lungs constant error.
<img width="1920" alt="Lethal_Company_bgbBZ3HRJU" src="https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/156091332/0c2adeb5-ff88-4150-85e6-703145020ab5">
<img width="1280" alt="Lethal_Company_2acxBBubGQ" src="https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/156091332/dcd198e3-abf1-40b7-991f-102d9d390605">

**Comment by Uniteria** [comment]
Update :)

Version 3.2.3 seems to fix that issue. Will monitor it further tho.
Thanks!

**Comment by Uniteria** [comment]
Another update

Version 3.2.3 made monsters immune to shovel damage.
Reverted back to 3.1.1 and everything works fine.

**Comment by WhiteSpike** [comment]
I probably know why. I will take a look at it.

**Comment by Uniteria** [comment]
Aight, thanks for info :)
