### ISSUE TITLE
Bug Report: Rocket Launcher Ammo missing on server start / Scrap Insurance not working

### ISSUE THREAD

**Issue by Fabrieze** [Malcolm-Q/LC-LateGameUpgrades#335]
As title says, when restarting or relogging into a server, the ammo on a rocket launcher is all gone. Similarly, we tried scrap insurance once and it never worked: all the items disappeared.

**Steps:**
1: Buy rocket launcher, ammo is full (4 green dots.)
2: Restart server
3: Rocket Launcher is missing ammo.

1: Buy scrap insurance
2: die
3: items are all gone :(.

**Mod list:**
1. BepInExPack v5.4.2100
2. BepInEx pack for Mono Unity games. Preconfigured and ready to use.
3. MoreCompany v1.8.1
4. Runtime_Netcode_Patcher v0.2.5
5. More_Emotes v1.3.3
6. LateCompany v1.0.11
7. ShipLoot v1.0.0
8. Boombox_Controller v1.2.2
9. ShipClock v0.9.0
10. ObjectVolumeController v1.0.4
11. Boombox_Sync_Fix v1.1.2
12. HDLethalCompany v1.5.6
13. More_Suits v1.4.1
14. AdditionalContentFramework v1.0.3
15. AdditionalSuits v2.0.0
16. YippeeMod v1.2.4
17. LCBetterSaves v1.7.3
18. HookGenPatcher v0.0.5
19. LethalLib v0.14.2
20. LethalThings v0.9.4
21. BoomBoxNoPower v1.0.0
22. LCSoundTool v1.5.1
23. CustomSounds v2.3.2
24. FasterItemDropship v1.2.1
25. FastSwitchPlayerViewInRadar v1.3.2
26. GeneralImprovements v1.1.9
27. PathfindingLagFix v1.2.1
28. DissonanceLagFix v1.0.0
29. FixRPCLag v1.0.1
30. NoSellLimit v1.0.1
31. LethalCompany_InputUtils v0.6.3
32. BetterSprayPaint v2.0.2
33. WeatherMultipliers v1.1.0
34. LethalExpansionCore v1.3.15
35. ShipMaid v4.0.6
36. Lategame_Upgrades v3.2.3
37. BetterStamina v1.3.2
38. SpectateEnemies v2.3.1
39. PeterGriffinHouse v3.6.5
40. LethalExpansion v1.3.41
41. ExpansionAssets v1.1.0
42. Orion v1.3.0
43. FairGiants v1.0.0
44. LethalSnap v1.5.0
45. MoreFabSuits v1.0.4
46. ModelReplacementAPI v2.3.7
47. Lethal_Master_Chief v0.1.0
48. LethalEscape v0.8.5
49. CullFactory v0.8.3
50. NuclearLib v1.0.4
51. Symbiosis v1.0.5
52. SnatchinBracken v1.3.8
53. OuijaBoard v1.5.3
54. AlwaysHearActiveWalkies v1.4.4
55. Diversity v1.1.10
56. OdinSerializer v2022.11.9
57. LethalNetworkAPI v2.1.6
58. Aquatis v1.1.1
59. LC_Masked_Fix v0.0.2
60. SellBodies v1.1.0
61. DanceTools v1.1.4
62. LethalConfig v1.3.4
63. LethalEmotesAPI v1.5.1
64. EnemyInteractions v1.1.0
65. BadAssCompany v1.1.5

Output:
https://pastes.io/biplfg5tf5 (rest is just a bunch of cosmetic spam)

**Comment by WhiteSpike** [comment]
Don't know about the rocket launcher issue as we don't have any implementation of a rocket launcher item in this mod and we don't mess with item saving/loading.

Related to the scrap insurance issue, I need the logs of when this happens. The logs you provided seem to only show when you booted up in the game and not when the items disappeared when used Scrap Insurance

**Comment by Fabrieze** [comment]
Oops, that's super my bad. Lots of mods, I got this mixed up with lethal things. Unfortunately, don't have the log for the scrap insurance and we're avoiding it after it didn't work the one time, but if I ever get the time to test it solo I'll update.

**Comment by WhiteSpike** [comment]
Closing due to lack of response.
