### ISSUE TITLE
shopping carts price change when loading a save

### ISSUE THREAD

**Issue by sangca2002** [Malcolm-Q/LC-LateGameUpgrades#336]
i was using the gamblingatthecompany mod and changed shopping cart prices to about 1300 credits and then when i load back the save, its price is 189 and it also doesnt have the square credit mark.

**Comment by WhiteSpike** [comment]
Should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/337) in next release.
