### ISSUE TITLE
[BUG] shovel cannot deal any dmg

### ISSUE THREAD

**Issue by CoolLKKPS** [Malcolm-Q/LC-LateGameUpgrades#338]
config file: 
[com.malco.lethalcompany.moreshipupgrades.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14394087/com.malco.lethalcompany.moreshipupgrades.txt)

**Comment by CoolLKKPS** [comment]
if need modlist, just tell me, but i don't think that's necessary

**Comment by WhiteSpike** [comment]
Repeat of issue reported in latest comments of #333

**Comment by CoolLKKPS** [comment]
copy
