### ISSUE TITLE
Enemy loot sample bug/ Unable to kill enemy on client side

### ISSUE THREAD

**Issue by newcomer953** [Malcolm-Q/LC-LateGameUpgrades#339]
1/ Enemy loot sample bug

Using Hunter, when enemies got killed, enemy that drop samples will drop 2 samples on client side, only one of them are interactable.

The one that can't be interacted will get stuck on client side, only a lobby reload will remove them.

2/ Unable to kill enemy on client side

If a client killed an enemy on their side, the enemy will still be alive on host side and can still kill the host.

Only the host can kill enemy except for weak enemies like Hoarding bug or an exception like Nut cracker since they don't drop loot sample.

The image and player log are from the client side.

The image is from client side where the samples can't be interacted.

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/52492375/614cc105-c75d-48f7-ab89-3b9a41f56c74)
[Player.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14396064/Player.log)

**Comment by remiX-** [comment]
> 2/ Unable to kill enemy on client side
> If a client killed an enemy on their side, the enemy will still be alive on host side and can still kill the host.
> Only the host can kill enemy except for weak enemies like Hoarding bug or an exception like Nut cracker since they don't drop loot sample.

+1 on this. A friend of mine and I experienced this this past weekend but we weren't sure if it was LGU or not. We resorted to me (the host) doing all the killing. Client killing also didn't drop samples at all for us - we had level 3
