### ISSUE TITLE
NV keybinding config sometimes doesn't work

### ISSUE THREAD

**Issue by julioSantosAlbarregas** [Malcolm-Q/LC-LateGameUpgrades#35]
I want to change the key to toggle it on/off to Q instead of leftAlt but I'm unable to make it work, it shows "Press q to toggle Night Vision!!!" on chat but it somehow keeps working with leftAlt. That's not the case when I change to, for example, RightAlt, which works as intended, Which key name should I use to change it to Q or any letter?

**Comment by DillyTheDillster** [comment]
I did just test it myself and it does seem to work with a 'Q' bind. 

initially it did NOT work with a lowercase 'q' so i might need to remedy that, i also did a relaunch after changing to 'Q' so verify that you do that as well
