### ISSUE TITLE
Stimpack Bug

### ISSUE THREAD

**Issue by HourSpeed1017** [Malcolm-Q/LC-LateGameUpgrades#351]
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14427150/LogOutput.log)
Even though Stimpack upgrade is active, player health is locked at 100. Happens after introducing new mod.

**Comment by WhiteSpike** [comment]
Can you specify what was the new mod you introduced where the issue started occuring?

**Comment by HourSpeed1017** [comment]
Sorry for late response, the mod's name is BeehivesEverywhere. Even after removing the mod the bug continued.

**Comment by WhiteSpike** [comment]
Stimpack seems to be working as it gives the players the health buff. It's probably some other mod that resets health or something.

**Comment by HourSpeed1017** [comment]
Strange. I have 2 mods that are related to health being: LethalRegeneration and HealthStation. I've also configured the Stimpack upgrade to have 5 tiers. Should I send modlist?

**Comment by WhiteSpike** [comment]
Sure, might be easier to browse than using logs. Lol.

**Comment by HourSpeed1017** [comment]
ok.

**Comment by HourSpeed1017** [comment]
ReservedItemSlotCore v1.8.17 by FlipMods

**Comment by HourSpeed1017** [comment]
ReservedItemSlotCore v1.8.17 by FlipMods

**Comment by HourSpeed1017** [comment]
ReservedItemSlotCore v1.8.17 by FlipMods
ReservedFlashlightSlot v1.6.3 by FlipMods
LC_API v3.4.5 by 2018
LethalCompany_InputUtils v0.6.3 by Rune580
BetterSprayPaint v2.0.2 by taffyko
HookGenPatcher v0.0.5 by Evaisa
LethalLib v0.14.2 by Evaisa
CSync v2.0.0 by Owen3H
TerminalApi v1.5.2 by NotAtomicBomb
FacilityMeltdown v2.4.1 by loaforc
FairAI v1.3.3 by TheFluff
HDLethalCompany v1.5.6 by Sligili
LethalExpansionCore v1.3.15 by jockie
ImmersiveScraps v1.2.0 by Justice69
LethalConfig v1.3.4 by AinaVT
LethalEscape v0.8.5 by xCeezy
LethalExpansion v1.3.44 by HolographicWings
LethalPosters v1.2.0 by femboytv
LethalThings v0.9.4 by Evaisa
StarlancerAIFix v3.1.0 by AudioKnight
LCMaxSoundsFix v1.1.0 by Hardy
Wesleys_Moons v2.1.7 by Magic_Wesley
ExpansionAssets v1.1.0 by sfDesat
Aquatis v1.1.1 by sfDesat
Celest v0.2.1 by sfDesat
Runtime_Netcode_Patcher v0.2.5 by Ozone
More_Emotes v1.3.3 by Sligili
Permanent_Ladder v1.0.3 by Silvercore
Giant_Extension_Ladders v1.2.2 by Inoyu
More_Suits v1.4.1 by x753
ShipLoot v1.0.0 by tinyhoot
SirenHead v0.7.8 by Ccode_lang
TVLoader v1.1.1 by Rattenbonkers
TooManySuits v1.0.5 by Verity
AlwaysShowClock v1.0.0 by thomas
ShootableMouthDogs v1.0.1 by AgentRev
BetterShotgun v1.4.3 by Hypick
BetterStamina v1.2.0 by OpJosMods
Boombox_Sync_Fix v1.1.2 by FutureSavior
ClearFirstPerson v1.0.1 by Mhz
CoilHeadStare v1.0.9 by TwinDimensionalProductions
CrossHair v1.1.0 by CTNOriginals
LCSoundTool v1.5.1 by no00ob
CustomSounds v2.3.2 by Clementinise
DetailedScan v1.2.2 by fivetoofive
DoorFix v1.0.0 by itsmeowdev
EmployeeAssignments v1.1.0 by amnsoft
EnhancedRadarBooster v1.6.2 by MrHydralisk
FasterItemDropship v1.2.1 by FlipMods
GokuBracken v1.5.4 by Vulf
HealthStation v1.0.1 by Thorlar
LethalRegeneration v1.2.0 by Toskan4134
HealthMetrics v1.0.2 by matsuura
Hold_Scan_Button v1.1.1 by FutureSavior
HookGun v1.3.4 by BLKNeko
LC_Masked_Fix v0.0.2 by kuba6000
NoHornCooldown v1.0.0 by SkilledOn
kill_a_giant v1.0.1 by kim_bird
HazardsOutside v1.1.3 by snake_tech
Haunted_Harpist v1.2.6 by Bob123
LethalSettings v1.4.0 by willis81808
LetMeLookDown v1.0.1 by FlipMods
MaskedEnemyOverhaul v3.1.2 by HomelessGinger
TakeThatMaskOff v2.1.5 by SillySquad
Mimics v2.4.1 by x753
Minimap v1.0.5 by Tyzeron
MoreItems v1.0.2 by Drakorle
BepInUtils v1.2.1 by Ozone
Glow_Steps v1.1.2 by Ozone
DoorBreach v1.1.0 by Nyxchrono
QuotaRollover v2.3.0 by boxofbiscuits97
RankFix v1.0.2 by Glitch
ReservedSprayPaintSlot v1.0.7 by FlipMods
ScanFix v1.0.3 by Nebulaetrix
ScannableCodes v1.0.2 by Dev1A3
ShowAmmoCount v1.1.0 by SoraYuki
ThrowEverything v0.4.1 by Spantle
SpectateEnemies v2.3.1 by AllToasters
WeatherMultipliers v1.1.0 by Blorb
Lategame_Upgrades v3.3.0 by malco

**Comment by remiX-** [comment]
> Stimpack seems to be working as it gives the players the health buff. It's probably some other mod that resets health or something.

We noticed it as well until a restart. Then it was back to 180 until we died (I think). Now it seemingly is locked at 100 in orbit.

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/2831747/80e5a001-e43e-4c68-b0b4-09cfc1bd4a38)

Current logs in our current game:
[Player.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14466600/Player.log)

**Comment by HourSpeed1017** [comment]
Do you also manually install mods?

**Comment by remiX-** [comment]
> Do you also manually install mods?

Nope we use Thunderstore

**Comment by HourSpeed1017** [comment]
> Nope we use Thunderstore

Ok, so it's not happening to me only.

Did it start happening when you installed a new mod?

**Comment by remiX-** [comment]
> > Nope we use Thunderstore
> 
> Ok, so it's not happening to me only.
> 
> Did it start happening when you installed a new mod?

It's hard to tell as everytime we lose / get fired we look for something new to add haha. In this case we had added LethalResonance for sound modification stuff :D  

I will test this with my modding profile and see - if still I will test with LGU / LethalLib standalone

**Comment by HourSpeed1017** [comment]
> * Literally just BepInExPack + LGU + HealthMetrics (to see hp)


I also tried only HealthMetrics and LGU and it worked. Then I put the rest of my modpack in and it stopped working. Weird.

**Comment by WhiteSpike** [comment]
I believe this is a problem with old saves. Because I forgot of a table that is used to store each player's level (so that everyone can see the same health values) to the synchronization between old and new save format, it might not give the health back upon revive.

However, if this is happening on a brand new save (past 3.2,0), I will look at the saving mechanism to try fix it.

**Comment by remiX-** [comment]
> I believe this is a problem with old saves. Because I forgot of a table that is used to store each player's level (so that everyone can see the same health values) to the synchronization between old and new save format, it might not give the health back upon revive.
> 
> However, if this is happening on a brand new save (past 3.2,0), I will look at the saving mechanism to try fix it.
> 
> EDIT: The reason I say this is that I tested this on two saves, one's from January and other from today. The today's worked as expected however the january's, the revive prompt did not bring the health back with the current version. Might be due to forgetting to also save the health tables used to keep everyone's track of their health.

So in the video I started from a fresh save (as of today) and then also exited, deleted, and started a completely fresh one - so in my test case I hadn't use an old save :(

Good to know you most likely know the cause though :D

**Comment by HourSpeed1017** [comment]
> So in the video I started from a fresh save (as of today) and then also exited, deleted, and started a completely fresh one - so in my test case I hadn't use an old save :(

I was also playing in a new save.

**Comment by WhiteSpike** [comment]
This issue should be [resolved](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/358) in next release
