### ISSUE TITLE
scan enemies verbose function not working well

### ISSUE THREAD

**Issue by sangca2002** [Malcolm-Q/LC-LateGameUpgrades#352]
it only shows lootbugs... maybe due to other mods' creatures? i also felt quantum disruptor making enemies spawn significantly less

**Comment by WhiteSpike** [comment]
Enemy spawning is influenced by the time in the moon, so if you have something slowing down the moon's time, the enemy spawns will also be influenced.

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/58040140/923d9cb9-e51e-4754-9792-93a98cc16697)
It should still be able to grab their enemy type to know their name. However, just to be sure, I need the logs of when you decide to use ``scan enemies`` when a custom enemy spawned to know for certain.
