### ISSUE TITLE
[BUG/Log not helpful] Upgrade desync between client and host, for some reason the host can't take any dmg after recently sick beat patch

### ISSUE THREAD

**Issue by CoolLKKPS** [Malcolm-Q/LC-LateGameUpgrades#354]
Convert all upgrades to be shared. = true
Individual Purchase = All true

but after rejoin, upgrade will work normally, so should be cause bc not the right time i guess

!!! Note host can't take any dmg might cause by other mods, still trying to figure out, that already took 4 days to test

**Comment by CoolLKKPS** [comment]
here's the save, mod and "update to try fix this issue" config file
[LCSaveFile3.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14452390/LCSaveFile3.zip)
[com.malco.lethalcompany.moreshipupgrades.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14452393/com.malco.lethalcompany.moreshipupgrades.txt)
[mods.yml.txt](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14452408/mods.yml.txt)

**Comment by CoolLKKPS** [comment]
re-enable sick beat and hunter, and set all Individual Purchase to true to reverse to original setting

**Comment by WhiteSpike** [comment]
Possible spots to look at:
- Config sync throw an error
- Save share throw an error.
- Upgrade purchase throw an error.
- Logic in any of these is wrong.

So, to know where to look at, I need the logs from each person in the lobby when the desync happens (when purchasing, using ``load lgu <playerName>``, etc.).

**Comment by CoolLKKPS** [comment]
will let u know if the issues happen again, since this issues is very random (idk what happen even), so i will start test desync issue first

**Comment by CoolLKKPS** [comment]
still testing, but not sure if this issue already fixed by other mods, idk weird, if this issue happen again will reopen this issue

**Comment by CoolLKKPS** [comment]
but de-sync issue sometime worked sometime not, i have to tell my friend how to get logoutput file and send to me, which will need more time
