### ISSUE TITLE
upgrades not being saved

### ISSUE THREAD

**Issue by sangca2002** [Malcolm-Q/LC-LateGameUpgrades#356]
changing the upgrade save timing to autosaving did fix some things, but the problem is that when we purchase upgrades during orbit, they are not saved at all. it happens a lot because we usually try to hit the company for credits and then go back into orbit to buy upgrades, since after visiting the company on quota different upgrades go on sale. what makes it unavoidable is that the sale does not persist after saving & loading, and on the first day no upgrades go on sale, so we have no way to make our way through except going on another run before quitting.

**Comment by WhiteSpike** [comment]
So the issue here is not the saving mechanism itself but rather the sales of the upgrades not being saved through reboots?

**Comment by remiX-** [comment]
What we usually do that seems to work is sell @ company, buy upgrades on special and then route to any moon - I think that does some kind of internal save? From there we usually have our upgrades still in place.

Another thing is to screenshot it and check it again when playing again and making use of `forcecredits` to match it back up :)

**Comment by WhiteSpike** [comment]
Game by default already makes an autosave whenever you extract from a moon, you can see the prompt appear on the bottom right.

I just need to understand what is wrong to know what to fix.

If it's the fact that the saving was moved from disconnect to autosave, it seemed like the most logical as the vanilla doesn't save what was the moon you routed to before you quit. It would make you back to the moon you were on when you autosaved (thus why you keep the credits).

If it's the upgrade sales that are not being persisted, I would have to check that code as I wasn't the one who wrote it and would need to read it to understand what it's doing behind scenes.

**Comment by WhiteSpike** [comment]
I found that the LGU sales were in fact not being saved after quota. It should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/378) in next release.
