### ISSUE TITLE
Portable Teleporter not working with input outside of mouse

### ISSUE THREAD

**Issue by mlabus93** [Malcolm-Q/LC-LateGameUpgrades#357]
https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/abf3d4099793d83bf5ade8afdba357a58efbcae2/MoreShipUpgrades/UpgradeComponents/Items/PortableTeleporter/BasePortableTeleporter.cs#L106

I noticed that the portable teleporter doesn't function on controller, but on mouse left click it does. I think this is the source and it's coded directly to mouse input only.

**Comment by WhiteSpike** [comment]
Yeah, it would have to be reworked the same way as NV and Wheelbarrow's drop all items bindings were.

**Comment by WhiteSpike** [comment]
This issue should be [resolved](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/358) in next release.
