### ISSUE TITLE
[BUG] Night vision

### ISSUE THREAD

**Issue by UlqCifer** [Malcolm-Q/LC-LateGameUpgrades#367]
When someone buys and wears night vision googles everyone on the server gets it and if someone dies the person who died and the host loses it

**Comment by WhiteSpike** [comment]
Can you provide the configurations of when this occured please?

**Comment by UlqCifer** [comment]
What exactly do you need, didnt bother that much with modding here

**Comment by UlqCifer** [comment]
Config for the mod? For some reason it does not generates. All 4 my friends doesnt have config for the mod too, for some reason, cant even rebind buttons because yesterday alt was working for NV now alt doesnt work...didnt change a thing

**Comment by UlqCifer** [comment]
nvm found the config

**Comment by UlqCifer** [comment]
So if config for the mod so its default one

**Comment by SnackSBR** [comment]
do you guys use input utils? If so check the keybind menu. The current version sync the keybind that the host use. If you are not using input utils check Toggle Night Vision Key inside the mod config for the current key.

**Comment by UlqCifer** [comment]
I managed to fix keybinding problems, but still if we enable "Lost on death" option host always loses NV

**Comment by UlqCifer** [comment]
So yea, upgrades for all + lost on death = host always loses NV on death

**Comment by WhiteSpike** [comment]
Made a small change in 3.4.0 regarding this, don't know if it will fix the issue. If you could check it, I would appreciate it.
