### ISSUE TITLE
Sales Not Refreshing

### ISSUE THREAD

**Issue by TwoPointInfinity** [Malcolm-Q/LC-LateGameUpgrades#37]
Sales in the vanilla store change every profit quota, but it seems that for at least 3 quotas the sales in LGU haven't changed. Hopefully this is a bug and are meant to change regularly, if not its a feature request for changing sales like the base game.

**Comment by Malcolm-Q** [comment]
Yeah I believe this is a client side issue. The host should have sales update. If it's what I think it is it's a stupid mistake and a fix will be out soon.

**Comment by TwoPointInfinity** [comment]
thank you so much, im glad i can bring this to your attention, i wish i could do more if i knew anything about coding i would make a pull request.
