### ISSUE TITLE
Error no game start with hunter enabled

### ISSUE THREAD

**Issue by mcNuggets1** [Malcolm-Q/LC-LateGameUpgrades#370]
https://i.imgur.com/sQ0bqTK.png

**Comment by WhiteSpike** [comment]
The amount of prices you have in the hunter upgrade has to be the same as the number of tiers for monster samples.

**Comment by mcNuggets1** [comment]
main price: 800
following: 400, 600, 800, 1000
sample string: Hoarding Bug-Centipede, Crawler-Bunker Spider, Baboon Hawk, MouthDog, Flowerman
i dont see no issue with my config yet i get the error

**Comment by SnackSBR** [comment]
you have 5 prices (base plus 4 for upgrades) but only 3 monster tiers

**Comment by mcNuggets1** [comment]
I thought commas seperated them, fuck.
Please just add a warning for mismatching arguments. ^^
