### ISSUE TITLE
Boombox doesnt work with DiscJockey addon, just errors on AddToList

### ISSUE THREAD

**Issue by mcNuggets1** [Malcolm-Q/LC-LateGameUpgrades#371]

**Comment by WhiteSpike** [comment]
Can't reproduce on current released version. Need more information.

**Comment by mcNuggets1** [comment]
I use DiscJockey and use mp3 files from disk to load at start.
On opening the menu with F10 it errors, won't open the menu until I disable the "sick beats" perk.

**Comment by WhiteSpike** [comment]
This issue should be [resolved](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/373) in next release
