### ISSUE TITLE
Compat issue with CompanyBuildingEnhancements

### ISSUE THREAD

**Issue by mcNuggets1** [Malcolm-Q/LC-LateGameUpgrades#382]
https://i.imgur.com/DdCh9Zy.png
Came when travelling to company building with the mod enabled and CompanyBuildingEnhancements installed (AdvCompany too)

**Comment by WhiteSpike** [comment]
Seems like CompanyBuildingEnhacements crashed when doing stuff for weightless inventory in company moon. I don't know what it's doing and I can't check the source code so you will have to ask that mod's author what happened to understand what i need to do.

**Comment by WhiteSpike** [comment]
Closing due to lack of response.
