### ISSUE TITLE
Thunderstore list of upgrades is out-of-date

### ISSUE THREAD

**Issue by tmewett** [Malcolm-Q/LC-LateGameUpgrades#384]
Hi, thanks for this fun mod.

The list of items and upgrades on the Thunderstore page is missing some items. https://thunderstore.io/c/lethal-company/p/malco/Lategame_Upgrades/

At least the following are missing: 

- Helmet
- Wheelbarrow
- Drop Pod Thrusters
- Sick Beats
- Shutter Batteries

**Comment by WhiteSpike** [comment]
3.4.0 release has the README updated. I will be closing this but feel free to open a new one when any forgetfulness happens again.
