### ISSUE TITLE
INFO descriptions contain broken values

### ISSUE THREAD

**Issue by tmewett** [Malcolm-Q/LC-LateGameUpgrades#385]
The values aren't inserted, instead showing the code / variable names.

For example, INFO WHEELBARROW produces:

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/3171736/20800c82-0085-4939-aba9-98c61c3e7fbe)

**Comment by WhiteSpike** [comment]
Should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/386) in next release.

**Comment by tmewett** [comment]
Thanks! Though it's not just wheelbarrow I think, I recall trying another time and seeing the same thing

**Comment by WhiteSpike** [comment]
There could be similar fragments with some infos when I changed to ConfigEntry as strings don't warn me when using ConfigEntry for text.

**Comment by WhiteSpike** [comment]
Released 3.4.0 which seemed to fix a good bunch of them. I will be closing this but feel free to make a new one if it arises again.
