### ISSUE TITLE
Disable Splashscreen in config or similar for Steam Deck users

### ISSUE THREAD

**Issue by Pumamori** [Malcolm-Q/LC-LateGameUpgrades#39]
Good day,

I genuinely enjoy the mod quite a bit but for a friend of mine, the Splashscreen with the "Press Escape" thing is quite annoying and it'd be great if it could either be skipped via config or just not be there to begin with. There is a workaround (Steam maps Steam button + a Dpad input to Escape) but having the option to skip it altogether would be better!

Much appreciated & have a wonderful day!

**Comment by Malcolm-Q** [comment]
Hey I will just add more options for buttons to press to skip it. If I remove it I will be flooded with questions that it addresses. Even with it in it doesn't stop people asking how to open the store and stuff.

**Comment by Pumamori** [comment]
@Malcolm-Q 
Thanks for the quick reply - I would rather there be an option to disable it, as it's quite intrusive when creating a modpack - assuming someone creates it to play with friends, they are likely to explain how the mod works, so it'd be nice to have the option in the configuration to not show it, I'm not saying to get rid of it altogether. (: 

More buttons to get rid of the screen are welcome too, though.

**Comment by Malcolm-Q** [comment]
Yeah that will be added.

You would assume so yeah but no they are not likely to do that at all or even read it for themselves. They are likely to message me that the mod doesn't work.

Before adding the splashscreen I would get probably 10 people a day asking the same question that I had plastered everywhere. Now it's down to maybe 1-3 a week with the splashscreen.
