### ISSUE TITLE
Client disconnect issue breaks game

### ISSUE THREAD

**Issue by remiX-** [Malcolm-Q/LC-LateGameUpgrades#397]
Hi,

For the last few versions, we've noticed that when a client disconnects, or if the host leaves causing clients to disconnect, an error occurs which breaks the ability to rejoin. Sometimes rejoining works but then upgrades don't get applied to that client.

Additional:
* This never occurs for the host
* It occurred on day 1, so we had no upgrades
* Appears to occur in a map possibly?
* Exiting after selling at company building it was fine

I have attached a log for this happening on a friends PC (as I'm always the host).

[Player-prev.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14656790/Player-prev.log)

Note: we have not checked v3.4.0 that just come out recently yet.

**Comment by WhiteSpike** [comment]
~~Not the damn components being missing again~~

**Comment by WhiteSpike** [comment]
3.4.3 was released with a possible solution to this issue.
Check if it persists and if so, post another logs of when it happens.

**Comment by WhiteSpike** [comment]
Closing due to lack of response so assumed it's fixed.
