### ISSUE TITLE
LateGame_Upgrades can only be used by client, not whole party

### ISSUE THREAD

**Issue by stepeche** [Malcolm-Q/LC-LateGameUpgrades#401]
Hi, 

I noticed with the new update that when I launch Lethal Company with the Lategame_Upgrades mod, I have the mod but my friends who are playing do not (i.e. we had purchased Back Muscles, I have this addition but they do not). They have the mod installed and it had been working fine when we played on 3/18/24. I'm not sure if this has to do with the Csync upgrade but please let me know if there is something I need to do to get this to work, as it is a really helpful mod for us. Thank you.

**Comment by Sourceshard** [comment]
Typing LGU also presents a blank black screen

**Comment by WhiteSpike** [comment]
If you can provide logs from both host and client when this issue occurs (upgrades not being loaded at boot or blank LGU screen), I can try look what's causing these issues to happen.

**Comment by Sourceshard** [comment]
Host
https://cdn.discordapp.com/attachments/133839601067491338/1219988871744454656/message.txt?ex=660d4e2d&is=65fad92d&hm=4ccf2be040ba126398fa7ef3c5e7c711ade44c3ca88f3a604bb5b547260cbbac&

Player 2
https://cdn.discordapp.com/attachments/133839601067491338/1219988471599333406/message.txt?ex=660d4dcd&is=65fad8cd&hm=81b5a3671e2cc032d0179843cee08a089d8ab252a92177a9a78942abbb2c4e32&

**Comment by stepeche** [comment]
Thank you, when I get home today I’ll get you those logs.Sent from my iPhoneOn Mar 20, 2024, at 4:42 AM, Sourceshard ***@***.***> wrote:﻿
Host
https://cdn.discordapp.com/attachments/133839601067491338/1219988871744454656/message.txt?ex=660d4e2d&is=65fad92d&hm=4ccf2be040ba126398fa7ef3c5e7c711ade44c3ca88f3a604bb5b547260cbbac&
Player 2
https://cdn.discordapp.com/attachments/133839601067491338/1219988471599333406/message.txt?ex=660d4dcd&is=65fad8cd&hm=81b5a3671e2cc032d0179843cee08a089d8ab252a92177a9a78942abbb2c4e32&

**Comment by Xyla28** [comment]
Hi, I encountered the same issue. When I joined the lobby I could not see, nor use LGU, but when I loaded the same save file from my partner's pc, the roles reversed

**Comment by stepeche** [comment]
Hi there, Here is the picture of my screen and the message I get. I’ve never seen it before. I also went through all of the code that pops up and I don’t see Lategame_Upgrades in it at all. I do see Csync. Sent from my iPhoneOn Mar 20, 2024, at 12:21 PM, Xyla28 ***@***.***> wrote:﻿
Hi, I encountered the same issue. When I joined the lobby I could not see, nor use LGU, but when I loaded the same save file from my partner's pc, the roles reversed

**Comment by WhiteSpike** [comment]
This issue should be [resolved](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/404) in next release.

**Comment by stepeche** [comment]
Thank you so much! Sent from my iPhoneOn Mar 21, 2024, at 9:38 AM, WhiteSpike ***@***.***> wrote:﻿
This issue should be resolved in next release.
