### ISSUE TITLE
Bigger Lungs does not apply "Stamina cost decrease on jumps"

### ISSUE THREAD

**Issue by AfterRebelion** [Malcolm-Q/LC-LateGameUpgrades#403]
### Versions:
LethalCompany: v49
BepInEx: 5.4.22
LateGameUpgrades: 3.4.1

### Steps to reproduce:
Pre: Configure value of "Stamina cost decrease on jumps" to some extreme values, like 0.1 or 8.0, to make effect more "Visible"
1. Start a new Lobby
2. Use forceCredits 9999, to be able to buy upgrades.
3. Purchase 1 Level of "Bigger Lungs" upgrade on LGU Store

#### Expected behavior:
All stats are modified, according to configuration
#### Actual behavior:
Only "Sprint Time Unlock" and "Stamina Regeneration Increase" are applied, and no change to Jump Stamina cost seems to be in place.

### Logs
[LC-LogOutput-20240320.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14671924/LC-LogOutput-20240320.log)

### Additional info:
Only PLAYER_SPRINT_TIME is reported on the Debug logging
`[Debug  :More Ship Upgrades] [Bigger Lungs] Adding 12 to PLAYER_SPRINT_TIME...`
Would be good for debugging purposes to also include Regeneration and Jump cost to the log.

**Comment by WhiteSpike** [comment]
Sprint time is increased starting the first ever level of Bigger Lungs
Stamina regeneration is applied on the first ever level of bigger lungs
Stamina cost on jumps is applied on the **second** ever level of bigger lungs.

If needed, I can add configuration to add at what levels you want to apply certain effects and/or make them the same logic as sprint time.

**Comment by AfterRebelion** [comment]
Hi, thanks for the quick response.
Can confirm that it works at level 2.
Was confused, since it's not mentioned anywhere, neither on the upgrade info page.

> ![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/559819/6395dba8-23bb-4a3e-810b-8511a29955f5)

Nor in the config documentation.
> ![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/559819/c7e5d445-53e2-4cb9-995d-70ca881ae3b0)

**Stamina regen** is not mentioned ingame either, however at least it's in the config documentation.
> ![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/559819/b5a277d2-9935-4b9b-82c1-32e9f7723d65)

I think I remember this maybe being mentioned on the Thunderstore mod page at some point?

Regarding adding configuration for this, I'm always onboard with more configuration options, however I don't particularly think it's required, default seems good.

Only reason I stumbled upon this, is because I'm trying to debug some random upgrade desync issues between host and clients (That's why I'm using some extreme config values, to make changes apparent at first sight), similar to https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/354 , and was confused as to why this config wasn't working.
