### ISSUE TITLE
Lategame_Upgrades not working for friends who also have it

### ISSUE THREAD

**Issue by stepeche** [Malcolm-Q/LC-LateGameUpgrades#406]
Hi there! I had a previous issue with Lategame_upgrades a couple days ago that was resolved with the newest update and worked when I played with my friends on 3/21/24. Today when we hopped on, I had the LGU mods active, and my friend who also has these mods wasn't able to utilize any of them (for example, we had back muscles on level 2, running shoes on level 1). He could however go onto the terminal and search LGU, and see the mods, but they showed as he needed to purchase the first level upgrade. I'm not sure if this is something with the mod itself or something on my computer. Thank you.

**Comment by WhiteSpike** [comment]
3.4.3 was released with a possible solution to this issue. 
Check if it still persists and if so, posts the logs of when it happens to see the origin of the problem.

**Comment by stepeche** [comment]
Thank you so much! Sent from my iPhoneOn Mar 23, 2024, at 5:34 AM, WhiteSpike ***@***.***> wrote:﻿
3.4.3 was released with a possible solution to this issue.
Check if it still persists and if so, posts the logs of when it happens to see the origin of the problem.

**Comment by Xyla28** [comment]
Hi, I've mentioned an issue with it to the previous post a few days ago as well, I too am seeing LGU in host's game and can purchase upgrades, but they seem to only apply to myself. The host's LGU has everything maxed out. 3.4.3 doesn't seem to have fixed it for me. We didn't get to try the previous update. Thanks!

**Comment by arriva2686** [comment]
Hi, same problem. An hour ago wanted to play with a friend, both have mods from Thunderstore, the same configuration and build. Bottom line - only the lobby leader has improvements, no restarts and reinstallations help

**Comment by WhiteSpike** [comment]
If you can provide logs from both host and client, I can try help.

**Comment by Xyla28** [comment]
[Player Client.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14736500/Player.Client.log)
[Player Host.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14736501/Player.Host.log)

I hope these are the right ones, thank you!

**Comment by StonedGoat** [comment]
would like to bump this, i am also having these desync issues and i've been having them for some time now
i can't get them right now but i'll try to drop my logs as well if it helps fix things cuz this is definitely not an isolated issue

**Comment by SlayScare** [comment]
Can confirm. Every 3.4.X version is not working for multiplayer. It works for the host but not for those who join. Its just blank screen when typing lgu aswell. 
When going back to v3.3.1 everything works fine. 
Thats what we did for now until its fixed. 

Thank you for your great work! This mod really elevates the Lethal Company Experience and we enjoy it :)

**Comment by stepeche** [comment]
Hi there, It looks like we can use lgu mods but only if we start a brand new game, and all individuals who are playing start in the new game. They are able to use the mods then, but not if they join an in progress game or a game that autosaved and we came back to. I’ve attached my logs, it also shows I have level two back muscles when it says I have level 3 in the terminal. I’ll also be attaching my friend’s logs in a bit as it showed him he has level 1/2 back muscles but they aren’t activatingSent from my iPhoneOn Mar 25, 2024, at 4:14 AM, SlayScare ***@***.***> wrote:﻿
Can confirm. Every 3.4.X version is not working for multiplayer. It works for the host but not for those who join. Its just blank screen when typing lgu aswell.
When going back to v3.3.1 everything works fine.
Thats what we did for now until its fixed.
Thank you for your great work! This mod really elevates the Lethal Company Experience and we enjoy it :)

**Comment by SlayScare** [comment]
Ah thank you!
Then we will try updating again after our run ended.

**Comment by SnackSBR** [comment]
[MoreShipUpgrades.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14748592/MoreShipUpgrades.zip)

Can you try again with this dll? Also report you logs from 
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/4934886/71471100-3fcb-428f-8dad-ecdf984ed48b)

**Comment by stepeche** [comment]
I have copies of both my log and my friend's log with the issues we are facing, where is the best place for me to add these? They are quite long so I didn't want to put too much info into the comments.

**Comment by WhiteSpike** [comment]
Closing as it seems to been fixed past 3.5.x release.
However, if I'm wrong, make another issue with logs from both host and clients.
