### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by ReshiStar** [Malcolm-Q/LC-LateGameUpgrades#41]
Version in use: V2.6.1
Game version: V45
First issue: Peeper malfunction/Audio glitching
The item Peeper, when placed anywhere on the map, can be heard as if it was being placed right next to you, regardless who placed it and where they placed it. This was done in multiplayer, I was the host, 4 players in lobby.

Second issue: Peeper audio malfunction
The Peeper when placed, creates an ear piercing turret scanning sound that repeats at a very rapid frequency, consistency on this varied, as I never experienced it but various players in my lobby did, some had to rejoin for the issue to fix, and other players would start to experience this. Audio would not glitch out if it was just being held, but reportedly this could be heard from anywhere on a map.

Third issue: Beekeeper Upgrades not working
I've set the values to be so that max upgrade would result in bees dealing 0% of their base damage, however this resulted in bees still doing damage, and at a more rapid frequency. Further testing I upgraded it to be that bees dealt -140% their base damage, and they still dealt the same amount of damage. 
Current configs are as follows;
Enable Beekeeper Upgrade: True
Price of Beekeeper Upgrade: 450
Multiplied to incoming damage (rounded to int): 0.6
Price of each additional upgrade: 225,280,340,400,450
Individual Purchase: False
Additional % Reduced per level: 0.4

Prior to recent updates and tested in solo multiplayer; this originally made it so bees dealt no damage at all.

**Comment by ReshiStar** [comment]
Small update to the beekeeper bug;
On further testing, itll work just fine until i reload the game/server, in which the upgrade will remain but the effect will not, resulting in me taking damage

**Comment by Malcolm-Q** [comment]
All should be fixed and will be included in next update, thank you for the help.
