### ISSUE TITLE
Probing moons can cause you to reach negative numbers

### ISSUE THREAD

**Issue by TechTonic02** [Malcolm-Q/LC-LateGameUpgrades#413]
The "**Probe moon**" upgrade can cause you to reach negative numbers and still be used causing you to reach unseen levels of debt
![Screenshot (12)](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/165220879/f628f376-9ae2-4022-9755-046f3d36aafd)
![Screenshot (13)](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/165220879/846375c6-7079-42f2-8112-a91d527e94f0)

**Comment by WhiteSpike** [comment]
Forgot to add the check for enough money. Will fix soon.

**Comment by WhiteSpike** [comment]
Should be [fixed](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/415) and live in next release.
