### ISSUE TITLE
More ship upgrades not loading

### ISSUE THREAD

**Issue by Gohan-Le-Goat** [Malcolm-Q/LC-LateGameUpgrades#417]
When I load a game and go the computer, the "lgu", "lategame" and "lategame store" commands won't work. 
While reading the terminal, i noticed this part was red.

```
[Error  : Unity Log] MissingMethodException: Method not found: void CSync.Lib.SyncedInstance`1.add_SyncComplete(System.EventHandler)
Stack trace:
MoreShipUpgrades.Plugin.Awake () (at <4da35b0453aa4c4b99265d13486c8852>:IL_0007)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

```
This led me to believe the mod just doesn't load. Using LethalConfig with another modpack, it couldn't detect Lategame upgrades but the terminal would give me the same output.
Here is my log output:
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14826199/LogOutput.log)

My mod list (with a clean reinstall/deletion of previous files):

- BebInExPack v5.4.2100
- HookGenPatcher v0.0.5
- Csync v4.0.2
- LethalLib v0.15.0
- Lategame_Upgrades v3.4.4

**Comment by NighteyezWolf** [comment]
Same here.

[Error  : Unity Log] MissingMethodException: Method not found: void CSync.Lib.SyncedInstance`1.add_SyncComplete(System.EventHandler)
Stack trace:
MoreShipUpgrades.Plugin.Awake () (at <4da35b0453aa4c4b99265d13486c8852>:IL_0007)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by Kayden21** [comment]
yeah it just straight up does not exist after updating

**Comment by MetroidCatcher** [comment]
Same here, just created a profile to check again, it's like not existing.

Same error in the LogOutput.log

**Comment by McGodMan** [comment]
Had the same issue, seems like CSync updating to V4.0.0 broke LGU, downgrading CSycn to V3.1.1 fixes the issue.

[My log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14827390/LogOutput.log)

Hopefully a fix is found soon, in the meantime downgrade CSycn and refrain from updating until LGU updates to account for CSync's update.

**Comment by Toonmomo** [comment]
Csync update V4.0.2 breaks LGU, gotta keep it to 3.1.1

**Comment by rjhoppe** [comment]
3.1.1 fixed, much appreciated
