### ISSUE TITLE
nee my bru

### ISSUE THREAD

**Issue by zabbazebra** [Malcolm-Q/LC-LateGameUpgrades#423]
nee my bru

dis hierdie mod breaks my fokin speletjie.

what the poes? is jy dom?

nis nie good nie

**Comment by WhiteSpike** [comment]
> no my bro
Ok.

> this mod breaks my fokin game.
How do you know that? Do you have any logs where it proves that this mod breaks your game?

> what the cat? are you stupid
Last I checked, no. And nobody else in the development department as perfection is an impossibility.

> not good
Cool.

**Comment by remiX-** [comment]
There seems to be an issue with LethalLib preventing enemy spawns. It's known as part of this list https://docs.google.com/spreadsheets/d/1c9rZIyxcOS7ZYjfyBsjFaYKWkbozkOVZJ1wDk2yE3Tc/edit#gid=0

Otherwise LGU is working fine ;-)

@zabbazebra fokof go have a braai

**Comment by zabbazebra** [comment]
NEE! JULLE FOK!

EK IS NIE GELUKKIG NIE!

**Comment by WhiteSpike** [comment]
Closing this issue due to lack of information to help improve this mod so it can satisfy as many people as possible without jeopardizing others.

**Comment by zabbazebra** [comment]
NEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by zabbazebra** [comment]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/157727110/7de23b91-3b02-4718-aa20-8c0304c39a1d)

**Comment by WhiteSpike** [comment]
Is this with the 3.5.3 release?
If yes, post me the full log file.
Otherwise, use that and see if the issue persists.

**Comment by WhiteSpike** [comment]
Closing due to lack of response so assuming it's working as expected.
