### ISSUE TITLE
Not Compatible with Too Many Emotes Store

### ISSUE THREAD

**Issue by canadia-1** [Malcolm-Q/LC-LateGameUpgrades#428]
Normally, by typing "emotes" into the terminal, you can bring up the too many emotes store. With this mod enabled, you cannot open the store, and it provides a "there was no action supplied with the word." By disabling this mod, the emote store works properly. Not a critical thing to fix, just annoying :(

**Comment by WhiteSpike** [comment]
Can you provide logs of when this happens to understand what I need to change.

**Comment by remiX-** [comment]
> Normally, by typing "emotes" into the terminal, you can bring up the too many emotes store. With this mod enabled, you cannot open the store, and it provides a "there was no action supplied with the word." By disabling this mod, the emote store works properly. Not a critical thing to fix, just annoying :(

We use LGU + TooManyEmotes, works perfectly fine.

Any possible chance it's not LGU but maybe something else that conflicts with LGU somehow?

**Comment by WhiteSpike** [comment]
Closing due to lack of response so assuming that either this mod is not the cause of the issue or it got resolved already.
