### ISSUE TITLE
Discombobulator info glitch

### ISSUE THREAD

**Issue by EnduringGuerila** [Malcolm-Q/LC-LateGameUpgrades#43]
I think the images will be pretty self explanatory. 
When doing 'info' on the discombobulator, the first entry shows 40 seconds instead of 7.5 or whatever it's set to.

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/2485608/82b718f5-805c-408e-8151-096a9f204937)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/2485608/cff6f153-c8fe-4d8a-a81e-3e9cd9f39aea)

**Comment by Malcolm-Q** [comment]
Whoops, I'll put that in next update thanks.
