### ISSUE TITLE
Error when joining the game

### ISSUE THREAD

**Issue by DonV06** [Malcolm-Q/LC-LateGameUpgrades#433]
Hello.

When joining a game as a client, result is that.
![20240413204845_1](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/77447076/6582edef-7782-4a87-bd6c-34ce10d2d000)

Player which hosts the game is fine everything works.

I tested that on LAN but online has the same problem.

[LogOutputClient.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14968377/LogOutputClient.log)

[LogOutputServer.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14968378/LogOutputServer.log)

**Comment by WhiteSpike** [comment]
Install all CSync dependencies correctly (I don't see any mention of [FixPluginTypesSerialization](https://thunderstore.io/c/lethal-company/p/Evaisa/FixPluginTypesSerialization/) in the logs, meaning that it's not installed and CSync will not work as expected.)

**Comment by DonV06** [comment]
Thank you, that helped.
