### ISSUE TITLE
Upgrade sales reset on save reload

### ISSUE THREAD

**Issue by ZachHaber** [Malcolm-Q/LC-LateGameUpgrades#439]
I have a save file where every time I load the save, the LGU store resets the sales to what they were at 

Attached is 2 saves from my current game - One is from day 9, the other at day 14. I've had the same sales show up every time I re-host the game.

Even after the sales change, if I load the save file, the sales seem to reset back to "Bargain - 19%", "Climbing - 32%", "Efficient - 17%", "Sick Beats - 37%". (While double checking things, one time the save loaded with no sales at all - I exited and re-hosted the save and it went back to the same sales).

[LCSaveFiles.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14986564/LCSaveFiles.zip)
Profile: 018ee506-a3f3-16fc-cb09-a47631f42e61

**Comment by WhiteSpike** [comment]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/58040140/4efa94c0-1709-41f0-9faa-df688b81e6a3)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/58040140/082c4266-3101-4d07-9949-82958447f29d)

The sales seem to differ between the saves.
So you're saying that you're seeing exactly the same sales on both saves?

**Comment by ZachHaber** [comment]
The first screenshot is what I saw before I stopped playing. The second is what I saw after I hosted the save file again. - we restarted the server multiple times while actively playing, and each time it reset to those sales.

Today, I started up the files, and now neither of the files show any sales in the LGU store.

**Comment by WhiteSpike** [comment]
The sales not loading's probably due the implementation's amount of tries of acquiring what it needs to sync up the saves not sufficient and loads it under a default value.

And the sales only change after a quota is met. (I cannot tell from the saves alone this fact happened)

So either three things are happening with the sales:
- Sales are not being generated every time a quota is met. (Means that [GenerateSales](https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/main/MoreShipUpgrades/Managers/LGUStore.cs#L494) is either failing or not being called)
- Sales are not being saved after being generated (Means that [ServerSaveFile](https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/main/MoreShipUpgrades/Managers/LGUStore.cs#L117) is either failing or not being called)
- Sales are not being loaded when rebooting from a game (Means that [LoadSales](https://github.com/Malcolm-Q/LC-LateGameUpgrades/blob/main/MoreShipUpgrades/Managers/UpgradeBus.cs#L128) is either failing or not being called)

So I would need you (if possible obviously, otherwise it would be after I'm done with my stuff to start testing this again) to try do the steps of generating the sales, leave and come back and see the results. After this, post the logs of this session so that I can have a look at what's going on.

**Comment by ZachHaber** [comment]
Okay, the bug re-triggered this time. The days I'm tallying here might not be the correct numbers. But this time it actually loaded the first time with the sales in the LGU that didn't load this morning when I responded. This is the LCSaveFile2 from the first zip folder but landing on experimentation 3 times and then reaching the quota.

Day 10: Sales changed (LGU didn't) - Walkie 30% => radar-booster 20%
Day 11: Sales changed (LGU no) - Walkie 20%/extension 50%/radar 50%/spray-paint 10%
Day 12 (After quota ended): Sales unchanged - LGU changed: Better Scanner 16%/Locksmith 27%/Protein 12%/ Sick Beats 33%

Day 12: after loading: Bargain 19%/ Climbing 32%/ Efficient 17%/ Sick Beats 37%

Lines 1287-1290 show the initial sales loaded
```log
[Info   :More Ship Upgrades] [LguStore] Loading SteamID: 76561198041076472
[Info   :More Ship Upgrades] [LguStore] Successfully loaded save data for ID: 76561198041076472
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.8088145 for Bargain Connections.
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.6842617 for Climbing Gloves.
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.8285989 for Efficient Engines.
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.6277798 for Sick Beats.
```
Lines 4063-4130 in the log shows the new LGU sales, then after I quit and re-loaded the same file, 
<details>
<summary>4063-4130</summary>

```log
[Info   :More Ship Upgrades] [LguStore] Generating sales with seed: 259081 on this client...
[Info   :More Ship Upgrades] [LguStore] Set sale percentage to: 0.6710415 for Aluminium Coils.
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Set sale percentage to: 0.7355092 for Fast Encryption.
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198041076472
[Info   :GeneralImprovements] Applying surplus quota to fulfilled: $1798
[Info   :More Ship Upgrades] [LguStore] Generating sales with seed: 905470 on this client...
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Set sale percentage to: 0.843331 for Better Scanner.
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Set sale percentage to: 0.7315573 for Locksmith.
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Set sale percentage to: 0.8811426 for Protein Powder.
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Set sale percentage to: 0.6675756 for Sick Beats.
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Saving node into save
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198041076472
```
</details>
lines 5012-5017 show the sales loaded are the ones that existed when I first loaded the save!

```log
[Info   :More Ship Upgrades] [LguStore] Loading SteamID: 76561198041076472
[Info   :More Ship Upgrades] [LguStore] Successfully loaded save data for ID: 76561198041076472
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.8088145 for Bargain Connections.
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.6842617 for Climbing Gloves.
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.8285989 for Efficient Engines.
[Info   :More Ship Upgrades] [UpgradeBus] Loaded sale of 0.6277798 for Sick Beats.
[Info   :More Ship Upgrades] [LguStore] Applying loaded upgrades...
```

[LGU Save issues.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/15004951/LGU.Save.issues.zip)

**Comment by ZachHaber** [comment]
In addition, just to double check on loading straight from game-load: The log shows that the sales loaded (the old ones, not what it should be here - this is the Day 12 file after the quota), but the UI shows no sales at all when I go to the LGU store (and the base store sales don't exist either).
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/19843782/1c97dcce-1384-476b-9f2a-623c4cf9b17e)
[bepinex.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/15005071/bepinex.log)

Hope this helps you figure out what's going wrong!
