### ISSUE TITLE
Malware broadcaster possible bug?

### ISSUE THREAD

**Issue by CroSSinski** [Malcolm-Q/LC-LateGameUpgrades#44]
Looks like only me (host) can destroying turrets and landmines but friend cant.

What we tried;
- load lgu through console in game
- i tried change config both personal nad new options misc
- i tried set disable time to 300sec, not working even for me

**Comment by DillyTheDillster** [comment]
i just tested it with 2 players, all default settings allows non host to explode the turrets and land mines, you might have an incompatible mod somewhere

**Comment by CroSSinski** [comment]
mods in my pack: [screen1](https://i.imgur.com/OXVO9x8.png) , [screen2](https://i.imgur.com/umLVgqp.png) , [screen3](https://i.imgur.com/TEUtLnm.png) and [screen4](https://i.imgur.com/DT2AksW.png)

i forgot to mention i only test it with a player who joins late (after few rounds) that may be a case. I usually play in big groups of 8-10 players and rotate in players is very often.

**Comment by Malcolm-Q** [comment]
If they don't have the upgrade unlocked they won't be able to use the upgrade yeah.

**Comment by CroSSinski** [comment]
> If they don't have the upgrade unlocked they won't be able to use the upgrade yeah.

so it means all players need to be when game starts, players who joins later will not get upgrade yeah?

**Comment by Malcolm-Q** [comment]
Yeah if you type `load lgu Player` instead of load lgu username that should work. However in next update if the config option that converts all upgrades to be shared is true it will automatically do this on join.

**Comment by CroSSinski** [comment]
PERFECT!
