### ISSUE TITLE
Please fix the Diving kit being off centered.. it is driving me crazy

### ISSUE THREAD

**Issue by Kablumbaa** [Malcolm-Q/LC-LateGameUpgrades#444]
I am playing with the mod called OopsAllFlooded which makes the interior fill up with water when the weather is flooded. I am using the diving kit helmet to navigate the flooded parts of the interior, which is very challenging and fun. BUT the window on the diving kit is off centered and is far away from the camera which makes it really hard to see. I don't know if it is tied to the FOV but i am playing with the vanilla FOV anyways. Would really appreciate if it is fixed. GREAT mod btw, thanks.

**Comment by WhiteSpike** [comment]
Right now, the mechanism used to block your vision as to simulate using a diving helmet is literally using the model to block your view.

There are [suggestions](https://github.com/Malcolm-Q/LC-LateGameUpgrades/discussions/321) in making it better in that regard that I can consider but that right now I do not have the time to do them.

Just a heads up that a change is considered for the diving kit at some point in the future..
