### ISSUE TITLE
Hacking Tool Feature

### ISSUE THREAD

**Issue by Niconoko** [Malcolm-Q/LC-LateGameUpgrades#45]
Could we add one more feature after done hacking to explode only or to disable only? Like when we done with the math set the tool will ask again to put 0 or 1 as to explode or disable? Thx in Adv. :3

**Comment by Malcolm-Q** [comment]
Hi I think you have my mod confused with lethal things. That mod introduces a hacking handheld item that makes you do math to hack things.
