### ISSUE TITLE
Upgrade preservation problem

### ISSUE THREAD

**Issue by LucasGre17** [Malcolm-Q/LC-LateGameUpgrades#455]
In version 3.6.2 of the mod, there is a problem regarding the retention of upgrades in multiplayer. The bug occurs when one of the crew members leaves the game and then returns, they lose the upgrades displayed in the "lgu".
Another example, if the host closes the game and reopens it, he will see the upgrades in the "lgu" but not the other players.

**Comment by WhiteSpike** [comment]
That's because upgrades are only saved on vanilla's autosave.
So if someone leaves and comes back, they will use the save that is currently in disk, not what is stored in your current managers.

**Comment by LucasGre17** [comment]
Okay, but what I don't understand is that I already played your mod in 3.0.x and there was no problem with the progress of the upgrades. As a non-host player, even with a disconnection, I kept the upgrades.
