### ISSUE TITLE
Failing to go company

### ISSUE THREAD

**Issue by vecasvcc** [Malcolm-Q/LC-LateGameUpgrades#459]
When I go to the terminal, and write "com(or full name)" but the ship didn't do orbit correction to the company.
I don't know why;;. If you know  how to fix it, plz tell me.
Thank you for read my saying ^^ (I'm korean so...grammer is not good. sry)

**Comment by WhiteSpike** [comment]
I heard that LLL (LethalLevelLoader) causes that. 
You can use some mods to work around it such as [Terminal Formatter](https://thunderstore.io/c/lethal-company/p/mrov/TerminalFormatter/) or [AutoCompanyBuilding](https://thunderstore.io/c/lethal-company/p/La_chips/AutoCompanyBuilding/)
