### ISSUE TITLE
[Nitpick] Charging Booster level starts at lvl 0 instead of lvl 1

### ISSUE THREAD

**Issue by MathiusXII** [Malcolm-Q/LC-LateGameUpgrades#472]

**Comment by WhiteSpike** [comment]
That's because you only get the effect of charging an item through the radar booster on the first ever purchase of the upgrade. It doesn't unlock by default.

Unless I'm confused about this issue entails?

**Comment by MathiusXII** [comment]
I'm saying the first ever purchase is lvl 0 instead of 1 like everything else.
