### ISSUE TITLE
Protein Powder not saving

### ISSUE THREAD

**Issue by CroSSinski** [Malcolm-Q/LC-LateGameUpgrades#48]
I bought PP lvl1 and lvl2 after few rounds i had to reset game and only PP from all upgrades was not saved and we had again lvl0

**Comment by WhiteSpike** [comment]
The issue is that the level of protein powder is saved not with the current Protein Powder's level but Beekeeper's.
Regardless, the authors/contributors are aware of the issue and they will fix whenever possible.
