### ISSUE TITLE
Cannot use lookup command despite having a defusal contract

### ISSUE THREAD

**Issue by DejviDxD** [Malcolm-Q/LC-LateGameUpgrades#483]
This has happened multiple times by now we have been playing a save with my friends and we had a defusal contract but there were cases where we found the bomb sent smb back to ship and after providing them with the serial nr. he couldn't get the wire order and it said something along the lines of can't use this command, you need to have a defusal contract.

**Comment by WhiteSpike** [comment]
If you use ``contract`` commands instead of the interactive ``contracts``, you will probably not have this issue.
