### ISSUE TITLE
running shoes dont work with latecompany or insanity remastered

### ISSUE THREAD

**Issue by rootbeer2222** [Malcolm-Q/LC-LateGameUpgrades#487]
any potential fix for this?

**Comment by WhiteSpike** [comment]
The only thing I can think of is not use the variable shared to everyone in the game and use only mine which then adds to the respective variable separately.

Problem with this implementation is that I need to find all occurences of the variable to be applied correctly.

**Comment by rootbeer2222** [comment]
> The only thing I can think of is not use the variable shared to everyone in the game and use only mine which then adds to the respective variable separately.
> 
> Problem with this implementation is that I need to find all occurences of the variable to be applied correctly.

even with shared to everyone off or on the issue is still happening, whats odd is the speed of the running shoes will be fine when in orbit but as soon as I land it goes away

**Comment by WhiteSpike** [comment]
Because again, the variable associated with the player's movement speed is changed to a set value rather than increments.

**Comment by rootbeer2222** [comment]
> Because again, the variable associated with the player's movement speed is changed to a set value rather than increments (by other mods).

oh I see, I know insanity remastered has a variable with movement but only during certain events and debuffs like slowness, I disabled the effect but the issue is still there so its deeper in the code where the players speed is associated with the sanity, how would I go around as to remove the variable causing this?

**Comment by WhiteSpike** [comment]
If it's not configurable by an user, I don't think it's possible. You will have to wait til either of us makes a decent implementation where it changes the variable's value regardless of what mods do to it.

**Comment by rootbeer2222** [comment]
> If it's not configurable by an user, I don't think it's possible. You will have to wait til either of us makes a decent implementation where it changes the variable's value regardless of what mods do to it.

I see alright, i'll just disable that upgrade for now to avoid the issue for the time being
