### ISSUE TITLE
Defuse contract bug

### ISSUE THREAD

**Issue by rootbeer2222** [Malcolm-Q/LC-LateGameUpgrades#491]
I select defuse contract, find the bomb, go to the terminal to do the lookup command only to be met with "you must be in a defuse contract to use this command"

**Comment by rootbeer2222** [comment]
I mean I get the defuse contract not select it

**Comment by WhiteSpike** [comment]
And this is from the new contract UI?

**Comment by rootbeer2222** [comment]
> And this is from the new contract UI?

I think? I have terminal formatter if that screws with it.

**Comment by WhiteSpike** [comment]
If you can provide logs of when you purchase a contract with other clients from both you and the other clients, I would appreciate it.

**Comment by rootbeer2222** [comment]
> If you can provide logs of when you purchase a contract with other clients from both you and the other clients, I would appreciate it.
> 
> Edit: Nevermind, I think I figured out the problem.

Hey sorry bout that. But I see you figured it out. Super appriciate it!
