### ISSUE TITLE
Back muscles dont work and instead store the weight in odd ways seemingly randomly

### ISSUE THREAD

**Issue by rootbeer2222** [Malcolm-Q/LC-LateGameUpgrades#492]
so after some gaming I noticed my weight was 8lb's even when carrying nothing, so I continued and after some time it went to 16lb's after carrying a cash register jetpack utility belt (from lethal things) and a pro flashlight.
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/168264445/4b528a5f-eeaa-4456-a162-9b675de99994)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/168264445/dfbf953b-a488-48d5-a7b8-b9979f17c3d9)
****

my logs look like this but its been doing this for a while and idk why every nano second its spamming this. if you'd like my mod list in a txt format here it is
[modlist.txt](https://github.com/user-attachments/files/15779563/modlist.txt)

also sorry I keep coming up with new issues lol.

**Comment by WhiteSpike** [comment]
If you can give the logs of when this happened and how are you doing it (as in what moment does it start giving you the non-existent weight to you), I can try giving it a look.

**Comment by rootbeer2222** [comment]
> If you can give the logs of when this happened and how are you doing it (as in what moment does it start giving you the non-existent weight to you), I can try giving it a look.

I will try when I get home but my log box looks like the screenshot above and it spams it every nano second so I can't really see any different logs with how fast it's spamming those same errors.

**Comment by WhiteSpike** [comment]
That's fine, I just need the file when it happens.

**Comment by rootbeer2222** [comment]
https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/168264445/e91c81ba-a3ed-447b-b333-19ab49e07470

idk how to get said file but I found out how to recreate it, when on a flat terrain close to where the first item drops such as something like a jetpack while having back muscles active you will instantly pick up the jetpack glitching the weight out and making it so im always 26 pounds and mind you this is with late game upgrades being the only mod enabled (with the dependencies)

**Comment by WhiteSpike** [comment]
The file is in the ``BepInEx`` folder. It generates one for each game session you have (as in having the game up)

**Comment by rootbeer2222** [comment]
[LogOutput.log](https://github.com/user-attachments/files/15796038/LogOutput.log)
here is the log output freshly made, some...weird stuff at the bottom

**Comment by Skyblade799** [comment]
Frustratingly, this also has been happening to me, but I can't get any consistent results at all and there are no errors. It happens every run eventually, and the items seem to permanently lose their weight. It started I think when I changed the weight upgrade to be split into smaller chunks, first 20%, then up by 10% for another 6 levels...

I'm going to try the "ReduceCarryInfluence" option and see if that makes the issue go away, or see if it still happens (as that would mean that it is something else).

**Comment by WhiteSpike** [comment]
I'm gonna close this as I can't seem to replicate this issue.

However, my best guess as to why this might happen is that some error is occuring in either grabbing an object or dropping it and weight wasn't updated in time before the error occured.

The patches related to Back Muscles seem to be correctly applied and the math seems correct so it's unlikely it's a math error from Back Muscles side.

**Comment by rootbeer2222** [comment]
> I'm gonna close this as I can't seem to replicate this issue.
> 
> However, my best guess as to why this might happen is that some error is occuring in either grabbing an object or dropping it and weight wasn't updated in time before the error occured.
> 
> The patches related to Back Muscles seem to be correctly applied and the math seems correct so it's unlikely it's a math error from Back Muscles side.

The updating weight might be what it is, because I get it but then as time goes on it corrects itself either when taking off or landing.
