### ISSUE TITLE
LogOutput spamming warning lag

### ISSUE THREAD

**Issue by YETI07HUN** [Malcolm-Q/LC-LateGameUpgrades#493]
When in terminal's upgrades (lgu) and I press something like up, down, left or right, then the log is spamming this and it will be like 0 fps:
[Warning: Unity Log] Unable to add the requested character to font asset [IBM 3270]'s atlas texture. Please make the texture [IBM 3270 Atlas] readable.
Before pressing any button:
![kép](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/146641041/a77617fc-79c2-474a-9bac-5429e3d89d26)
After pressing down for 3 seconds:
![kép](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/146641041/9cc8b585-e5ac-4b05-8e65-3b0f30c9e5b1)
Modpack's code: 01903700-bf74-58ba-cb96-519083906b14
[LogOutput.log](https://github.com/user-attachments/files/15919008/LogOutput.log)

**Comment by YETI07HUN** [comment]
I haven't been tried to redownload the mod yet.

**Comment by YETI07HUN** [comment]
I found the problem, it's my fault, the fontfixer mod was the problem.

**Comment by WhiteSpike** [comment]
Closing as author seemed to have found the fault.
