### ISSUE TITLE
(small issue) Extraction guy floating

### ISSUE THREAD

**Issue by rootbeer2222** [Malcolm-Q/LC-LateGameUpgrades#497]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/168264445/3f14fc7a-8669-45b3-beb0-7b94b960d762)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/168264445/b5bb267e-9d6b-45de-95cd-67a8c332299c)
he just floats, isnt game breaking, just odd and worth noting.

**Comment by WhiteSpike** [comment]
I can't seem to replicate this? I spawned them and they seemed to be in the correct y offset from the floor to not be floating. It could be something that is changing it at runtime, not sure.

**Comment by rootbeer2222** [comment]
> I can't seem to replicate this? I spawned them and they seemed to be in the correct y offset from the floor to not be floating. It could be something that is changing it at runtime, not sure.

Imma try again once home and see if I just got unlucky. It could also be vanilla content expansion which sometimes makes things float at that exact height for some reason

**Comment by rootbeer2222** [comment]
it uh, fixed itself lol, a few mods updated and once they did it got fixed idk which one was causing it

**Comment by WhiteSpike** [comment]
Closing as it seems the issue resolved itself.
