### ISSUE TITLE
(BUG) can't put things in wheelbarrow

### ISSUE THREAD

**Issue by TheComicRelief** [Malcolm-Q/LC-LateGameUpgrades#499]
I can't put anything in the wheelbarrow. It always says can't insert anymore item when there is none. here's my code: 0190689b-a3a9-c54f-dea0-cdcfcf6d62d8

**Comment by WhiteSpike** [comment]
Closing as fixed in 3.8.2 version.
If the issue still persists, feel free to reopen this.
