### ISSUE TITLE
Back Muscles causes permanent weight to be added in VR

### ISSUE THREAD

**Issue by TheMexicanWeeb** [Malcolm-Q/LC-LateGameUpgrades#503]
While having back muscles active in VR, all objects that are picked up still apply their normal weight. Dropping them results in the item removing the correct amount of weight as though back muscles worked.

With Back Muscles I:
Shovel adds 14 weight when picked up, but removes 7 when dropped.

[LogOutput.log](https://github.com/user-attachments/files/16121875/LogOutput.log)

**Comment by WhiteSpike** [comment]
VR has repeated code related to grabbing objects which doesn't take account Back Muscles.
Either:
- This mods patches the method related to VR which adds the Back Muscles interaction to their GrabItem function
- They make compatibility code with LGU where they take account Back Muscles in their GrabItem function.

**Comment by WhiteSpike** [comment]
Latest release should have this issue resolved.
