### ISSUE TITLE
Back muscles adding extra weight permanently(Non VR)

### ISSUE THREAD

**Issue by EliwsEverywhere** [Malcolm-Q/LC-LateGameUpgrades#504]
I see a related issue for this but in VR already reported. I also have this issue in non VR in which I will pick an item up and after dropping the item I still have the weight, this only happens after having at least 1 level of back muscles bought and doesn't happen without the upgrade. 

Edit: 
[LogOutput.log](https://github.com/user-attachments/files/16143705/LogOutput.log)
Log file uploaded. Fresh install with just LGU, Imperium and dependencies for both. Spawned 2 shotguns with no back muscles upgrade - weight adds and removes correctly. Bought L1 then L2 back muscles and spawned 2 shotguns each time, both times the weight is not being calculated properly or removed when item is dropped

**Comment by WhiteSpike** [comment]
I can't seem to replicate this issue.

Installs: LGU (and its dependants), HealthMetrics (for health testing), LethalDevMode (for debug testing) and Unity Explorer (for stat debugging)

Version of the game: v56

Version of the mod: 3.9.0

Steps:
- Boot up a game
- Toggle test room
- Spawn a shotgun
- Pick up shotgun (weight increases by 16lb)
- Drop shotgun (weight decreases by 16lb)
- Purchase Back Muscles upgrade with mode that allows altering the weight value once.
- Pick up Shotgun (weight increases by 8lb)
- Drop shotgun (weight decreases by 8lb)

**Comment by EliwsEverywhere** [comment]
I'm awful at putting data in writing so I've attached a screenshot of mod list and [this link](https://youtu.be/dAEnlpA3FTE) to a video of it in effect from the start of a game. Hopefully it's of some use.
![image_2024-07-09_163851759](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/175123248/a1bb699c-eba2-4741-815c-9de0f87079f1)

**Comment by EliwsEverywhere** [comment]
I am wrong. It is not the back muscles/lgu that is the issue. The effect seen in the video does only apply when spawning the item(s) using imperium. I did have this bug last night in a game with friends where we do not use imperium but many other mods so I cannot say if one of those mods caused the issue or lgu itself. Apologies for the waste of time for us both. Can close it there, thank you.
