### ISSUE TITLE
Buy not working

### ISSUE THREAD

**Issue by ahamboeck** [Malcolm-Q/LC-LateGameUpgrades#51]
Somehow when I try to type "Buy Locksmith" into the terminal inside the lategame store it is not working. Is it only for me or a general issue? I installed it with the r2modman.

**Comment by WhiteSpike** [comment]
You are meant to type the name of the perk only for items present in the ``lgu`` menu.
Examples:
``Locksmith``, ``Strong Legs``, ``Running Shoes``

Examples that won't work
``buy Locksmith``, ``purchase Locksmith``

New items that appear in the ``store`` menu can be bought through either name, ``buy`` or ``purchase`` as they are in fact an item.

**Comment by Malcolm-Q** [comment]
From the FAQ:

Why can I not buy the upgrades in lategame store?
- Enter the full name of the upgrade and the full name only (case insensitive).
- Ex: `beekeeper`
- If you enter `buy beekeeper` or `purchase beekeeper` it will not work.

**Comment by Malcolm-Q** [comment]
beat me to it @WhiteSpike
