### ISSUE TITLE
running shoes not appling when buying the upgrade

### ISSUE THREAD

**Issue by Drawntubers** [Malcolm-Q/LC-LateGameUpgrades#511]
so i checked any mods that changed how speed works but none of them was causing this bug

**Comment by WhiteSpike** [comment]
Just to be clear, what makes you think you are not having the upgrade's effect?
Are you losing it between moons?
Are they never applying when bought?
Can you also provide logs of a game session where you buy the upgrade, land on a moon and then come back to orbit, please? Thank you.

**Comment by Drawntubers** [comment]
ok so i disabled a mod called "JetpackFallFix" and then the bug was resolved.
sorry for bothering you

**Comment by Drawntubers** [comment]
so i disabled a mod called "jetpackfallfix" and then the bug was resolved
sorry for bothering you.

**Comment by WhiteSpike** [comment]
Closing as the author seemed to have fixed the described issue.
