### ISSUE TITLE
Can´t open the game with the latest lgu

### ISSUE THREAD

**Issue by FaithOfSin** [Malcolm-Q/LC-LateGameUpgrades#516]
LC V55
LGU v3.9.4
Thunderstore Mod Manager
Mod Pack: 0190b00d-005a-a09d-2b18-264724648614

I wanted to play my modpack today, there was an update for lgu, coroner and cull factory which I did. (the modpack worked 3 days ago).
Today I got the unity error window while starting. I started to deactivate one after another of those 3 and noticed that the error doesn´t occur if I deactivate lgu.

Here is the log with all mods active when the error happens: https://pastebin.com/Pc76SFkM
And here is the log with lgu only deactivated, this way the game works: https://pastebin.com/993xRWkT

I also tested deactivating coroner and cull factory and active lgu since those 2 also had an update, but the error doesn´t change. As soon as lgu is active it crashes while starting. The whole modpack without lgu works.
I also tested lgu only, so deactivated ALL mods and only activated lgu, which works.

I can´t find out in the logs what causes this, all I know is this modpack worked 3 days ago and now after the lgu update it doesn´t.

Thank you for your time and help, I really like your mod too!

**Comment by WhiteSpike** [comment]
Sounds like something is making the game deadlocking in the main thread, leading to the game having an unity crash window report.

Sadly, I can only look into this after my break (which should end on 29th)

**Comment by WhiteSpike** [comment]
Grabbed the code you provided and did not update any of the mods.
Started the game just fine, managed to get to the main menu.
Booted up a save, it loaded correctly.
Landed on a moon, no visible issues when landing or leaving.

So are you still having this issue or has it been magically resolved?

**Comment by FaithOfSin** [comment]
It seems to be solved now!
