### ISSUE TITLE
Efficient Engines not reducing cost of Planets

### ISSUE THREAD

**Issue by dee-rey** [Malcolm-Q/LC-LateGameUpgrades#518]
After purchasing level 1 of Efficient Engines and trying to route to Titan, the game tells me it'll cost 595 Credits to do so.
Then, after confirming while having 640 Credits in store, it refuses to route and instead shows that I now need 700 Credits (the original cost to route to Titan).

Using latest LGU version 3.9.4, along with latest dependencies.

![20240715124107_1](https://github.com/user-attachments/assets/66b8a8d7-b553-4209-a994-4d6efffc6d68)

**Comment by WhiteSpike** [comment]
Seems the price field has changed places and I'm patching the wrong field.

I can only have a look at this after my break (which should end on 29th this month)

**Comment by WhiteSpike** [comment]
Yeah, the discount is being applied to the company cruiser instead of the moon routing. Oops.

I should be able to find a workaround to resolve this.
