### ISSUE TITLE
"Resetting the Upgrade Bus due to disconnecting" but Never disconnects the player, locking them into the game.

### ISSUE THREAD

**Issue by VanillaChan6571** [Malcolm-Q/LC-LateGameUpgrades#519]
After playing some games, it seems that LGU unable to correctly disconnect the player.

Players need to Alt + F4 to exit the game since returning to the main menu doesn't work as never executes the disconnect function.

Log File: 
[LogOutput.log](https://github.com/user-attachments/files/16335621/LogOutput.log)
Config: 
[com.malco.lethalcompany.moreshipupgrades.txt](https://github.com/user-attachments/files/16335636/com.malco.lethalcompany.moreshipupgrades.txt)
(Appears GitHub does not support .cfg for whatever reason)

If this is not an LGU error then I have no idea since LGU seems to respond to the player hitting confirm to go back to main menu but it seems to not completely allow it.

**Comment by WhiteSpike** [comment]
I believe that it isn't this mod that's being stuck in a loop causing the main thread to lock itself and making the game seem like frozen. Otherwise the logs related with skin walker and plugin serialization wouldn't have appeared.

**Comment by WhiteSpike** [comment]
Closing due to lack of response for some time. 

LGU doesn't mess with the disconnect mechanism besides using it to also reset everything LGU related. It seems that something has made the vanilla behaviour of disconnecting just stop working altogether.
