### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Valoneu** [Malcolm-Q/LC-LateGameUpgrades#52]
sometimes when we all die we dont get the upgrades on next map and sometimes when we buy upgrades we dont get them instantly

**Comment by WhiteSpike** [comment]
**inhales**

- Are you only using this mod (and respective dependencies)?
- Is it always the same upgrades or always different ones?
- When you mean "all die", you mean the game over scene or dying on a moon?
- You do not get a notification when buying said upgrades?

**exhales**

**Comment by EnduringGuerila** [comment]
I am also having issues not getting the upgrades we buy. upgrades were working fine on 2.6.1, 2.6.5 seems to be the issue. I only added one mod since then, which was nameplateTweeks. The other 18 mods are the same from when we played 2 days ago on 2.6.1

**Comment by EnduringGuerila** [comment]
update, I disabled nameplateTweeks and had my friend host and problem solved...
so, things that might help: 
2 of the 4 players quit, 
I was the original host and 
I was the only one that had NameplateTweeks installed
It was an 'old' save where we had failed to meet quote 2 days ago on 2.6.1. So fresh start but had bestiary entries.

**Comment by Malcolm-Q** [comment]
Thanks for the info. Are you using bigger lobby or more company?

If seemingly nothing changed and it broke my best guess is the lobby just instantiated incorrectly and netcode was broken.

**Comment by Valoneu** [comment]
ill look when im home at what mods do i use BUT i remember we got no notification and i was not game over we just all died

**Comment by EnduringGuerila** [comment]
Yes, we were using More Company. Haven't gone back to test me hosting yet

**Comment by Valoneu** [comment]
im not using more company or any other mod for bigger lobby

**Comment by Malcolm-Q** [comment]
Another user provided more info and I made some tweaks to the loading and target in 2.7.1
I think your issues should be fixed as well.

**Comment by Valoneu** [comment]
doesent get fixed

**Comment by Valoneu** [comment]
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/60077591/9cbbf283-e27e-40e1-bcb4-bbb90f5c8ab8)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/60077591/ed9ee969-586c-4276-9d71-3111151cc34a)
![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/60077591/52e32e63-a71c-4fec-9d76-98819c865906)
i have these mods

**Comment by Malcolm-Q** [comment]
What version of the game are you on

**Comment by Valoneu** [comment]
v45

**Comment by Valoneu** [comment]
so?

**Comment by Malcolm-Q** [comment]
I'm not sure. You're the only person I've seen with this issue. Everyone you're playing with has this mod and the other mods installed right? Family is visiting and sleeping in my office so I don't really have opportunity to look into this.

I'm genuinely not sure what could be causing it to have this serious of issues, it's a lot of mods but I've seen people use more and have it be fine.

**Comment by Valoneu** [comment]
:(, i mean happends to all of us and we all have the same mods installed

**Comment by Valoneu** [comment]
idk if it helps but we have the sharing turned ON
