### ISSUE TITLE
What happened to "Extend Deadline"?

### ISSUE THREAD

**Issue by FlabbiestSeven** [Malcolm-Q/LC-LateGameUpgrades#523]
In previous versions of this mod, you could type in "extend deadline" and then you could extend the quota deadline by however many days you wanted or could afford. I read the recent changelog and it mentions that Extend Deadline has been separated into it's own mod, but looking at the creators page, I couldn't find it. Can anyone help with this? I just want to be able to extend the deadline again.

**Comment by WhiteSpike** [comment]
It's under WhiteSpike's name, not malco's. That way you should be able to find it.
