### ISSUE TITLE
Does "Hunter" support Kidnapper Fox and Spore Lizard?

### ISSUE THREAD

**Issue by ajsglist** [Malcolm-Q/LC-LateGameUpgrades#526]
Hey there,

Sorry if I missed a resource for this -- I checked the wiki (which seems to be focused on the API end of Hunter) and tried all of the variations I could think of (internal monster name, display name, and variations).  Whatever I try for Spore Lizards (puffers) and Kidnapper Fox (bushfox/fox) don't seem to work.  Are either of these currently supported with the Hunter upgrade?

Thanks :)

**Comment by WhiteSpike** [comment]
Fox and Puffer don't have a item dedicated for it. I will do one when I have free time.

**Comment by ajsglist** [comment]
That was... incredibly fast.

Thanks a lot :D

**Comment by ajsglist** [comment]
just a heads up, the scan node for the Fox sample says Tulip Snake

![image](https://github.com/user-attachments/assets/51cf8e39-42ce-4647-b1ee-005d153725b7)

**Comment by WhiteSpike** [comment]
And the other probably also has the wrong name, lol.

**Comment by WhiteSpike** [comment]
Latest version should have this issue fixed btw.
