### ISSUE TITLE
If you try to buy "Old Medkit" it opens the Old Bird Description

### ISSUE THREAD

**Issue by Chiller-Dirk** [Malcolm-Q/LC-LateGameUpgrades#528]
Like the title says, if you try to buy the"Old Medkit" it opens the Description for the Old Bird.

**Comment by WhiteSpike** [comment]
Vanilla issue of not being able to handle multiple same keywords.

TerminalConflictFix should fix that issue.

**Comment by Chiller-Dirk** [comment]
Thank you i give it a try.

**Comment by WhiteSpike** [comment]
I changed the name to "Medic Bag", shouldn't be an issue anymore.
