### ISSUE TITLE
Exorcizm Contract: Pentagram spawns below the jumps

### ISSUE THREAD

**Issue by YETI07HUN** [Malcolm-Q/LC-LateGameUpgrades#533]
Here a picture:
![image](https://github.com/user-attachments/assets/135fa4ff-e38a-4878-aa7e-59fa435d3647)

**Comment by WhiteSpike** [comment]
Known issue with vanilla spawn scrap behaviour. I don't know if there's any other method of spawning that consistenly puts the item in a player-acessible area.

**Comment by YETI07HUN** [comment]
Also the bomb contract, but thx for responding.

**Comment by YETI07HUN** [comment]
I think I will disable the "Spawn main object far away" option, because that worked once.
Also, can you tell me, how can we identify a demon in an exorcizm contract @WhiteSpike?

**Comment by YETI07HUN** [comment]
okay thank you, I'm just very silly because I thought wraith is write so I was confused.
