### ISSUE TITLE
Butlers can't slow down nearby players, when the Fedora Suit is active.

### ISSUE THREAD

**Issue by YETI07HUN** [Malcolm-Q/LC-LateGameUpgrades#534]
Sorry for my bad english.

When I'm alone with a butler, he doesn't slowing down to sweep the floor.
I know that if the butler doesn't have any target, then he will go much faster to find one.

In this video he shows us from 1:06 to 1:24 what does the butler do if he has no target.
https://www.youtube.com/watch?v=hmPD0j_urVE&t=66s

**Comment by WhiteSpike** [comment]
You still get targetted. They just can't go into attack mode if you have the upgrade.

**Comment by YETI07HUN** [comment]
And can you do that, if the upgrade is active, then the butlers will be only sweeping or something?
