### ISSUE TITLE
 Malware Broadcaster not destroying turrets, mines, or spike traps

### ISSUE THREAD

**Issue by goose-soop** [Malcolm-Q/LC-LateGameUpgrades#540]
I've noticed malware broadcaster doesn't destroy anything, or make anything able to be disabled. I tried to disable something from terminal, it out puts a response as disabled, but it doesn't show as disabled, or destroyed, and it stays intact when next to it. 

This is as of version 3.9.15 - 2024-08-19. Will update when I play the newest version.

**Comment by WhiteSpike** [comment]
I would have to look at logs to know what's going on when you try to use Malware Broadcaster.

**Comment by WhiteSpike** [comment]
Closing due to lack of response.
