### ISSUE TITLE
fix scrolling? & small things

### ISSUE THREAD

**Issue by Alyaqdhans** [Malcolm-Q/LC-LateGameUpgrades#543]
Is the problem on my end? or is it intended?

The lgu screen can be scrolled, but why?

![image](https://github.com/user-attachments/assets/57a698de-d2ad-4dbf-9ac4-7b57e9ff0300)

except when there is small info screen

![image](https://github.com/user-attachments/assets/ef0647e0-18ec-4528-9e9f-d469b1bcf0db)

**Comment by Alyaqdhans** [comment]
Also, a suggestion for the maxed upgrades, instead of greying them out like they're disabled lower the contrast a bit and replace the price with Maxed! or something similar.

**Comment by Alyaqdhans** [comment]
By the way, what button to change the sorting? it would be nicer if it were written beside the current sort as a small tooltip.

**Comment by Alyaqdhans** [comment]
What does "Item progression" do in the mod?

**Comment by WhiteSpike** [comment]
> The lgu screen can be scrolled, but why?
Vanilla terminal allows you to scroll.

> By the way, what button to change the sorting? it would be nicer if it were written beside the current sort as a small tooltip. (before the "Sorted by:" ex "[S] Sorted by:" just make it subtle)
You can change/check the control bindings in the settings.

> What does "Item progression" do in the mod?
Instead of using credits to purchase, you use scrap items depending on the mode you selected.

**Comment by Alyaqdhans** [comment]
I suspected that the Vanilla terminal was the cause of scrolling, but is it not possible to force it to be static?


What do you think about this?
> Also, a suggestion for the maxed upgrades, instead of greying them out like they're disabled lower the contrast a bit and replace the price with Maxed! or something similar.
> 
> As for the disabled upgrades, you can add an option "Show disabled upgrades" and default it to false, you can use the current maxed style (grey out the option) to show it's disabled.

**Comment by WhiteSpike** [comment]
> I suspected that the Vanilla terminal was the cause of scrolling, but is it not possible to force it to be static?

Probably but then I would have know big of the screen is to disallow/allow scrolling which sounds a headache to do.

> What do you think about this?

Sure when I have free time to mess with this.

**Comment by Alyaqdhans** [comment]
I don't think you need to worry about screen size, isn't this already managed by the game so the terminal fits correctly? Unless you're using some kind of custom way to display the upgrades info and it may break on different screens, but I still think it won't.
The only time the info needs scrolling is when there is too much info like bestiary or moons list/info.

**Comment by WhiteSpike** [comment]
> isn't this already managed by the game so the terminal fits correctly?

No, actually. It's the default behaviour of a typical text component when there are too many lines to fit on the screen.

**Comment by WhiteSpike** [comment]
Implemented the different coloring and text for maxed upgrades and the control binding used to show sorting, maybe this works for you, not sure.

The scrolling would be way too complex and very likely break other terminal mods if not thought correctly so I will leave in the future.

**Comment by Alyaqdhans** [comment]
Thank you for implementing them.

but why it looks like this? linda has a line
![image](https://github.com/user-attachments/assets/fd019f28-e5a2-4777-9218-1a2fb9152c1d)

also would you implement the "Show disabled upgrades" option? (default it to false in configs to not ruin existing ones)
![image](https://github.com/user-attachments/assets/fa3411f3-a68a-491d-8052-950e2b29d07e)

**Comment by Alyaqdhans** [comment]
If you will implement it, you can change the not enough credits color to dark blue or something different to not cause confusion.

**Comment by Alyaqdhans** [comment]
The strike through for the disabled upgrade isn't important, and I figured it out for the insufficient credit upgrades.
You can make just the price red, it will be very convenient and easy to get, and maybe the warning text inside each upgrade too.

As for the scrolling, you can take your time and if you want or not to add it, but keep in mind the upgrades info needs scrolling.

**Comment by WhiteSpike** [comment]
> but why it looks like this? linda has a line

It shows both PC and Controller Bindings.

> also would you implement the "Show disabled upgrades" option? (default it to false in configs to not ruin existing ones)

I don't understand the point of showing disabled upgrades if they will never do things.

> You can make just the price red, it will be very convenient and easy to get, and maybe the warning text inside each upgrade too.

The warning is already shown at the bottom after the info if you try to purchase it without credits.
So keep the green colouring except the price which would be red if not sufficient?

**Comment by Alyaqdhans** [comment]
Try and experiment, see if all the text red would look good or not, but I think the price only would be better, and color the warning with the same color to make it appear more.

Try to choose a bit pale red that is clear for the terminal background.

**Comment by Alyaqdhans** [comment]
> I don't understand the point of showing disabled upgrades if they will never do things.
The only reason you want to show the disabled upgrades is to show people that "These features exist, but they're disabled", and it's just like giving people different ways to customize the mod the way they like.

**Comment by Alyaqdhans** [comment]
I'm sorry, I really don't wanna be annoying with the details, but you should color the money icon the same as the price (when it's red), and the warning in red better, to differentiate it from the description text.
![image](https://github.com/user-attachments/assets/9e694f9f-06e5-4956-b435-cd95f1a912f9)
![image](https://github.com/user-attachments/assets/364d9c5a-05e1-4912-a63c-bea7c0d876df)

**Comment by WhiteSpike** [comment]
Closing as made most of the requested features while the ones not implemented wouldn't make the user experience any better as it's already near the prompts for selection and you were shown before that you couldn't afford the upgrade for the warning to appear.
Showing the disabled prompts doesn't make sense as they're defaulted on so you would have to know what they did to know you wanted them off.
