### ISSUE TITLE
Item Progression seemingly not working.

### ISSUE THREAD

**Issue by Xeyth** [Malcolm-Q/LC-LateGameUpgrades#544]
Using a debug modpack with just the [debug menu mod by Spike](https://thunderstore.io/c/lethal-company/p/Spike/Debug_menu/), and LateGame_Upgrades + Dependencies, I cannot seem to get Item Progression to work.

What I want to achieve is selling the Apparatus/Apparatice will give me various ship/electrical upgrades from LGU, while keeping other upgrades purchasable. In the modpack I want this in we have [facility meltdown](https://thunderstore.io/c/lethal-company/p/loaforc/FacilityMeltdown/), but even without it I can't seem to get it to work.

I have Item Progression set to true, Item Progression mode set to CustomScrap, Non-Purchasable Upgrades to false, and every relevant upgrade I want upgraded to have "Apparatice" in the Contribution Items slot. I have also tried Apparatus and Lung Apparatice/Apparatus, but none seem to give me the upgrade when selling to the company, or when taking off.

I've also tried other items like cash register or yield sign, but still no dice. Though I'm unsure if I'm supposed to include the space or not?

I also noticed ItemProperties.ItemName can be used in place of the scan node's name, but I have no idea how to get that information. No wiki I see contains anything related to that?

![image](https://github.com/user-attachments/assets/e0641ebe-f98c-4b9e-b422-52ec83340cf4)
![image](https://github.com/user-attachments/assets/8b30c41b-d835-4739-81f2-45858cbbeafc)
![image](https://github.com/user-attachments/assets/1370d760-ac4b-48b1-aed1-be38f139eb03)

**Comment by WhiteSpike** [comment]
If you try lower case, it will probably work.

**Comment by Xeyth** [comment]
Lowercase did work, unfortunately I'm now realizing I was mistaken in the wording of item progression mode. I thought selling a certain piece of scrap would automatically unlock the upgrade, not take the price off.

A little sad it doesn't work like that, but at least it partially got figured out. Thank you!
