### ISSUE TITLE
Landing Thrusters slow for clients functions normally for host

### ISSUE THREAD

**Issue by Matt577** [Malcolm-Q/LC-LateGameUpgrades#547]
This issue sounds similar to [Landing Thrusters Slows and Eventually Softlocks the Ship #515](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/515) but only for client. It will function normally for me but they will still be landing slower then normal. I tried hopping off and on the ship and they told me they me teleporting down to the ground then back on the ship. 

Now its seems even worse I noticed when I pull the lever the ship will land slow and even take back off into the sky **only for client** it will still be on the ground for me 
![Proof](https://github.com/user-attachments/assets/c9b08cc6-f605-43df-b0a0-b051a4690753)

It's some crazy desync and only started when we bought the upgrade I have their logs attached and if you need mine as well I can post as well 
[LogOutput.log](https://github.com/user-attachments/files/16859540/LogOutput.log)

I have also did have them delete their configs and having it regenerate it still did not fix the issue

**Comment by WhiteSpike** [comment]
Apparently the function I picked to patch is only called by host, leading to clients to not have the desired speed.

I will look at this better at later time.

**Comment by Matt577** [comment]
Would this also lead to the weird issue with the ship taking back off after landing as well. Like from the screenshot they both died from the ship "leaving" but was still on the ground for me

**Comment by WhiteSpike** [comment]
Since you have different speeds between each other, it's likely to cause desyncs in terms of landing/leaving.

**Comment by WhiteSpike** [comment]
Should be fixed in 3.10.2 release, will keep this open incase it's not.

**Comment by WhiteSpike** [comment]
Closing as it seems to be fixed.
