### ISSUE TITLE
Non host players buying upgrades doesn't use credits

### ISSUE THREAD

**Issue by blastman67** [Malcolm-Q/LC-LateGameUpgrades#548]
Seems to be a bug where if the host buys upgrades it works fine but if a non host player buys any upgrades it doesn't cost anything.

**Comment by WhiteSpike** [comment]
If you could post logs from both host and client whenever they are buying an upgrade, I would appreciate it.

**Comment by blastman67** [comment]
Log for the host:

[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Weed Genetic Manipulation increment: False
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Weed Genetic Manipulation increment: False
[Info   :More Ship Upgrades] [LguStore] First purchase, executing BaseUpgrade.load()
[Info   :More Ship Upgrades] [LguStore] Node found (Weed Genetic Manipulation) and unlocked (level = 0)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   : Unity Log] Setting animation on client
[Info   : Unity Log] Setting animation on client
[Info   : Unity Log] Setting animation on client
[Info   : Unity Log] Setting animation on client
[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Bargain Connections increment: False
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Bargain Connections increment: False
[Info   :More Ship Upgrades] [LguStore] First purchase, executing BaseUpgrade.load()
[Info   :More Ship Upgrades] [LguStore] Node found (Bargain Connections) and unlocked (level = 0)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   : Unity Log] clip index: 10; current planet: 41 Experimentation
[Info   : Unity Log] Current ship ambience clips length: 12
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Oxygen Canisters increment: False
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Oxygen Canisters increment: False
[Info   :More Ship Upgrades] [LguStore] First purchase, executing BaseUpgrade.load()
[Info   :More Ship Upgrades] [LguStore] Node found (Oxygen Canisters) and unlocked (level = 0)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Oxygen Canisters increment: True
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Oxygen Canisters increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Oxygen Canisters) and unlocked (level = 1)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Oxygen Canisters increment: True
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Oxygen Canisters increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Oxygen Canisters) and unlocked (level = 2)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Weed Genetic Manipulation increment: True
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Weed Genetic Manipulation increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Weed Genetic Manipulation) and unlocked (level = 1)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   :More Ship Upgrades] [LguStore] Received server request to handle shared upgrade for: Weed Genetic Manipulation increment: True
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Weed Genetic Manipulation increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Weed Genetic Manipulation) and unlocked (level = 2)
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 76561198352951390
[Info   :More Ship Upgrades] [LguStore] Received and updated save info for client: 0
[Info   : Unity Log] clip index: 2; current planet: 41 Experimentation
[Info   : Unity Log] Current ship ambience clips length: 12
[Info   : Unity Log] Setting animation on client
--------------------------------------------------------------------------------------------------------------------------------------------
Log for non host:

[Info   : Unity Log] Could not parse word: lgu
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :More Ship Upgrades] [LguStore] Bargain Connections is registered as a shared upgrade! Calling ServerRpc...
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Bargain Connections increment: False
[Info   :More Ship Upgrades] [LguStore] First purchase, executing BaseUpgrade.load()
[Info   :More Ship Upgrades] [LguStore] Node found (Bargain Connections) and unlocked (level = 0)
[Info   : Unity Log] clip index: 10; current planet: 41 Experimentation
[Info   : Unity Log] Current ship ambience clips length: 12
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :More Ship Upgrades] [LguStore] Oxygen Canisters is registered as a shared upgrade! Calling ServerRpc...
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Oxygen Canisters increment: False
[Info   :More Ship Upgrades] [LguStore] First purchase, executing BaseUpgrade.load()
[Info   :More Ship Upgrades] [LguStore] Node found (Oxygen Canisters) and unlocked (level = 0)
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :More Ship Upgrades] [LguStore] Oxygen Canisters is registered as a shared upgrade! Calling ServerRpc...
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Oxygen Canisters increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Oxygen Canisters) and unlocked (level = 1)
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :More Ship Upgrades] [LguStore] Oxygen Canisters is registered as a shared upgrade! Calling ServerRpc...
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Oxygen Canisters increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Oxygen Canisters) and unlocked (level = 2)
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :More Ship Upgrades] [LguStore] Weed Genetic Manipulation is registered as a shared upgrade! Calling ServerRpc...
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Weed Genetic Manipulation increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Weed Genetic Manipulation) and unlocked (level = 1)
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :More Ship Upgrades] [LguStore] Weed Genetic Manipulation is registered as a shared upgrade! Calling ServerRpc...
[Info   :More Ship Upgrades] [LguStore] Received client request to handle shared upgrade for: Weed Genetic Manipulation increment: True
[Info   :More Ship Upgrades] [LguStore] upgrade already unlocked, executing TierUpgrade.Increment()
[Info   :More Ship Upgrades] [LguStore] Node found (Weed Genetic Manipulation) and unlocked (level = 2)
[Info   : Unity Log] clip index: 2; current planet: 41 Experimentation
[Info   : Unity Log] Current ship ambience clips length: 12

**Comment by Skyblade799** [comment]
Can confirm this happens. Becomes an issue for individual player upgrades.

**Comment by WhiteSpike** [comment]
Should be fixed in 3.10.2 release, will keep this open incase it's not.

**Comment by WhiteSpike** [comment]
People confirmed it was fixed so closing.
