### ISSUE TITLE
"load lgu" command doesn't use steam name.

### ISSUE THREAD

**Issue by GoliathX211** [Malcolm-Q/LC-LateGameUpgrades#55]
Not sure if it is intentional, but when using the command it tells me the player doesn't exist or something similar and then lists the players
The players are all named Player, the host is "Player" and guests are something along the lines of "Player (1)" or another number.

Have not tested this with just Late Game Upgrades yet, but we have used the mod with a bunch of different mods and it seems to be the same across the board.

**Comment by Malcolm-Q** [comment]
This will be fixed next update

For now do load lgu player to load the host.
