### ISSUE TITLE
[Incorrect upgrade text] Sick Beats stamina regen listed incorrectly

### ISSUE THREAD

**Issue by ajsglist** [Malcolm-Q/LC-LateGameUpgrades#555]
Hey there,

Just a heads up that the LGU entry for Sick Beats seems to list the Stamina Regen buff incorrectly.  The value set in the config for the upgrade is a Stamina Regen multiplier.  But the LGU entry refers to it as a "Stamina Drain muliplier"

Cheers

![image](https://github.com/user-attachments/assets/033e5272-7c5f-4f4c-bd58-2f132ea5c19a)
![image](https://github.com/user-attachments/assets/0d211584-983d-4019-8313-791197d7d0df)

**Comment by ajsglist** [comment]
Oh, and a minor thing about text formatting as long as I'm here, since it never seemed important enough to report on its own.

The "Weed Genetic Manipulation" name (and maybe others) is longer than the allotted space in the LGU upgrade section.  Since there's a bunch of unused space to the right, maybe a few more characters could be allotted to the upgrade name?

Original
![image](https://github.com/user-attachments/assets/e93b21d4-1a69-4b53-b426-38c96de6fb74)

30s edit/mockup
![image](https://github.com/user-attachments/assets/07dd69cf-16c8-4d66-a3c1-ad6ba5465095)

**Comment by WhiteSpike** [comment]
The non used space is for sales.
I will take a look at the sick beats text when I have the time.

**Comment by WhiteSpike** [comment]
Implementation suggests it's meant to act only when regenerating. I can either make it work on both regeneration and consumption of stamina or just change the text to speak of regeneration.

**Comment by WhiteSpike** [comment]
Should be live in 3.10.4 release.
