### ISSUE TITLE
[BUG] can't drop items at all 3.10.6

### ISSUE THREAD

**Issue by TheMlgCat** [Malcolm-Q/LC-LateGameUpgrades#559]

**Comment by WhiteSpike** [comment]
If you post logs of when this happens, I will have a better time troubleshooting.

**Comment by TheMlgCat** [comment]
this is with 3.10.7 also, no drop persists. disabling lgu allows me to drop stuff again.
[LogOutput.log](https://github.com/user-attachments/files/17452753/LogOutput.log)

**Comment by WhiteSpike** [comment]
DramaMask seem to be stopping you from dropping items.

**Comment by TheMlgCat** [comment]
You have saved me.
