### ISSUE TITLE
[ IMPORTANT ] Read Before Posting Bugs / Issues

### ISSUE THREAD

**Issue by Malcolm-Q** [Malcolm-Q/LC-LateGameUpgrades#56]
### Bug Reports
- Create concise descriptive title
- Don't create duplicate issues
- include logoutput.log (it's in your bepinex folder)
- Include mod list
- Steps to reproduce / circumstance

**Comment by WhiteSpike** [comment]
Moved this to [Thunderstore's Wiki entry](https://thunderstore.io/c/lethal-company/p/malco/Lategame_Upgrades/wiki/1899-bug-reporting/)

**Comment by Wolfegamingllc** [comment]
Rocket Launcher unable to be purchased
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/15137333/LogOutput.log)
018f1e52-204a-9550-e980-745b66898f42 - modlist from Thunderstore (note: this is not the only modpack in which the rocket launcher could not be purchased from the terminal store. this is just the most recent pack I made to use with friends)

It appears that the rocket launcher has been somehow removed. The item shows in the store, but is unable to be purchased. It does not recognize the terminal command to buy, and after typing Store > Rocket Launcher (any quantity) and hitting Enter, it just sits there with the words Rocket Launcher still on the terminal. No error sounds from terminal or anything. I did not see anything about it in the Changelog, and have not been able to find any info on the web about it.

**Comment by AgravatedRex** [comment]
I been playing the Late comapny mod as a 4 man team. The constant problem is that the upgrades after game restart keeps only the host , everybody else loses the upgrades.  Maby its an  multiple mod problem i dont know. My dowloaded mods in thunderbird are 0194cd1a-3eeb-1146-97cf-25bf139429bd .  Mabye there is a fix ? Seems like few other people have the same problem.
