### ISSUE TITLE
Quantum Disruptor slow down is misleading

### ISSUE THREAD

**Issue by McAwesome123** [Malcolm-Q/LC-LateGameUpgrades#564]
The Quantum Disruptor says that it'll make time go 20% slower (by default) when bought.
However, it seems to just subtract this 20% from the time speed multiplier, which is 1.4 in the base game, meaning that it actually only makes time go about 14.286% slower and it needs to reach 140% to (almost?) completely stop time.

**Comment by WhiteSpike** [comment]
So just multiply with the value, doesn't seem hard enough.

**Comment by McAwesome123** [comment]
It's not hard, just unexpected.
Additionally, a user who hasn't looked in depth at the game's mechanics or how the mod works might not even know to do this.

**Comment by WhiteSpike** [comment]
3.10.9 will have the logic fixed but the UI will show the value times a hundred as I didn't have enough time to realize during upload so this issue will stay up.

**Comment by WhiteSpike** [comment]
3.10.10 release should address the messed up percentage value shown in the upgrade description.
