### ISSUE TITLE
Compatibility issue with ShipInventory

### ISSUE THREAD

**Issue by YETI07HUN** [Malcolm-Q/LC-LateGameUpgrades#565]
I think someone was reported this before, but who knows.

I put scrap in the ShipInventory and I have the full 100% Scrap Keeper upgrade.
When I die and the ship leaves, then the scrap will disappear from the ShipInventory.

**Comment by WhiteSpike** [comment]
From what I read, it's all or nothing in ShipInventory's when all players die and you don't have its config to make items in the chute safe. I don't think I have much maneveur besides considering the items in the chute as one singular item and make a roll for it to wether or not to remove it.

**Comment by YETI07HUN** [comment]
It's still better than nothing.

**Comment by WhiteSpike** [comment]
3.10.10 release should address this.
