### ISSUE TITLE
Night vision goggle settings in config file no longer working.

### ISSUE THREAD

**Issue by KeoughDarklance** [Malcolm-Q/LC-LateGameUpgrades#57]
After the last update the config settings for night  vision goggles no longer works. I have it set to 0.00 drain and 1.00 recharge (which gave infinite use) however now, no matter what I set it to, it drains still and recharges slowly. Beekeeper settings still work though, so it seems to be just the night vision settings that are ignored.

[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13724453/LogOutput.log)

**Comment by Malcolm-Q** [comment]
[LGU.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13732856/LGU.zip)
Yeah I just did a refactoring of night vision. There's a build if you want to switch it out.
