### ISSUE TITLE
I cannot access the LGU shop

### ISSUE THREAD

**Issue by adeyUnivaG** [Malcolm-Q/LC-LateGameUpgrades#577]
While in game, when I open up the terminal and type in "lgu" it says " [There was no action supplied with the word.] ". Typing "lategame store" takes me back to the info page. I have already tried to edit the mod itself as well as the dependencies with the mod to older versions to try and see if an update is causing the issue. I have also tried to run the mod by itself to see if it was conflicting with any other mods to no avail.

**Comment by WhiteSpike** [comment]
If you post logs of when you try to load the mod, I can help you better than guessing what is the problem you are experiencing that stops the mod from loading.

**Comment by adeyUnivaG** [comment]
My fault, here is the code.
`[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (11/1/2024 11:35:17 PM)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [FixPluginTypesSerialization 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.2.1.0]
[Info   :   BepInEx] 3 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Message:FixPluginTypesSerialization] Using the config cache
[Info   :FixPluginTypesSerialization] Running under Unity v2022.3.9
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 5 plugins to load
[Info   :   BepInEx] Loading [LethalLib 0.16.1]
[Info   : LethalLib] LethalLib loaded!!
[Info   :   BepInEx] Loading [CSync 5.0.1]
[Info   :     CSync] CSync successfully applied patches.
[Info   :   BepInEx] Loading [Lethal Company Input Utils 0.7.7]
[Info   :Lethal Company Input Utils] Registered InputUtilsExtendedMouse Layout Override!
[Info   :Lethal Company Input Utils] InputUtils 0.7.7 has finished loading!
[Info   :   BepInEx] Loading [Interactive Terminal API 1.2.0]
[Info   :Interactive Terminal API] Game managers have been patched
[Info   :Interactive Terminal API] Interactive Terminal API 1.2.0 has been loaded successfully.
[Info   :   BepInEx] Loading [More Ship Upgrades 3.10.11]
[Info   :More Ship Upgrades] Registed sample for the enemy "centipede"...
[Info   :More Ship Upgrades] Registed sample for the enemy "bunker spider"...
[Info   :More Ship Upgrades] Registed sample for the enemy "hoarding bug"...
[Info   :More Ship Upgrades] Registed sample for the enemy "flowerman"...
[Info   :More Ship Upgrades] Registed sample for the enemy "mouthdog"...
[Info   :More Ship Upgrades] Registed sample for the enemy "baboon hawk"...
[Info   :More Ship Upgrades] Registed sample for the enemy "crawler"...
[Info   :More Ship Upgrades] Registed sample for the enemy "forestgiant"...
[Info   :More Ship Upgrades] Registed sample for the enemy "manticoil"...
[Info   :More Ship Upgrades] Registed sample for the enemy "tulip snake"...
[Info   :More Ship Upgrades] Registed sample for the enemy "bush wolf"...
[Info   :More Ship Upgrades] Registed sample for the enemy "puffer"...
[Info   :More Ship Upgrades] Registed sample for the enemy "maneater"...
[Info   :More Ship Upgrades] Items have been setup
[Info   :More Ship Upgrades] Commands have been setup
[Info   :More Ship Upgrades] Upgrades have been setup
[Info   :More Ship Upgrades] Enemies have been patched
[Info   :More Ship Upgrades] HUD has been patched
[Info   :More Ship Upgrades] Interactables have been patched
[Info   :More Ship Upgrades] Items have been patched
[Error  :More Ship Upgrades] [Tools] Couldn't find second negative value representing no sales
[Error  :More Ship Upgrades] [Tools] Couldn't find second maximum amount of items to go on sale
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Not found
[Error  :More Ship Upgrades] [Tools] Couldn't find minimum sale percentage
[Error  :  HarmonyX] Failed to patch void Terminal::SetItemSales(): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
  at System.Collections.Generic.List`1[T].Insert (System.Int32 index, T item) [0x00009] in <787acc3c9a4c471ba7d971300105af24>:IL_0009
  at MoreShipUpgrades.Patches.TerminalComponents.TerminalPatcher.SetItemSalesTranspiler (System.Collections.Generic.IEnumerable`1[T] instructions) [0x00174] in <de7b1a1aae914eeb971ea7e6e6371b1e>:IL_0174
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <787acc3c9a4c471ba7d971300105af24>:IL_006A
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <787acc3c9a4c471ba7d971300105af24>:IL_0083
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <787acc3c9a4c471ba7d971300105af24>:IL_0000
  at HarmonyLib.Internal.Patching.ILManipulator.ApplyTranspilers (System.Reflection.Emit.ILGenerator il, System.Reflection.MethodBase original, System.Func`2[T,TResult] getLocal, System.Func`1[TResult] defineLabel) [0x00093] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_0093
  at HarmonyLib.Internal.Patching.ILManipulator.WriteTo (Mono.Cecil.Cil.MethodBody body, System.Reflection.MethodBase original) [0x00066] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_0066
  at HarmonyLib.Public.Patching.HarmonyManipulator.WriteTranspilers () [0x00084] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_0084
  at HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl () [0x0002b] in <474744d65d8e460fa08cd5fd82b5d65f>:IL_002B 
[Error  : Unity Log] ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].Insert (System.Int32 index, T item) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
MoreShipUpgrades.Patches.TerminalComponents.TerminalPatcher.SetItemSalesTranspiler (System.Collections.Generic.IEnumerable`1[T] instructions) (at <de7b1a1aae914eeb971ea7e6e6371b1e>:IL_0174)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:IL_006A)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:IL_0083)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
HarmonyLib.Internal.Patching.ILManipulator.ApplyTranspilers (System.Reflection.Emit.ILGenerator il, System.Reflection.MethodBase original, System.Func`2[T,TResult] getLocal, System.Func`1[TResult] defineLabel) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0093)
HarmonyLib.Internal.Patching.ILManipulator.WriteTo (Mono.Cecil.Cil.MethodBody body, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0066)
HarmonyLib.Public.Patching.HarmonyManipulator.WriteTranspilers () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0084)
HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_002B)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.HarmonyManipulator.WriteImpl () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0378)
HarmonyLib.Public.Patching.HarmonyManipulator.Process (MonoMod.Cil.ILContext ilContext, System.Reflection.MethodBase originalMethod) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0042)
HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo, MonoMod.Cil.ILContext ctx) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0006)
HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate (System.Reflection.MethodBase original, MonoMod.Cil.ILContext ctx) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0007)
HarmonyLib.Public.Patching.ManagedMethodPatcher.Manipulator (MonoMod.Cil.ILContext ctx) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0012)
MonoMod.Cil.ILContext.Invoke (MonoMod.Cil.ILContext+Manipulator manip) (at <6733e342b5b549bba815373898724469>:IL_0087)
MonoMod.RuntimeDetour.ILHook+Context.InvokeManipulator (Mono.Cecil.MethodDefinition def, MonoMod.Cil.ILContext+Manipulator cb) (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0012)
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?-650121464(object)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
MonoMod.RuntimeDetour.ILHook.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:IL_0059)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0047)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_005F)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0033)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0045)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0095)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0008)
MoreShipUpgrades.Managers.PatchManager.PatchVitalComponents () (at <de7b1a1aae914eeb971ea7e6e6371b1e>:IL_0094)
MoreShipUpgrades.Managers.PatchManager.PatchMainVersion () (at <de7b1a1aae914eeb971ea7e6e6371b1e>:IL_0019)
MoreShipUpgrades.Plugin.Awake () (at <de7b1a1aae914eeb971ea7e6e6371b1e>:IL_0176)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Failed to change display to ExclusiveFullscreen...reverting to FullscreenWindow
[Info   : Unity Log] Saving changed settings
[Info   : Unity Log] subcribing to steam callbacks
Setting breakpad minidump AppID = 1966720
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199174389848 [API loaded no]
[Info   : Unity Log] file vers: 0 not compatible; 60
[Info   : Unity Log] Displaying menu notification: Some of your save files may not be compatible with version 60 and may be corrupted if you play them.
[Info   : Unity Log] Returning week num: 47
[Info   : Unity Log] week num: 47
[Info   : Unity Log] host button pressed
[Info   : Unity Log] Returning week num: 47
[Info   : Unity Log] Displaying menu message
[Info   : Unity Log] Connection approval callback! Game version of client request:
[Info   : Unity Log] Joining client id: 0; Local/host client id: 0
[Info   : Unity Log] Stopped connection approval callback, as the client in question was the host!
[Warning: Unity Log] [Netcode] You cannot decline the host connection. The connection was automatically approved.
[Info   : Unity Log] started host!
[Info   : Unity Log] are we in a server?: True
[Info   : Unity Log] Lobby has been created
[Warning: Unity Log] [Dissonance:Recording] (08:56:35.068) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.151345)
[Info   :More Ship Upgrades] [LguStore] No save file found for slot 2. Creating new.
[Info   :More Ship Upgrades] Random upgrades seed wasn't set, calculating a new seed..
[Info   :More Ship Upgrades] [LguStore] SteamID is not available yet, waiting...
[Info   :More Ship Upgrades] Registering key item under level 0 of Fusion Matter
[Info   :More Ship Upgrades] Registering flashlight item under level 0 of Fusion Matter
[Info   :More Ship Upgrades] Registering walkie-talkie item under level 0 of Fusion Matter
[Info   :More Ship Upgrades] Registering shovel item under level 1 of Fusion Matter
[Info   :More Ship Upgrades] Registering pro-flashlight item under level 1 of Fusion Matter
[Info   :More Ship Upgrades] Registering belt bag item under level 2 of Fusion Matter
[Info   :More Ship Upgrades] Registering radar-booster item under level 2 of Fusion Matter
[Info   :More Ship Upgrades] [Hunter] Hoarding Bug set to be harvestable at level 1
[Info   :More Ship Upgrades] [Hunter] Snare Flea set to be harvestable at level 1
[Info   :More Ship Upgrades] [Hunter] Spore Lizard set to be harvestable at level 1
[Info   :More Ship Upgrades] [Hunter] Bunker Spider set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Baboon Hawk set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Tulip Snake set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Kidnapper Fox set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Bracken set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Eyeless Dog set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Half/Thumper set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Manticoil set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Maneater set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Forest Giant set to be harvestable at level 4
[Info   :More Ship Upgrades] [UpgradeBus] Successfully reconstructed with hosts config.
[Info   :More Ship Upgrades] [LguStore] Successfully spawned 54 upgrade objects.
[Info   : Unity Log] Enabling connection callbacks in StartOfRound
[Info   : Unity Log] Began listening to SceneManager_OnLoadComplete1 on this client
[Info   : LethalLib] Adding 0 unlockables to unlockables list
[Info   : LethalLib] Adding 2 items to terminal
[Warning: Unity Log] damageTrigger is disabled! Netcode for GameObjects does not support spawning disabled NetworkBehaviours! The InteractTrigger component was skipped during spawn!
[Info   : LethalLib] Found 13 prefabs to fix
[Info   : Unity Log] 1107298560
[Info   : Unity Log] 1107298560
[Info   : Unity Log] level id: 0
[Info   : Unity Log] Changing level
[Info   : Unity Log] Loading from data: for 41 Experimentation: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 220 Assurance: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 56 Vow: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 71 Gordion: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 61 March: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 20 Adamance: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 85 Rend: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 7 Dine: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 21 Offense: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 8 Titan: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 68 Artifice: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 44 Liquidation: iterations at 0, starting at node #-1
[Info   : Unity Log] Loading from data: for 5 Embrion: iterations at 0, starting at node #-1
[Info   : Unity Log] Weather chance: 0.7886578; 1
[Info   : Unity Log] Item sales percentages #0: 0
[Info   : Unity Log] Item sales percentages #1: 0
[Info   : Unity Log] Item sales percentages #2: 0
[Info   : Unity Log] Item sales percentages #3: 0
[Info   : Unity Log] Item sales percentages #4: 0
[Info   : Unity Log] Item sales percentages #5: 0
[Info   : Unity Log] Item sales percentages #6: 0
[Info   : Unity Log] Item sales percentages #7: 0
[Info   : Unity Log] Item sales percentages #8: 0
[Info   : Unity Log] Item sales percentages #9: 0
[Info   : Unity Log] Item sales percentages #10: 0
[Info   : Unity Log] Item sales percentages #11: 0
[Info   : Unity Log] Item sales percentages #12: 0
[Info   : Unity Log] Item sales percentages #13: 0
[Info   : Unity Log] Item sales percentages #14: 0
[Info   : Unity Log] Item sales percentages #15: 0
[Info   : Unity Log] Item sales percentages #16: 0
[Info   : Unity Log] Item sales percentages #17: 0
[Warning: Unity Log] NetworkVariable is written to, but doesn't know its NetworkBehaviour yet. Are you modifying a NetworkVariable before the NetworkObject is spawned?
[Info   : Unity Log] Suits: 1
[Info   : Unity Log] Suit #0: 0
[Info   : Unity Log] pos: (-2.45, 2.75, -8.41); rot: (0.00, 90.00, 0.00)
[Info   : Unity Log] Key 'shipGrabbableItems' does not exist
[Info   : Unity Log] Loaded vehicle ID: -1
[Info   :More Ship Upgrades] Registering key item under level 0 of Fusion Matter
[Info   :More Ship Upgrades] Registering flashlight item under level 0 of Fusion Matter
[Info   :More Ship Upgrades] Registering walkie-talkie item under level 0 of Fusion Matter
[Info   :More Ship Upgrades] Registering shovel item under level 1 of Fusion Matter
[Info   :More Ship Upgrades] Registering pro-flashlight item under level 1 of Fusion Matter
[Info   :More Ship Upgrades] Registering belt bag item under level 2 of Fusion Matter
[Info   :More Ship Upgrades] Registering radar-booster item under level 2 of Fusion Matter
[Info   :More Ship Upgrades] [Hunter] Hoarding Bug set to be harvestable at level 1
[Info   :More Ship Upgrades] [Hunter] Snare Flea set to be harvestable at level 1
[Info   :More Ship Upgrades] [Hunter] Spore Lizard set to be harvestable at level 1
[Info   :More Ship Upgrades] [Hunter] Bunker Spider set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Baboon Hawk set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Tulip Snake set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Kidnapper Fox set to be harvestable at level 2
[Info   :More Ship Upgrades] [Hunter] Bracken set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Eyeless Dog set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Half/Thumper set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Manticoil set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Maneater set to be harvestable at level 3
[Info   :More Ship Upgrades] [Hunter] Forest Giant set to be harvestable at level 4
[Info   :More Ship Upgrades] [UpgradeBus] Successfully reconstructed with hosts config.
[Info   : Unity Log] Group credits: 60
[Info   : Unity Log] planet mold states length: $13
[Info   : Unity Log] Called teleport function on Player
[Info   : Unity Log] Taking control of player Player and enabling camera!
[Info   : Unity Log] Called teleport function on Player (1)
[Info   : Unity Log] Called teleport function on Player (2)
[Info   : Unity Log] Called teleport function on Player (3)
[Info   : Unity Log] Starting voice tracking for player: adeyUnivaG
[Info   : Unity Log] !!!! ENABLING CAMERA FOR PLAYER: Player
[Info   : Unity Log] !!!! connectedPlayersAmount: 0
[Info   : Unity Log] Has beta?: {hasBeta}
[Info   : Unity Log] Has beta save data: True
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/LightSwitchContainer/PlacementCollider"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/Cube"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/AnimatedShipDoor/HangarDoorLeft (1)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (1)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ControlDesk.001"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (3)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (7)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (6)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (8)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (5)"
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/ShipBottomColliders/Cube (4)"
[Warning: Unity Log] [Dissonance:Recording] (08:56:38.418) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0.1534704)
[Warning: Unity Log] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Environment/HangarShip/StorageCloset/Cube.000/Cube"
[Info   :More Ship Upgrades] [LguStore] Loading SteamID: 76561199174389848
[Info   :More Ship Upgrades] [LguStore] 76561199174389848 Was not found in save dictionary! Creating new save for ID.
[Info   : Unity Log] Set interminalmenu to true: True
[Error  : Unity Log] Trying to add Caret (TMPro.TMP_SelectionCaret) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
[Info   :More Ship Upgrades] [LguStore] Applying loaded upgrades...
[Info   : Unity Log] Could not parse word: lgu`

**Comment by WhiteSpike** [comment]
What version of the game are you trying to play on? Have you tried using the recommended mod version for that game version?

**Comment by adeyUnivaG** [comment]
I've been trying to play on version 64 of Lethal, but im not sure how to run lethal through thunderstore in a different version.

**Comment by adeyUnivaG** [comment]
> What version of the game are you trying to play on? Have you tried using the recommended mod version for that game version?

I looked through the main page of the addon and found what the issue is. 
Sorry for wasting your time.
