### ISSUE TITLE
Item progression: progress for upgrade resets upon save rejoin

### ISSUE THREAD

**Issue by tixomirof** [Malcolm-Q/LC-LateGameUpgrades#579]
I have `Item Progression Mode = CustomScrap` option selected in the config. If I sell listed items for upgrades, it will lower the price of the upgrade (basically a progress to get the next level of that upgrade).
_Ex: I sell 3 metal sheets for running shoes, the price goes 600 -> 500. Everything works as intended. But if I reach autosave and then rejoin the save, the price goes back to 600._

Does not reset upgrade tier upon rejoin, only it's cost.
_Ex 2: I sell 30 metal sheets for running shoes, the price goes 600 -> 550 and I get running shoes tier 1 (1.4 units movement speed increase). If I reach autosave and rejoin, I still have my tier 1 running shoes, but the price goes back to 600._

Maybe that's an intended feature, but it does not reset upgrade's progress upon reaching the next day or quota. So I find it annoying the requirance to keep the save online until you loose, if you want to keep the progress.

I also have `Non-Purchaseable Upgrades = true` , haven't tested without it, but I doubt it's the reason. Leaving this line here in case the issue is not reproducible for some reason. Everything else (besides upgrades costs, values and required items for item progression) is set to default.

**Comment by WhiteSpike** [comment]
3.11.0 release should address this. If you can check, I would appreciate.

**Comment by tixomirof** [comment]
Fixed in 3.11.0, thanks!
