### ISSUE TITLE
Stuck on terminal after getting to the LGU shop screen

### ISSUE THREAD

**Issue by Zediax** [Malcolm-Q/LC-LateGameUpgrades#582]
Each time i try this mod i get stuck on the LGU shop screen and can do anything, i can't move, can't back out, can't even choose options on the shop screen and it doesn't matter if i'm host or guest it always happens, i do not know why but it really is annoying because i really want to try the mod out

the only thing i can provide is that i don't use regular keybinding (zqsd as i have an azerty keyboard) and i would be guessing this is part of the problem but i don't know much about that

**Comment by Zediax** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17756602/LogOutput.log)

i forgot to include it so here's the output

**Comment by WhiteSpike** [comment]
You can change the control bindings to manipulate the screen in the settings menu.

This is of course assuming that you are effectively able to see the upgrade screen just fine and it's just a problem of not being able to manipulate it.

**Comment by Zediax** [comment]
I'll go check that when i get the time and come back to you if that worked on not :)

**Comment by WhiteSpike** [comment]
Did the issue still persist?

If it did, the logs can probably tell me what went wrong during game bootup. You can find them in the BepInEx folder labelled ``LogOutput.log`` which will have the last game session's. If using a mod manager, it should have a prompt to either check the profile folder which contains the first folder or to copy the contents of the log file.

**Comment by Zediax** [comment]
Okay so i finally had the time to check and the thing is that the controls aren't in the name category "Late Game Upgrades" but "Interactive Terminal API" so i thought these were for another mod at the time, maybe changing it could be helpful for people like me who don't play zqsd (or wasd for qwerty keyboards) as it can be confusing :)

**Comment by WhiteSpike** [comment]
Changing what? The prompts are universal from apps made from the API
