### ISSUE TITLE
Some (not all) Scrap Not Appearing at all where the Ship Map Screen Shows it at...

### ISSUE THREAD

**Issue by NIGHTMARE6492** [Malcolm-Q/LC-LateGameUpgrades#586]
When I'm playing with friends, one person most of the time will stay on the ship to help direct me and others around to any scrap around the facilities.  Most of the time, there is a 20% (general guess) or so of the scrap not being where the Ship map says where the scrap item says it should be.  Whether it spawned in the ground, wall, or just not actually spawned is hard to say.  My mod profile list currently with R2MODMAN is " 019363ba-c15f-cf8d-3899-0250c8d0b1a7 " .  I am not sure what is causing the issue, any insight on what could be causing this issue would be greatly appreciated.  As we never had this be an issue before downloading the current late game upgrades mod.

**Comment by WhiteSpike** [comment]
It could be possibly the contract objects. They still spawn regardless of having a contract or not. However, when they check that their contract isn't active or they are not in the right planet to appear, they get destroyed. However, the radar icons seem to be separate to the item so destroying one doesn't destroy the other.

I have added the check to destroy the icon aswell. Hopefully this will solve the ghost radar icons appearing when I make a release afterwards.

**Comment by WhiteSpike** [comment]
3.11.0 release should address this. If you can check, I would appreciate.

**Comment by NIGHTMARE6492** [comment]
I'll check it out as soon as I can, will let you know when I do.

**Comment by NIGHTMARE6492** [comment]
> 3.11.0 release should address this. If you can check, I would appreciate.

After a couple nights of playing the new update with my Wife, we only had 1 instance of an item not being where it should be.  Though that was in one of Wesley's Interior areas in the Factory looking tile set with the big robots and elevators, so it could've just been a bad spawn.  

However basically on everything else Vanilla and a few other modded interiors, had no issues having the items be where the monitor was showing them.

Will do more testing when I can this week, but if I don't reply anything more then I would say the update looks like a success so far, awesome work 👍
