### ISSUE TITLE
Idea:  Malware Grenade & Suggestion: Advanced Portable Teleporter

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#6]
First, the suggestion. In version 1.2.0, the Advanced Portable Teleporter received a nerf making it now has a 20% chance to break, which I personally think is not very good. 

Reason: a Portable Teleporter cost only 300 but has 90% chance of self destruct; an Advanced Portable Teleporter cost 1750 but has 20% chance of self destruct. To me, I think there's no longer a point to buy an Advanced Portable Teleporter. Why? Since both teleporters basically do the same thing and both can break now, meaning players can be super unlucky and have an 1750 Advanced Portable Teleporter break the first time they use it... 

Just to make things more easy to understand, with this nerf, it would require **"a player to use an Advanced Portable Teleporter 6 times in a row without breaking it to finally make up against the normal ones"**. In other words, everyone can ditch the Advanced Portable Teleporters and just buy the normal ones instead.

Not gonna lie, it's nice if the usual Portable Teleporters don't break after using, but if they do break, I can just go buy another one, not a big deal. On the other hand, I'm not gonna risk spending a solid 1750 to buy an Advanced Portable Teleporter just to have it break after less than 6 uses.

**Edit: Did a quick calculation, the chance of a player keeping an Advanced Portable tele after 6 uses is around 26.2%; while the chance of a player gaining at least one additional use from normal Portable teles after 6 uses is around 46.8%. The Advanced Portable tele is actually the "inferior" option at this point. Not to mention taking its tremendous price into consideration.**

Idea for a new shop item: Malware grenade (single use item similar to stun grenade)

Reason: We have Malware Broadcaster which is a ship upgrade and cause turrets/landmines to explode (Neat!). However, it still requires players to use the terminal. Then... what if there's no one capable of doing it atm? Suppose all your friends are dead and you're the only one alive... How can you disable turrets and mines that are standing in your way?

Overall, I think this item can be very useful for small teams or even single player teams, both lack the manpower to use the terminal 24-7. This item also won't negat the Malware Broadcaster since one costs some money after each use, while the other one is forever free after the initial purchase.

English not my native, sorry if my English is bad :(

**Comment by Malcolm-Q** [comment]
It's been reduced to 10% and additionally the latest update introduced a thorough config file so this and many other things can be tweaked to align with how you like to play.
