### ISSUE TITLE
Crash: Beekeeper Upgrade / Being attacked by Circuit Bees

### ISSUE THREAD

**Issue by Uncryptical** [Malcolm-Q/LC-LateGameUpgrades#7]
I noticed that buying the Beekeeper upgrade causes the game to crash right when you get attacked by the circuit bees.
I've tested this with multiple mods, as well as disabling every other mod but it immediately closes the game right when i take an instance of damage from the circuit bees.

But, i did notice that it did NOT crash before i bought the upgrade. Using the r2rmodman mod manager, i have created fresh installs of the mod without changing anything from the config. The circuit bees attack me and i am able to take damage without the game crashing. Any help would be appreciated.

**Comment by Uncryptical** [comment]
I also forgot to note: this crash is only occurring in Versions 1.2.5 and newer. I have tried this with v1.2.0 and it is no longer crashing. So my temporary solution is to use Version 1.2.0 for the time being.

**Comment by Malcolm-Q** [comment]
Hi, thanks for letting me know. I'll try recreate this first thing in the morning. Were you playing as a remote client or a host when your crash occured?

This will be fixed tomorrow. Sorry for the inconvenience. Feel free to join the linked discord to discuss the mod further and help test updates before they're released.

**Comment by Vynxly** [comment]
+1
Was happening to me and my buddies earlier, we bought the beekeeper upgrade, and as soon as the bees went to sting me, I crashed, we relaunched and went to go get stung again to see if it would happen again and my buddy crashed just before getting stung.
Using the Harmful Business modpack

**Comment by Malcolm-Q** [comment]
Thanks for including the modpack I'll check it out. I had two other people test with no crash but haven't personally tried it. Did you or someone you played with change the config file for the bee damage?

**Comment by Vynxly** [comment]
> Thanks for including the modpack I'll check it out. I had two other people test with no crash but haven't personally tried it. Did you or someone you played with change the config file for the bee damage?

Nah, we didn't mess with the config. When I tested solo, it didn't crash my game, but when we were in a game together, that's when it would occur

**Comment by Uncryptical** [comment]
> Hi, thanks for letting me know. I'll try recreate this first thing in the morning. Were you playing as a remote client or a host when your crash occured?
> 
> This will be fixed tomorrow. Sorry for the inconvenience. Feel free to join the linked discord to discuss the mod further and help test updates before they're released.

I was playing as a host when this occurred, but i haven't tested enough to find out if it also causes crashes to clients.

**Comment by Uncryptical** [comment]
> Hi, thanks for letting me know. I'll try recreate this first thing in the morning. Were you playing as a remote client or a host when your crash occured?
> 
> This will be fixed tomorrow. Sorry for the inconvenience. Feel free to join the linked discord to discuss the mod further and help test updates before they're released.


Alright this may solve @Vynxly 's problem but after updating to V1.3.1, i wasn't crashing anymore which is a great sign. I tried playing this with a friend to see if the client crashed, and fortunately it did not crash either. I have also tested messing with the config files (i.e. changing prices and the damage multiplier of the Beekeeper upgrade) and no crashes have yet to happen.

Thank you for patching the crash!

**Comment by Malcolm-Q** [comment]
@Uncryptical Thanks for the update. Yeah I switched it to a more broad and simpler solution in V1.3.0.

Thanks again for letting me know about this.
