### ISSUE TITLE
New tool and weapon Idea

### ISSUE THREAD

**Issue by DigitalIver** [Malcolm-Q/LC-LateGameUpgrades#70]
'Item Tripwire: that stun or damage anything that touch it. Cost: 75 for a single use.'
'Item or Upgrade Exo_Suit: Allow you to carry more than one 2 handed scrap. Cost: 1050 for a single item or upgrade.'
'Item DoorWedge: Use to lock a door for 30 second, it is removable at any time. Cost: 250 for a single item.'
'Upgrade BountyHunter: Everytime you landing you get a mission to kill a target or multiple target, reward increase depend on the enemies and upgrade level. Cost: 500, level upgrade cost: 400/500/600.'
'Upgrade FeatherFalling: Reduce the damage you take from falling, each upgrade level reduce damage taken by 25%. Cost: 350,
level upgrade cost: 400/450/500.'
'Item InsanityPill: Haunted girl cannot kill you or haunt you for 300 seconds. Cost 400 for a bottle that contain 3 uses.'
'Item Alerter: Create a sound and Ping when a monster is near the item. Cost 180 for a single item.'
'Item Disintegrator: A weapon that has a 6 second charge can kill almost anything 1 shot. Cost: 900 for a single use item.'
'Upgrade EnergyShield: Allow you to block a single hit or more depend on upgrade level, each landing. Cost 1000, level upgrade cost: 1250/1500.'  This is just my Idea hope you add some of them in the feature it ok if you don't i still love your mods and stuff you created keep it up !.

**Comment by Malcolm-Q** [comment]
A lot of good ideas here, thanks

**Comment by Malcolm-Q** [comment]
moved to discussions https://github.com/Malcolm-Q/LC-LateGameUpgrades/discussions/227
