### ISSUE TITLE
Interaction after update 2.8.0+

### ISSUE THREAD

**Issue by Niconoko** [Malcolm-Q/LC-LateGameUpgrades#71]
Can't esc or interact with terminal after the update, it didn't happen until relog/change profile of the save game. Not sure if it was from other mods has yet to update or not compatible to this mod new version. *Maow* :3

**Comment by Malcolm-Q** [comment]
Please attach your logoutput.log file (located in bepinex folder) from a session where this occured.

**Comment by Niconoko** [comment]
https://pastebin.com/eAC3jUE6
Here's the log around when it happens, me open terminal when the game start is fine, playing just fine, until relog at some point, can no longer click esc and when click into terminal, can't close it.

Me think it causes by LC API, but me not sure.

**Comment by Niconoko** [comment]
It was Terminal Game mod and it's API from what me have removed and it's back to normal so far. *Maow* :3
