### ISSUE TITLE
Issue with Giftboxes Infinitely Spawning Scrap.

### ISSUE THREAD

**Issue by PapaVortex** [Malcolm-Q/LC-LateGameUpgrades#72]
I am finding an issue where Gift Boxes will freeze the game and create the infinite spawn glitch where the box cannot be taken out of your hot bar unless disconnected or killed and every time you use the open keybind for the box, it will simply spawn another piece of scrap and never disappear. This was tested over several runs using a mod menu to spawn in the gift boxes and confirmed that they reliably open with no issue with the mod disabled and the issue persists with the mod enabled.

LogOutput.log File:
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13758174/LogOutput.log)

Mod List:
LCBetterSaves by Pooble
LC_API by 2018
Mimics by x753
MoreScreams by egeadam
LateCompany by anormaltwig
LethalLoudnessMeter by extraes
WackyCosmetics by EliteMasterEric
HookGenPatcher by Evaisa
BepInExPack by BepInEx
EmployeeAssignments by amnsoft
LethalLib by Evaisa
LCSoundTool by no00ob
HDLethalCompany by Sligili
More_Suits by x753
DynamicDeadline by Krayken
TerminalApi by NotAtomicBomb
MoreCompany by notnotnotswipez
Helmet_Cameras by RickArg
Skinwalkers by RugbugRedfern
ScalingStartCredits by sunnobunno
LethalThings by Evaisa
HealthMetrics by matsuura
DetailedScan by fivetoofive
ScanForEnemies by 299792458
WeatherMultipliers by Blorb
LethalExtras by joe1359
Strange_Objects by togglemybits
MoonOfTheDay by MaxWasUnavailable
HealthStation by Thorlar
MoreBlood by FlipMods
VoiceHUD by 5Bit
FasterItemDropship by FlipMods
ShipClock by ATK
LetMeLookDown by FlipMods
ShipLoot by tinyhoot
GameMaster by GameMasterDevs
Lategame_Upgrades by malco

To replicate simply load up the game with the mods listed or download my modpack: Lethalest_Of_Companies (How I found the issue in the first place) and find a few giftboxes and attempt to open them all.

**Comment by Malcolm-Q** [comment]
This should be fixed on 2.8.1
Are you on 2.8.1 or 2.8.0?

**Comment by PapaVortex** [comment]
I was on 2.8.0 at the time as my Thunderstore never notified me to update it, my mistake, thank you for the clarification.

**Comment by Malcolm-Q** [comment]
Right on. Thanks for such a detailed bug report none the less.

**Comment by PapaVortex** [comment]
Of course, gotta respect the people who can do what I can't.
