### ISSUE TITLE
Shovel seems to damage both the player and the person being hit

### ISSUE THREAD

**Issue by greenskye** [Malcolm-Q/LC-LateGameUpgrades#75]
I think this may be tied to the stimpack upgrade, but if you hit another player with the shovel it will damage them and you for some reason.

**Comment by Malcolm-Q** [comment]
All of whitespikes recent pull requests are now live in version 2.8.3
I haven't tested anything but there was a pull request that changed shovel behavior so if you test it again and it fixes it please let me know.

**Comment by Malcolm-Q** [comment]
I'll close this since I haven't heard anything back
