### ISSUE TITLE
How to assign Night Vision hotkey to '~' key?

### ISSUE THREAD

**Issue by greenskye** [Malcolm-Q/LC-LateGameUpgrades#76]
I've tried OemTilde, Tilde, BackQuote, ~, `

None appear to work. Any ideas on what to use?

**Comment by Malcolm-Q** [comment]
https://docs.unity3d.com/ScriptReference/KeyCode.html

>Tilde '~' key. Deprecated if "Use Physical Keys" is enabled in Input Manager settings, use KeyCode.BackQuote instead.

BackQuote should be working. I'm not at my PC rn but I can look into this sometime soonish.

**Comment by WhiteSpike** [comment]
"Backquote" has worked for me. "BackQuote" does not.

Closing this as no answers from some time.
