### ISSUE TITLE
Reopen: v2.8.2 Bug: Stimpack Damage Issue

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#78]
Sorry, I tried to reopen the previous one but I don't have the "Reopen Issue" button at the bottom of the page.
After updating to v2.8.2, I found the Stimpack Damage Registration is still bugged.

Just like before, 500 Health and jumping down from the railings outside Experimentation Fire Exit.
![LGU001](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/7483cb7a-7c63-4cd2-b2d4-1098a92d21d5)

After the first jump, I'm already at 60 HP.
![LGU002](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/e3976a76-b0dd-4508-9caf-ccb23af7f153)

Using the Medkit once, I'm already 200 HP despite I never set it to heal that amount (see below).
![LGU003](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/8ef8fd91-a99a-43bf-9d79-7cf4d3322aa9)

I should be 160 HP if the config heal amount is talking about number instead of percentage, and if it's talking about percentage I should be healed back to 500 HP unless it's capped at 200 HP. (Subsequent healings couldn't heal me above 200, making me believe it's capped at 200 HP)
![LGU004](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/c237c3c7-77f5-4e88-83f1-c1c5f7495b03)

Go back up to the railings (now 200 HP), I jumped down again.
![LGU005](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/90866317-179d-412e-871e-a6b6f5d58a2a)

My health is again 60 HP.
![LGU006](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/8908f4e8-aed0-4bc1-b0c1-2191413e8c0b)

Combining with my previous post, I think the fall damage was pretty consistent to be 40 HP per jump. However, the next jump already put my health lower than 20 HP. (Originally, it's 500 -> 100 -> 60 -> 20 -> Below 20; Now, it's 500 -> 60 -> Below 20. Don't know why...)
![LGU007](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/82710934/207f90c9-43f2-45ba-8204-551b9cee1c1b)

I only tested fall damage, not sure how other damage react to Stimpack.
The Medkit critically injured has been fixed.

**Comment by Malcolm-Q** [comment]
All of whitespikes recent changes are now live in the 2.8.3 hotfix so this may be fixed. I haven't checked out all the changes or tested anything but it should be safer simpler code now. If you test it out, let me know how it goes. I'll leave this open.

**Comment by FireGeneral** [comment]
> All of whitespikes recent changes are now live in the 2.8.3 hotfix so this may be fixed. I haven't checked out all the changes or tested anything but it should be safer simpler code now. If you test it out, let me know how it goes. I'll leave this open.

Understood! Sorry for the late reply, I was sleeping... I'll go check it out now!
Thank you for the hard work!

**Comment by WhiteSpike** [comment]
Closing this issue since it was resolved.
