### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Niconoko** [Malcolm-Q/LC-LateGameUpgrades#8]
1. Those physical perks are individual, or one for everyone once purchased?
2. Me playing solo and bought 2 light footed, the message show that me have 2 light footed perks in the list, is that normal?
   That's it for now, thx in adv. *Maow* :3

**Comment by Malcolm-Q** [comment]
All perks are applied to everyone and should only be bought once. Next update will introduce a custom shop solution with logic more fine tuned for the mod. This has been a goal for a bit now so putting bandaids on the current shop solution has been ignored and I've put my effort towards more pressing issues. Thanks.
