### ISSUE TITLE
Disconnecting makes power ups go away

### ISSUE THREAD

**Issue by dtammisd** [Malcolm-Q/LC-LateGameUpgrades#89]
After you buy a power-up and then you leave the game (not die) it still goes away. why does it do that because it sucks.

**Comment by Malcolm-Q** [comment]
It shouldn't do that.

Are you playing on LAN?
Are you using LC better saves?
How many mods are you using?
What version of the game and mod are you playing on?

Provide info when creating an issue please.

**Comment by dtammisd** [comment]
yes im using better saves is that the issue?

**Comment by WhiteSpike** [comment]
The issue with better saves is that past 9 saves, it reshuffles the saves due to the ordering they are using.
As far as I am aware, below 9 saves worked perfectly fine between BetterSaves 1.6.0 and LGU.
