### ISSUE TITLE
Uninstalling the mod breaks the base game

### ISSUE THREAD

**Issue by Chimantha** [Malcolm-Q/LC-LateGameUpgrades#92]
I uninstalled lategame upgrades and was no longer able to walk. I tried creating new saves and nothing seems to work. I briefly checked documentation to see if there was an uninstall step but didn't see anything. I've also tried reinstalling lethal company to no avail. Please assist. I'd like to be able to play without the mod.

**Comment by Malcolm-Q** [comment]
Are you loading a save that was made when this mod was installed and contains items from the mod?

**Comment by Chimantha** [comment]
I am not. Complete vanilla works. I'm currently testing to see if my friends who have never installed lgu can walk with the current modpack that doesn't include lgu. Also reinstalling lgu does fix the issue. Having the mod disabled but installed also causes the issue to occur.

**Comment by Chimantha** [comment]
Here's my log output from when I tried to load the game with mods minus LGU
[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13773679/LogOutput.log)

**Comment by Chimantha** [comment]
At the moment I'm doing some process of elimination. So far a game running bepinex and more company works, which leads me to believe that LGU is overriding something else that another mod is breaking.

**Comment by Chimantha** [comment]
Final update: the problem was infinite emotes + more emotes. I guess I was right in that LGU was overriding whatever part that combination was breaking.

**Comment by Malcolm-Q** [comment]
That's a lot of mods and the most broken logoutput.log file I've ever seen.
1. If my mod isn't even loading and effecting the game then it's not breaking it. I guess when it's loaded it's somehow making this mess work funny enough.
2. A lot of these mods are really rough, they're raising exceptions at every single turn, it's remarkable you loaded in.
3. Infinite Emotes input utils is raising exceptions trying to get set up, that could be one place to look
4. More Emotes is raising an exception every single frame in PlayerControllerB.Update (the most important method of the game) preventing the rest of it from executing. That could be another area to look.

Also I don't recognize a lot of these so be careful downloading mods, they're just random files from strangers that can make your pc do anything.
