### ISSUE TITLE
Portable Teleporter set to FALSE to keep items, but acts if it's TRUE?

### ISSUE THREAD

**Issue by ElvesLie** [Malcolm-Q/LC-LateGameUpgrades#99]
You set the value to **FALSE** to have items not teleport with you, yet they still do? I've double, triple and even quadruple checked, turned off all mods and still tested and nothing. It still acts like it's set to **TRUE**.

![image](https://github.com/Malcolm-Q/LC-LateGameUpgrades/assets/66757457/2a09fd29-e049-41ec-8ec3-b4c7e64d124d)

**Comment by WhiteSpike** [comment]
It has been resolved in a [pull request](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/95).
Next release of this mod should have this issue fixed.

**Comment by ElvesLie** [comment]
Thanks for that Spike! I will have to sadly report another issue, though I think it's written this was as intended.

I intended for the Portable Teleporter to not be able to teleport stuff with you, but for the Advanced Teleporter to be able to teleport stuff with you - though, it seems that if you switch it off for the Portable Teleporter that this directly effects the behaviour of the teleporters in general (which I'm sure is how this mod is written).

Is there a possible chance to have it so we can make Advanced Portable Teleporters take stuff with you but no others? Thanks!
